### ISSUE TITLE
RTD package dependency

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CCL#1001]
`m2r2` requires docutils>=0.19 but pins mistune==0.8.4. docutils>=0.19 conflicts with the latest sphinx-rtd-theme requiring docutils<0.18. mistune==0.8.4 is old and conflicts with the requirements of other packages (jupyter related). We can use `sphinx_mdinclude` instead, which is forked from m2r2. (Currently, the only place that needs m2r2 is the `mdinclude` directive in `readthedocs/source/changelog.rst`)

**Comment by hsinfan1996** [comment]
The only difference is that sphinx_mdinclude needs to be installed from PyPi instead of conda.

**Comment by damonge** [comment]
@hsinfan1996 can you suggest a solution?

**Comment by hsinfan1996** [comment]
> @hsinfan1996 can you suggest a solution?

Use `'sphinx_mdinclude'` instead of `'m2r2'` in `readthedocs/conf.py` and `requirements.txt`. (Since the CI check does not include building docs, so we do not have to touch the Github Actions workflows.)
