### ISSUE TITLE
Beyond limber for projected correlation functions

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#1008]
We are implementing a general solution for non-limber C_ells. Do we want/need something specific to projected correlation functions?

For instance, eq 9 of https://arxiv.org/pdf/1411.1755.pdf, which has both k_z and k_perp integrals.

Does anything like this already exist in ccl?

**Comment by elisachisari** [comment]
It doesn't. I've been playing with the "hankel" package and it makes these integrals quite fast. If useful I can make some notebooks available.
