### ISSUE TITLE
Problem installing CCL

### ISSUE THREAD

**Issue by luigilcsilva** [LSSTDESC/CCL#1013]
Dear colleagues,
I am having a problem when installing CCL. I have been stucked in this for hours, searching for solutions, but without success. I will leave the code in a link below, so, if anyone can help me, I will be very grateful.

**Here are the full code:**
[See the full code here](https://drive.google.com/file/d/1wuweMMFWTQvNxcSQpWHyZEfqvECyDVMu/view?usp=sharing)

**Here are some parts of the code, containing the error messages:**
`<pre><font color="#26A269"><b>luigi@luigi-pc</b></font>:<font color="#12488B"><b>~</b></font>$ pip install pyccl
Defaulting to user installation because normal site-packages is not writeable
Collecting pyccl
  Using cached pyccl-2.6.tar.gz (12.6 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from pyccl) (1.21.5)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from pyccl) (5.4.1)
Building wheels for collected packages: pyccl
  Building wheel for pyccl (setup.py) ... error
  <font color="#C01C28"><b>error</b></font>: <b>subprocess-exited-with-error</b>
  
  <font color="#C01C28">×</font> <font color="#26A269">python setup.py bdist_wheel</font> did not run successfully.
  <font color="#C01C28">│</font> exit code: <font color="#2AA1B3"><b>1</b></font>
</pre>`

`<pre> File &quot;/tmp/pip-install-d0u5babn/pyccl_b2508809683b49f7b5624ad905207e36/setup.py&quot;, line 56, in run
  <font color="#C01C28">   </font>     _compile_ccl(debug=self.distribution.debug)
  <font color="#C01C28">   </font>   File &quot;/tmp/pip-install-d0u5babn/pyccl_b2508809683b49f7b5624ad905207e36/setup.py&quot;, line 27, in _compile_ccl
  <font color="#C01C28">   </font>     raise Exception(&quot;Could not build CCL&quot;)
  <font color="#C01C28">   </font> Exception: Could not build CCL
  <font color="#C01C28">   </font> <font color="#C01C28">[end of output]</font>
  
  <font color="#A347BA"><b>note</b></font>: This error originates from a subprocess, and is likely not a problem with pip.
<font color="#C01C28">  ERROR: Failed building wheel for pyccl</font>
  Running setup.py clean for pyccl
Failed to build pyccl
Installing collected packages: pyccl
  Running setup.py install for pyccl ... error
  <font color="#C01C28"><b>error</b></font>: <b>subprocess-exited-with-error</b>
  
  <font color="#C01C28">×</font> <font color="#26A269">Running setup.py install for pyccl</font> did not run successfully.
  <font color="#C01C28">│</font> exit code: <font color="#2AA1B3"><b>1</b></font>
</pre>`

`<pre> File &quot;/tmp/pip-install-d0u5babn/pyccl_b2508809683b49f7b5624ad905207e36/setup.py&quot;, line 56, in run
  <font color="#C01C28">   </font>     _compile_ccl(debug=self.distribution.debug)
  <font color="#C01C28">   </font>   File &quot;/tmp/pip-install-d0u5babn/pyccl_b2508809683b49f7b5624ad905207e36/setup.py&quot;, line 27, in _compile_ccl
  <font color="#C01C28">   </font>     raise Exception(&quot;Could not build CCL&quot;)
  <font color="#C01C28">   </font> Exception: Could not build CCL
  <font color="#C01C28">   </font> <font color="#C01C28">[end of output]</font>
  

  <font color="#A347BA"><b>note</b></font>: This error originates from a subprocess, and is likely not a problem with pip.
<font color="#C01C28"><b>error</b></font>: <b>legacy-install-failure</b>

<font color="#C01C28">×</font> Encountered error while trying to install package.
<font color="#C01C28">╰─&gt;</font> pyccl

<font color="#A347BA"><b>note</b></font>: This is an issue with the package mentioned above, not pip.
<font color="#2AA1B3"><b>hint</b></font>: See above for output from the failure.
</pre>`

**I will also leave the full code attached:**
[CCL-error-Luigi.pdf](https://github.com/LSSTDESC/CCL/files/10332155/CCL-error-Luigi.pdf)

Thank you in advance!

**Comment by hsinfan1996** [comment]
Looks like SWIG is not installed on your system.

**Comment by luigilcsilva** [comment]
It worked perfectly! I have spent some hours analyzing the code, and I didn't realize that. Thank you so much!

**Comment by hsinfan1996** [comment]
Glad to hear the problem is fixed.
