### ISSUE TITLE
Unit tests and integration with Travis CI

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/CCL#102]
@dkirkby suggested using python unit tests to do integration with Travis CI. The plan is use `astropy` to check the accuracy of the parts that are already implemented there. This will be implemented in the branch `travis_integration`

**Comment by elisachisari** [comment]
To be completed after public release.

**Comment by fjaviersanchez** [comment]
Guys, I managed to install and run the tests at Travis but I get a segmentation fault. It's in `ccl_test_pyccl_interface.py` in the power-spectra and `sigmaR` part. I suspect that Travis is running out of memory (which it's kind of surprising since I think that the tests are kind of lightweight). Any ideas? @damonge @philbull @dkirkby @elisachisari

**Comment by elisachisari** [comment]
@fjaviersanchez would you like to close this issue and make a separate issue for pip installation?

**Comment by fjaviersanchez** [comment]
Yes!
