### ISSUE TITLE
Action to publish to Anaconda

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#1036]
Every new tag is also published on PyPI with a release workflow. We can do the same for Anaconda and avoid having to do it manually.
https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org

**Comment by rmjarvis** [comment]
Conda-forge should automatically notice your new tag and made a new conda release.  Is that not already automatically happening?

**Comment by nikfilippas** [comment]
If that is the case, I didn't know. How does conda-forge realize when a new tag is marked? Is this in the docs somewhere?
Feel free to close this.

**Comment by rmjarvis** [comment]
I don't know how they know, but all my repos get conda-forged automatically after tagging.

**Comment by nikfilippas** [comment]
@damonge did you have to do anything else after you tagged 2.6.1 or did everything happen automatically?

**Comment by damonge** [comment]
It's all automatic

**Comment by nikfilippas** [comment]
Ok great, closing this then!

**Comment by nikfilippas** [comment]
false closing tag
