### ISSUE TITLE
A question regarding M_vir mass definition within CCL

### ISSUE THREAD

**Issue by dwhan89** [LSSTDESC/CCL#1067]
I have a quick question about the mass definition used in the pyccl library. 

While calculating the virial radius of halos using the `pyccl.halos.massdef.MassDefVir` object, I found that the overdensity parameter Delta has an extra factor of `1/Omega_m` compared to the standard definition (See [https://github.com/LSSTDESC/CCL/blob/master/pyccl/halos/massdef.py#L140](https://github.com/LSSTDESC/CCL/blob/master/pyccl/halos/massdef.py#L140) and  [https://github.com/LSSTDESC/CCL/blob/master/src/ccl_massfunc.c#L41](https://github.com/LSSTDESC/CCL/blob/master/src/ccl_massfunc.c#L41).).

I checked whether the library uses `rho_m` in the mass definition (i.e such that `Delta/omega_m * rho_m = Delta*rho_crit`), but it doesn't seem like it at a glance ([https://github.com/LSSTDESC/CCL/blob/master/pyccl/halos/massdef.py#L282](https://github.com/LSSTDESC/CCL/blob/master/pyccl/halos/massdef.py#L282)). I'm wondering if you could help me understand why there's a difference and whether I'm missing something simple.

**Comment by nikfilippas** [comment]
I think the difference is there because we define `MassDefVir` in terms of the critical density, which multiplies `Delta` in the radius calculation, as seen [here](https://github.com/LSSTDESC/CCL/blob/master/pyccl/halos/massdef.py#L187).

You may wish to define your own `MassDef("vir", "matter")`, which recovers that extra `1/Omega_m` factor:
```python
cosmo = ccl.CosmologyVanillaLCDM()
print(ccl.halos.MassDefVir().get_radius(cosmo, M=1e14, a=1) / cosmo["Omega_m"]**(1/3))
print(ccl.halos.MassDef("vir", "matter").get_radius(cosmo, M=1e14, a=1))

1.2373782561528808
1.2373782561528808
```

**Comment by damonge** [comment]
@dwhan89 I think you're right, this is definitely a bug. We should either remove the Om factor from [here](https://github.com/LSSTDESC/CCL/blob/4e36b13bc06b9e7f46018a7d332b642d71e38f0d/src/ccl_massfunc.c#L41), or use `'critical'` [here](https://github.com/LSSTDESC/CCL/blob/4e36b13bc06b9e7f46018a7d332b642d71e38f0d/pyccl/halos/massdef.py#L288).

I think the former (i.e. fixing the C code) is the only proper way of doing this.
