### ISSUE TITLE
Instabilities in the calculation of power spectra depending on rho^2

### ISSUE THREAD

**Issue by andrearubiola** [LSSTDESC/CCL#1088]
Good morning, 

I am working with annihilating dark matter power spectra, which depend on a rho^2 density profile, rho being the usual NFW model. 
Whilst power spectra depending on rho are rather stable even when integrated across many orders of magnitude (up to 10^-7 - 10^18 M_sun), those depending on rho^2 are more unstable. In particular, once the the mass interval for the integration has been chosen, there is a huge variability on the k_min parameter within the function HMcalculator (I attach an example below, 
contrasting the rho and the rho^2 cases). 
Furthermore, the k_min providing the correct normalisation, matching the papers I am trying to replicate, is around 2 Mpc^-1 and there's no specific reason for that other than fine tuning. 
Thank you, 
Best
Andrea

 
![immagine](https://github.com/LSSTDESC/CCL/assets/59877325/3d7f38c9-a676-4283-a388-564295dc2c1a)
![immagine](https://github.com/LSSTDESC/CCL/assets/59877325/d1b1f9c5-a894-4f68-93ea-36005d32b45c)

**Comment by damonge** [comment]
Hi @andrearubiola . `k_min` only matters if you're using `norprof=True` in the HMCalculator methods (note that all of this will be deprecated in the new - imminent CCL version).

In your case, I don't think you want to normalise your profiles by the mass integral of their value at low k (this is what normprof does). This is usually only useful for overdensity-like quantities, which are normalised by the mean density. Instead you probably want to ensure the profiles are correctly normalised by default.

**Comment by andrearubiola** [comment]
Hi, I was actually needing to normalise the profiles because this is the way they are shown in my reference papers, where they are all in Mpc^3 units and hence comparable with the matter power spectrum. More generally, there might be cases where a trustworthy calculation of <rho^2> could be needed, so I thought it could be useful to raise the issue.
Many thanks

**Comment by damonge** [comment]
OK, thanks. I'll close this for now, but feel free to reopen if this crops up again.
