### ISSUE TITLE
Bug: `angular_cl_cov_SSC` and `angular_cl_cov_cNG` do not accept `None` for `tkka` argument

### ISSUE THREAD

**Issue by davidesciotti** [LSSTDESC/CCL#1091]
Contrary to what reported in the [documentation](https://ccl.readthedocs.io/en/latest/api/pyccl.core.html#pyccl.core.Cosmology.angular_cl_cov_SSC), the `angular_cl_cov_SSC` and `angular_cl_cov_cNG` functions do not accept `None` as value for the `tkka` argument. Moreover, the formula in the documentation is exactly the same (including the cNG subscript in the left hand side). PyCCL version: 2.8.0

This is the error:

```
    tsp = t_of_kk_a.tsp
AttributeError: 'NoneType' object has no attribute 'tsp'
```

PS if indeed these covariance functions do not accept `None` as input value, in the case of number counts should I pass the `tkka` computed with `HaloProfileHOD`? 
```
import pyccl as ccl
halo_profile = ccl.halos.profiles.HaloProfileHOD(c_M_relation=c_M_relation)
tkka = ccl.halos.halo_model.halomod_Tk3D_SSC(cosmo, hmc, prof1=halo_profile, ...)
```

because when calling `HaloProfileHOD` I get the error
```
/opt/anaconda3/lib/python3.9/site-packages/pyccl/halos/pk_4pt.py:518:
RuntimeWarning: invalid value encountered in true_divide
dpk12[ia] = ((47/21 - dpk/3)*i11_1*i11_2*pk + i12_12) / (norm1 * norm2)
```

**Comment by damonge** [comment]
Hi @davidesciotti . Apologies for the delay. Indeed, `tkka` can't be `None`. This is an issue with the documentation.

Regarding the `true_divide` warning, this might happen when you're in a regime in which the average number of galaxies per halo is zero. This might happen at very high redshifts, depending on the HOD parameters you're using, so perhaps worth limiting the range of `a` over which you generate the trispectrum.

**Comment by davidesciotti** [comment]
Hi @damonge, thanks a lot for the reply, this is much clearer now.
