### ISSUE TITLE
Numerical instability of Hernquist `_fx_projected` and `_fx_cumul2d` when x is close to 1

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CCL#1095]
Need to Taylor expand the `np.arccos`, `np.arccosh` and `np.fabs(x2m1)**m` terms. I have the expressions of the series, but still need to determine at what value of x should we start to use those approximations.

**Comment by rmjarvis** [comment]
I suspect you could just use the identities:

acosh(1/x) = asinh(sqrt(1-x^2)/x)
acos(1/x) = asin(sqrt(x^2-1)/x)

I would guess that just switching to these would be sufficiently stable when x^2-1 is close to 0.

**Comment by hsinfan1996** [comment]
> I suspect you could just use the identities:
> 
> acosh(1/x) = asinh(sqrt(1-x^2)/x) acos(1/x) = asin(sqrt(x^2-1)/x)
> 
> I would guess that just switching to these would be sufficiently stable when x^2-1 is close to 0.

asinh and asin work, which will make the fix easier. Thank you.
