### ISSUE TITLE
Pyccl.halos.profile

### ISSUE THREAD

**Issue by Jane550** [LSSTDESC/CCL#1124]
Hi all! I want to compute the excess surface density of an NFW halo analytically using pyccl.halos.profile package. I now use 'HaloProfileNFW.cumul2d()-HaloProfileNFW.projected()'. Is it the right way to do it or is there any other simpler way? Also I want to check whether 'cumul2d' and 'projected' return the comoving or physical surface density.

**Comment by hsinfan1996** [comment]
I believe using `cum2d - projected` is the only way to obtain the excess surface density profile. The returns are comoving density.

**Comment by Jane550** [comment]
Sure, Many thanks!

**Comment by damonge** [comment]
Hi @Jane550 . Yes, the way the current code is structured is optimized for halo model power spectrum/correlation function calculations, which calculate all the possible combinations between `M` and `r`. For your case, would calling `cumul2d` inside a loop that runs over the different values of `M`, `R`, and `z` work? Or would that be too slow? My first guess is that the time wasted in looping would be small compared to evaluating the expressions that go into `cumul2d`, so perhaps it's not the worst solution...

**Comment by Jane550** [comment]
No, the loop is too slow. I'm calculating the ESD as model predictions in a Bayesian parameter inference, so I need to calculate these many many times. And each time calling the likelihood (calculating the ESD), the length of $M,R,z$ is of order $10^7$.

**Comment by damonge** [comment]
OK, I see. I think the easiest option for now would be for you to hack/reimplement this function:
https://github.com/LSSTDESC/CCL/blob/6b08a255f2878ffd6ebe045d3d95b103fddef77f/pyccl/halos/profiles/nfw.py#L161
which implements the ESD of an NFW profile. Would that work?

Once you have that, we may be able to put it back into CCL (although it'd be great to think of a way to do it that is completely generalisable to the other profiles - including those in which the calculation needs to go through FFTLog).
