### ISSUE TITLE
Inconsistent naming of BaccoEmu Baryons object

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#1125]
The `BaccoemuBaryons` object should be called `BaryonsBaccoemu` to conform with the naming of other baryonic effect objects (e.g. `BaryonsSchneider15` or `BaryonsVanDaalen19`).

Unfortunately this slipped through after tagging v3, and changing it would break the API. Thoughts?

**Comment by damonge** [comment]
The solution should be to rename a `BaccoemuBaryons` into `BaryonsBaccoemu`, and create a class called `BaccoemuBaryons` that inherits from it and simply throws a deprecation warning if initialised.

**Comment by nikosarcevic** [comment]
> The solution should be to rename a `BaccoemuBaryons` into `BaryonsBaccoemu`, and create a class called `BaccoemuBaryons` that inherits from it and simply throws a deprecation warning if initialised.

I would suggest naming it "BaryonsArico20" to keep consistent with other modules.

**Comment by zdu863** [comment]
> The solution should be to rename a `BaccoemuBaryons` into `BaryonsBaccoemu`, and create a class called `BaccoemuBaryons` that inherits from it and simply throws a deprecation warning if initialised.

Do we need to create separate unit tests for the deprecated class?
