### ISSUE TITLE
typo in correlation method

### ISSUE THREAD

**Issue by nikosarcevic** [LSSTDESC/CCL#1132]
not sure if this typo is still in ccl v3 but im running v2.8 and found this typo

correlation(cosmo, ell, C_ell, theta, type, corr_type, method)
    137 method = method.lower()
    139 if type not in correlation_types:
--> 140     raise ValueError(f"Invalud correlation type {type}.")
    142 if method not in correlation_methods.keys():
    143     raise ValueError(f"Invalid correlation method {method}.")
    
    "Invalud"

**Comment by damonge** [comment]
I kind of like "Invalud" :-P.

Thanks for spotting this. Do you mind fixing it here https://github.com/LSSTDESC/CCL/pull/1122 ? It's not really a documentation bug, but also not worth triggering a new PR for it.

**Comment by nikosarcevic** [comment]
> I kind of like "Invalud" :-P.
it is pretty cool 😂😂😂
> 
> Thanks for spotting this. Do you mind fixing it here #1122 ? It's not really a documentation bug, but also not worth triggering a new PR for it.
no problem, ill fix it 😎

**Comment by nikosarcevic** [comment]
DONE.
