### ISSUE TITLE
Able to Define a ccl.WeakLensingTracer() object with has_shear = False and no ia_bias value.

### ISSUE THREAD

**Issue by kaushikchakram** [LSSTDESC/CCL#1133]
Hello,

I was able to define a `ccl.WeakLensingTracer()` where the `has_shear = False`, but no `ia_bias` value was provided for example: [`ia_bias = (z,ia_bias_value)`]. The code did not raise an error. Finally, the error is raised when computing the angular power spectrum [doing an auto correlation (that tracer object with itself)]. The error is raised as follows: `CCLERROR: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error`.

I have attached the images of my code where I define the object and no error is raised and when i compute angular power spectra when the integration error is raised.

1)This Image shows defining the object with  `has_shear=False`, but no `ia_bias` value given.
 
<img width="1159" alt="Screenshot 2023-11-02 at 08 39 51" src="https://github.com/LSSTDESC/CCL/assets/149659649/1f77644e-56fb-4107-ba79-7b593f3211f7">

2) This Image shows the Integration error raised when using the object defined in 1) to compute the angular power spectrum.

<img width="1156" alt="Screenshot 2023-11-02 at 08 41 54" src="https://github.com/LSSTDESC/CCL/assets/149659649/08327ca3-e7a5-4d48-886f-df768a9fce05">

**Comment by tilmantroester** [comment]
What are `z` and `zdistbin_1`?

**Comment by kaushikchakram** [comment]
Hello,
 `z` is the linespace I am using for my redshift distribution and `zdistbin_1` corresponds to those values of the distribution in bin 1. I have segmented the distribution into 5 bins. Below I have attached Images of how they are defined:

1) Shows how  `z` is defined:

<img width="710" alt="Screenshot 2023-11-02 at 11 19 32" src="https://github.com/LSSTDESC/CCL/assets/149659649/f015baba-e235-4fd7-a62d-a92b9139bb4a">

2) This shows the Binning process and How I have gotten the values to correspond to 5 bins:

<img width="809" alt="Screenshot 2023-11-02 at 11 20 01" src="https://github.com/LSSTDESC/CCL/assets/149659649/25572b05-4082-4e86-8106-e26f8bc590c8">

<img width="820" alt="Screenshot 2023-11-02 at 11 20 21" src="https://github.com/LSSTDESC/CCL/assets/149659649/378f19cc-402e-4664-b381-9ade226dab65">

**Comment by tilmantroester** [comment]
Could you upload a single file with the `z` and `zdistbin_1` arrays? We need a minimal working setup to reproduce the error.

For code snippets, using the formatting 
\```python 
your code
\``` 
is preferable to screen shots, since the latter don't allow for copy and paste.

**Comment by kaushikchakram** [comment]
Hello,
Ah Okay. I apologize. In the future I shall use code snippets instead of screenshots. Okay Here are code snippets of the python notebook  (I am running this on gogle collab). In the snippets I have provided just the relevant quantities that I have used  to run the code. Snippets 1 & 2 are just what I need to run the code in terms of installing packages etc. Snippets 3-7 are the relevant Snippets. Snippet 6 is the line that doesn't raise an error when I define the tracer with `has_shear = False` but I proved no `ia_bias`. Then Snippet 7 is the line when I compute the `ccl.angular_cl()` I get the Integration Error message. 

Snippet 1:
```python
#Run this command twice
# I am running this on google Collab
!pip install -q condacolab

import condacolab

condacolab.install()

!mamba install pyccl
```
  
Snippet 2:
```python
import numpy as np
import pylab as plt
import pyccl as ccl
#If this prints '3.0.0', everything is working.
ccl.__version__
```

Snippet 3:
```python
cosmo = ccl.Cosmology(Omega_c = 0.27, Omega_b = 0.045, h = 0.67, sigma8 = 0.83, n_s = 0.96)
z = np.linspace(0.0,3.0,600)
```

Snippet 4 number density distribution defn.:
```python
def dNumdz(i_lim):
  """
  this function takes in the Limiting i-band magnitude and
  returns the number density distribution.
  """
  z0 = 0.0417*i_lim - 0.744
  Ngal = 46. * 100.31 * (i_lim - 25.) # Normalisation, galaxies/arcmin^2
  pz = 1./(2.*z0) * (z / z0)**2. * np.exp(-z/z0) # Redshift distribution, p(z)
  dNdz = Ngal * pz
  return dNdz
```
Snippet 5 Binning Procedure Dividing into 5 Bins:
```python
# Dividing 0<z<=3 5 bins locations 3/5 = 0.6
#1st bin: 0-0.6,2nd bin: 0.6-1.2, 3rd bin: 1.2-1.8, 4th bin: 1.8-2.4,
#5th bin: 2.4-3.0.
#Basically 120 values per bin.

bins_location = [0.0,0.6,1.2,1.8,2.4,3.0]
bins_index = []

for i in range(0,len(bins_location)):
  bins_index.append(np.max(np.where(z<=bins_location[i])))

#print(bins_index)
#1st bin: 0-0.6,2nd bin: 0.6-1.2, 3rd bin: 1.2-1.8, 4th bin: 1.8-2.4,
#5th bin: 2.4-3.0.

#Five Z bins:
zbin_1 = z[0:120]
zbin_2 = z[119:240]
zbin_3 = z[239:360]
zbin_4 = z[459:480]
zbin_5 = z[479:600]

#Five Number distribution bins as Lists to store appropriately:
zndist_full = dNumdz(26)
zndist_1 = [zndist_full[i] if 0<=i<=119 else 0 for i in range(0,len(zndist_full))]
zndist_2 = [zndist_full[i] if 119<i<=239 else 0 for i in range(0,len(zndist_full))]
zndist_3 = [zndist_full[i] if 239<i<=359 else 0 for i in range(0,len(zndist_full))]
zndist_4 = [zndist_full[i] if 359<i<=479 else 0 for i in range(0,len(zndist_full))]
zndist_5 = [zndist_full[i] if 479<i<=600 else 0 for i in range(0,len(zndist_full))]
#print(zndist_5)

#Five Number distribution bins converted back into arrays to use later:
zdistbin_1 = np.array(zndist_1)
zdistbin_2 = np.array(zndist_2)
zdistbin_3 = np.array(zndist_3)
zdistbin_4 = np.array(zndist_4)
zdistbin_5 = np.array(zndist_5)
# I think now the values are binned properly.
```

Snippet 6 Defined tracer with `has_shear = False` and no IA bias No Error is raised here.:
```python
lens_shiftbin_noshear1 = ccl.WeakLensingTracer(cosmo, dndz=(z,zdistbin_1), has_shear =False)
ell = np.arange(2, 2000) # represents modes we are looking at l= 2 to 2000 here.
```

Snippet 7 Here the Integration error is raised.
`CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error`

```python
cls_lens_shiftbin_noshear1 = ccl.angular_cl(cosmo, lens_shiftbin_noshear1, lens_shiftbin_noshear1, ell)
```
