### ISSUE TITLE
lookback time

### ISSUE THREAD

**Issue by nikosarcevic** [LSSTDESC/CCL#1146]
can we implement lookback time into pyccl? I realized I need it and really do not want to use astropy as my setup is ccl as much as I can

I will gladly write the code

**Comment by damonge** [comment]
That'd be great! Please go for it.

**Comment by nikosarcevic** [comment]
> That'd be great! Please go for it.

Hi, David
here is the working version (sorry, I am not well versed in c!! so what I have now I a py code)

def lookback_time(cosmo, a):
    """
    Method to compute the lookback time in Gyrs for a given scale factor or array of scale factors.
    See eq. 30 in Hogg 1999 https://arxiv.org/abs/astro-ph/9905116.
    """
    H0 = cosmo["h"] * 100  # Hubble constant in units of 1/Gyr BUT I think ccl has this built in
    hubble_time = 1 / H0  

    # Define the integrand as a lambda function directly using ccl.h_over_h0
    def integrand(z):
        a_at_z = 1 / (1 + z)
        return 1 / (ccl.h_over_h0(cosmo, a_at_z) * (1 + z))  # need to change ccl to self or c equivalent

    # Handle both single value and array input for 'a'
    if np.isscalar(a):
        z_max = 1 / a - 1
        z_values = np.linspace(0, z_max, num=1000)  # Adjust the number of steps as needed
        integrand_values = [integrand(z_val) for z_val in z_values]
        result = np.trapz(integrand_values, z_values)
        return result * hubble_time
    else:
        # For an array of 'a', compute lookback time for each value
        lookback_times = []
        for a_val in a:
            z_max = 1 / a_val - 1
            z_values = np.linspace(0, z_max, num=1000)  # Adjust the number of steps as needed
            integrand_values = [integrand(z_val) for z_val in z_values]
            result = np.trapz(integrand_values, z_values)
            lookback_times.append(result * hubble_time)
        return np.array(lookback_times)
        
        
        let me know if this helps 
       
       
       ps I also have py code for coming volume, I think it would be handy to have it in ccl. let me know if you want it

**Comment by hsinfan1996** [comment]
Is reviving PR #1066 an option?

**Comment by nikosarcevic** [comment]
> Is reviving PR #1066 an option?

Ah yes!! I did talk to Nick about it some time ago. If it still exists and it was done by Nick already then I would recommend to green lit it. I need the comiving volume and look back time for my code and I prefer to use ccl over astropy for look back time (because DESC= <3)

**Comment by hsinfan1996** [comment]
> > Is reviving PR #1066 an option?
> 
> Ah yes!! I did talk to Nick about it some time ago. If it still exists and it was done by Nick already then I would recommend to green lit it. I need the comiving volume and look back time for my code and I prefer to use ccl over astropy for look back time (because DESC= <3)

Do you want to create a new PR from the branch `distance_v3`? I think it requires merging master first. I can help you with that as well as creating a new PR.

**Comment by nikosarcevic** [comment]
> > > Is reviving PR #1066 an option?
> > 
> > 
> > Ah yes!! I did talk to Nick about it some time ago. If it still exists and it was done by Nick already then I would recommend to green lit it. I need the comiving volume and look back time for my code and I prefer to use ccl over astropy for look back time (because DESC= <3)
> 
> Do you want to create a new PR from the branch `distance_v3`? I think it requires merging master first. I can help you with that as well as creating a new PR.

oh yes please, if you can do it. im comfortable merging and working in cclx but here im a bit afraid ill break something 🥵
