### ISSUE TITLE
T CMB from CLASS

### ISSUE THREAD

**Issue by nikosarcevic** [LSSTDESC/CCL#1147]
https://github.com/LSSTDESC/CCL/blob/6a288ec8748f19b121e26391e6bafcbceefee9a9/src/ccl_core.c#L209

Should we use 2.725 or 2.7255? Noticed this now

**Comment by damonge** [comment]
I think that's a C-level remnant that doesn't really do anything:
```
>>> import pyccl as ccl
>>> cosmo = ccl.CosmologyVanillaLCDM()
>>> cosmo['T_CMB']
2.7255
```
