### ISSUE TITLE
Trispectrum docs have some small bugs

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#1153]
I found a couple of small bugs in the trispectrum docs. Here are the screenshots:
<img width="720" alt="Screenshot 2024-01-22 at 20 05 30" src="https://github.com/LSSTDESC/CCL/assets/9137015/0893fd3f-d42c-4f5f-bb4f-f37a920974b1">
<img width="728" alt="Screenshot 2024-01-22 at 20 05 24" src="https://github.com/LSSTDESC/CCL/assets/9137015/f92f00c9-ec4f-4045-a2a8-cf92cf2a0828">

**Comment by elisachisari** [comment]
Assigning to @carlosggarcia but feel free to pass it on if you are not the right person!

**Comment by damonge** [comment]
@elisachisari addressed in #1168. Happy to get a review (e.g. from you or @carlosggarcia )!

**Comment by damonge** [comment]
The docs can be seen here: https://ccl.readthedocs.io/en/doc_trispectrum_fix/api/pyccl.halos.pk_4pt.html
