### ISSUE TITLE
keras error with baccoemu unit tests

### ISSUE THREAD

**Issue by zdu863** [LSSTDESC/CCL#1171]
I'm getting the following error message, when running the unit tests via `pytest -vv pyccl`

``` filepath=/Users/zdu/anaconda3/envs/ccl-dev/lib/python3.11/site-packages/baccoemu/lpt_emulator_v2.0.0/lpt_emu_field0. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel a...```

The message appears for all tests for `pyccl/tests/test_bacco_lbias_power.py` and `pyccl/tests/test_baccoemu.py`. I'm suspecting this has to do with the compatibility of `baccoemu` and `Keras 3`. Any insight on this issue is appreciated!

**Comment by zdu863** [comment]
I was able to resolve this issue by downgrading `Keras` to `2.12.0` and `tensorflow` to `2.12.0`.

**Comment by matteozennaro** [comment]
Yes, unfortunately the latest keras suddenly discontinued support for loading models saved with the previous version standard. I'll update baccoemu to deal with this (still not sure what is the best strategy -- resave the models, move away from keras/tensorflow, create a docker...), but in the meantime I'll add a requirements for specific version of keras and TF in the baccoemu setup.
