### ISSUE TITLE
camb bbn module not always available

### ISSUE THREAD

**Issue by itrharrison** [LSSTDESC/CCL#1186]
I have managed to encounter a situation in which the line:

https://github.com/LSSTDESC/CCL/blob/dfa2b3b7be13afef0da11b5c4392e413af4e67eb/pyccl/boltzmann.py#L118

returns an error as the `camb.bbn` module is not directly available.

Confusingly (for me anyway), the `bbn` module is [listed in the camb docs,](https://camb.readthedocs.io/en/latest/bbn.html) but not in the camb `__init__.py` [here](https://github.com/cmbant/CAMB/blob/master/camb/__init__.py).

I have also been able to directly access `camb.bbn` at other times 🤷 .

Either way I note that `camb.model.bbn` is always available, so an easy fix would be to replace the above line with
```
cp.bbn_predictor = camb.model.bbn.get_predictor()
```

**Comment by itrharrison** [comment]
...okay, this also happens with `camb.constants` (with `camb.model.constants` being available). I will try and work out what has gone strange with the camb import I am using (from cobaya packages).

**Comment by damonge** [comment]
@itrharrison did you figure out if this is a general issue we should solve or just a result of your particular import system?

**Comment by damonge** [comment]
@itrharrison , I'll close this for now, but let me know if you think this is a general issue we should worry about.
