### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by elikrause** [LSSTDESC/CCL#119]
One key point of feedback during the collaboration meeting was that users would really like CCL to be public, so that code developed for DESC can be used for other projects as well (and vice versa). In general, the plan is to keep CCL as a separate library and develop the individual probe likelihoods in separate repositories, and releasing CCL does not need to not imply developing the complete cosmology likelihood in public.

Do you see reasons to keep CCL private? Or if not, what milestones do we want to accomplish before a public release?

**Comment by elisachisari** [comment]
The repository is now public. A new tag will soon be created once PRs #166 and #110 are merged.
