### ISSUE TITLE
scipy's Simpson integrator backend breaks after version 1.11 due to deprecation

### ISSUE THREAD

**Issue by James11222** [LSSTDESC/CCL#1200]
there were recently changes to the scipy library (>= 1.12). These changes include a modification to the Simpson integration method in the integration module of scipy. This effectively breaks the `pyccl.halos.HMCalculator` object since it relies on Simpson integration by default. As of scipy 1.14 the behavior of the 1.11 version is completely deprecated.

I found this new issue to only be true when using the `.integrate_over_massfunc()` method for the HMCalculator object with versions of scipy >= 1.12.

**Comment by damonge** [comment]
@James11222 I think we solved this here: https://github.com/LSSTDESC/CCL/pull/1187
Can I check if you're using the latest version of the code?

**Comment by damonge** [comment]
Will close for now, but do let me know if this is still an issue.
