### ISSUE TITLE
CCLError: CCL_ERROR_INTEG - Integration Error in ccl.angular_cl Function

### ISSUE THREAD

**Issue by nikosarcevic** [LSSTDESC/CCL#1201]
Hi, all
I encountered an error in ccl `__version__ 3.0.2` when running the `ccl.angular_cl` method to compute the clustering angular power spectrum without galaxy bias. The error message indicates an integration issue:
`CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error`

You can reproduce the error by just running this block ([taken from CCLX](https://github.com/LSSTDESC/CCLX/blob/master/CellsCorrelations.ipynb))
```
cosmo = ccl.Cosmology(Omega_c = 0.27, Omega_b = 0.045, h = 0.67, sigma8 = 0.83, n_s = 0.96)
z = np.linspace(0., 3., 512)
i_lim = 26. # Limiting i-band magnitude
z0 = 0.0417*i_lim - 0.744
Ngal = 46. * 100.31 * (i_lim - 25.) # Normalisation, galaxies/arcmin^2
pz = 1./(2.*z0) * (z / z0)**2. * np.exp(-z/z0) # Redshift distribution, p(z)
dNdz = Ngal * pz # Number density distribution
b = 1.5*np.ones(512) #Galaxy bias (constant with scale and z)

clu = ccl.NumberCountsTracer(cosmo, has_rsd=False, dndz=(z,dNdz), bias=(z,b))
clu_nobias = ccl.NumberCountsTracer(cosmo, has_rsd=False, dndz=(z,dNdz), bias=None)
ell = np.arange(2, 2000)

cls_clu = ccl.angular_cl(cosmo, clu, clu, ell) #Clustering
cls_clu_nob = ccl.angular_cl(cosmo, clu_nobias, clu_nobias, ell) #Clustering without bias

```

**Comment by nikosarcevic** [comment]
Ok, I got it -- you MUST specify something for constructing the tracer. For example, if no gbias then you have to at least have the rsd (or perhaps magbias?). This needs to be explicitly stated in the docstring. Can we do that, @damonge ?

**Comment by damonge** [comment]
@nikosarcevic this is actually fixed on master (see [here](https://github.com/LSSTDESC/CCL/blob/4b9cb93827249a50f26f7da5cc540fb251daf6e3/pyccl/tracers.py#L821))
