### ISSUE TITLE
FAST-PT Updated to V 3.2

### ISSUE THREAD

**Issue by dderienzo** [LSSTDESC/CCL#1205]
FAST-PT has updated to 3.2, no longer relying on deprecated scipy functions. It can be run with scipy 1.14.1. 

What needs to be updated in CCL's dependencies to note this? I saw the environment.yml makes an explicit note requiring an earlier version of scipy.

Let me know and I or others can change them.

Thanks!

**Comment by damonge** [comment]
@dderienzo this this correct? I just try running our tests with the latest scipy and it failed due to fast-pt using `trapz` (see [here](https://github.com/LSSTDESC/CCL/actions/runs/11751257380/job/32740958466?pr=1209)). Am I missing something?

**Comment by dderienzo** [comment]
@damonge I see what you are saying. Do you know if when it runs this unit test if it makes sure FAST-PT is up to date? Because this should be an issue of the FAST-PT that was available on PyPi until recently, and should be fixed now. I am not super familiar with how this GitHub action works, but when it installed environment packages, there is no mention of installing/updating FAST-PT.

**Comment by dderienzo** [comment]
I apologize I didn't initially understand how the unit test works. I see now it is setting up a conda environment using what is specified in the environment.yml. The current version of fast-pt on conda-forge is outdated, and we are working to put the correct version online. I will follow up when that is compelte.

I am still confused why when it sets up the environment dependencies there is no mention of fast-pt. Are you able to explain that to me? Thank you.

**Comment by damonge** [comment]
Thanks a lot.
I don't know enough about GHA's output, unfortunately.
Please do ping us here when FAST-PT is finally in conda.

**Comment by dderienzo** [comment]
@damonge FAST-PT is updated in conda-forge. Let me know if it works, and thank you for the help.

**Comment by damonge** [comment]
That's great. Thanks a lot @dderienzo !
There's a separate issue that one of our other dependencies (Dark Emulator) still uses old scipy, but that's a separate thing.
