### ISSUE TITLE
Support to python 3.x?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/CCL#133]
I was trying to install the libraries using anaconda python 3.5 and I had some trouble related to SWIG.

Is python 3.x supported (or are we planning to support it) or right now are we only supporting python 2.7?

Has someone installed the library using python 3.x?

**Comment by dkirkby** [comment]
I just tried commenting out the lines that check for python 3.x and the `python setup.py install` step works fine, but I get the following import error:
```
import pyccl
...
~/.local/lib/python3.6/site-packages/pyccl/__init__.py in <module>()
...
----> 2 import ccllib as lib
...
ModuleNotFoundError: No module named 'ccllib'
```
This is not obviously a py3-specific problem.  Any ideas?

**Comment by fjaviersanchez** [comment]
Try to run `python setup.py install` twice... Apparently this is a known issue in swig (see #168). I think we might have to rebuild the wrapper with a different swig version and that will solve the problem.
