### ISSUE TITLE
splines and thread safety

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#137]
Just realized, working on a different repo, that CCL is not thread safe due to the use of interpolation accelerators for splines. Different threads using the same ccl_cosmo will get into race conditions when updating the spline accelerators.

Not sure this is a major problem as long as it's documented, but thread safety was the main driver to make the error status a separate variable, so I just wanted to flag this.

An easy solution would be to drop all accelerators, but this could have an impact on performance.

**Comment by beckermr** [comment]
We decided to remove the accelerators and call it good. Closing.
