### ISSUE TITLE
generated configure script is included in github.

### ISSUE THREAD

**Issue by rainwoodman** [LSSTDESC/CCL#160]
I noticed the generated configure script is included in github.

The usual practice is not to include generated configure scripts on github.
autotools will automatically include these scripts in a release tarball.

I think people do provide an autogen.sh to preproduce the scripts after a checkout.

e.g. 

https://git.gnome.org/browse/gtk+/tree/autogen.sh

autotools also have a 'maintainer-mode' which may modify these generated files at times

The idea is that the 'developers' who obtain the source code on github shall have a development environment with autoconf automake etc properly installed. The distributed release tar files are `platform independent` (in the autotools sense).

I don't see a discussion about this on the issue tracker -- so I am starting one here.

**Comment by beckermr** [comment]
Closing this since we use cmake now.
