### ISSUE TITLE
Revisit cosmo->status_message.

### ISSUE THREAD

**Issue by rainwoodman** [LSSTDESC/CCL#163]
The original purpose of definding status as an int and keeping error context (status_message) in cosmo object was to avoid tedious manipulation of the error status in numerical code. However, so far all places where `cosmo->status_message` is used, it is assoicated with `*status=`.

(see this via. `grep -A 1 status_message`)

Thus it appears we still propagate status all the way down anyways.

I thus propose moving status_message and merge it with *status into a `ccl_error` struct. This can be done in a few steps.

1. `typedef int ccl_error`; replace all `int *status` with `ccl_error * status`.
2. add method `ccl_error_set_message(cosmology * ...), and deprecate the inconsistent use of sprintf/strcpy. 
3. typedef struct {ccl_error_code * status; char * message} ccl_error; find all `ccl_error_set_message`, replace with `ccl_error_raise(ccl_error_code * status, char * message)`;

**Comment by philbull** [comment]
Closing this issue as "won't fix" for now. We could possibly revisit this later, but the current setup is working OK, and subsequent changes to `master` have fixed some consistency issues.
