### ISSUE TITLE
Swig Python Wrapper Install Requiring Two Attempts

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/CCL#168]
When building the Python wrapper for people at this Hack Week, we came into the issue where it seemed like `python setup.py install` would need to be run multiple times for the libraries to get copied over to the python distribution. This was also the solution to get the Python installation to work for the Dockerfile in #166.

@hsnee Suspects that this may be a known issue with SWIG build order. http://stackoverflow.com/questions/17666018/using-distutils-where-swig-interface-file-is-in-src-folder has a suggestion that making a custom build class and forcing the use of it might be able to solve this.

However, I do not know if this is relevant given #151 and issues raised in #159. Thoughts are appreciated.

**Comment by elisachisari** [comment]
This issue requires travis integration. We have decided this is not crucial for public release, but we will keep working on this.

**Comment by elisachisari** [comment]
@fjaviersanchez Has this been addressed already and can it be closed?

**Comment by fjaviersanchez** [comment]
I think that this is solved automatically with the new `setup.py` and I never found this problem with it. However, it would be good if more people tried to reproduce this problem before closing the issue.

**Comment by philbull** [comment]
Let's close this issue now. We can reopen if it becomes a problem again.
