### ISSUE TITLE
Test distances to recombination

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/CCL#176]
Current checks tests distances to z=5. It would be good to extend this to z=1150 and cross-check against CLASS for cosmologies with neutrinos. These distances enter in CMB theta parameter which is constrained to 1e-4 and quite important so one would expect people to use CCL in this regime and expect high accuracy.

**Comment by c-d-leonard** [comment]
I did a cursory check of CCL vs CLASS at z about 1090 (taking a z for which background quantities were output by CLASS). I found that when calling ccl.background.comoving_angular_distance() at this z, the relative agreement with CLASS was only about 1e-3, so this needs work. This was for a cosmology with no massive neutrinos. To do this, I had to adjust A_SPLINE_MIN down to 0.0001.

**Comment by philbull** [comment]
Hi @c-d-leonard, any progress on this? Do you know of any sensible tests we can add?

**Comment by c-d-leonard** [comment]
I think that @damonge 's work on high-z may have solved this. We now have tests out to high z (ccl_test_distances_hiz.c for example). David is this solved?

**Comment by damonge** [comment]
It might, but we haven't checked explicitly that our chi(z_LSS) matches CLASS's/CAMB's numbers for the same set of parameters

**Comment by slosar** [comment]
Yes, let's do this -- this is the last thing I would like to see tested before I switch to CCL wholesale! :)

**Comment by tilmantroester** [comment]
I think with PR #374 (and #390 ) having been merged, this can now be closed.
