### ISSUE TITLE
zstar is initialized to nan

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#190]
I am seeing this in the Python notebook within the correlation branch. Not only sigma8 is nan here, but also zstar. We need to check whether this is a problem.

**Comment by c-d-leonard** [comment]
@elisachisari @damonge can we close this? Is it still a problem? (Also what is zstar?)

**Comment by c-d-leonard** [comment]
@elisachisari @damonge bumping again, do we still care about this?

**Comment by c-d-leonard** [comment]
I'm closing this; if anyone wants to re-open feel free.
