### ISSUE TITLE
Add a run of nonlinear/linear power in the checks

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#198]
Currently, `make check` runs on BBKS. I suggest making a run of, for example, sigma_8 by calling CLASS and checking that this does not crash. Some of our current bugs in master come from the fact that the checks never probe the calls to CLASS.

**Comment by philbull** [comment]
Should we begin separating unit tests from validation tests?

**Comment by philbull** [comment]
OK, see PR #340 for a partial solution. Quite a few combinations of transfer functions and matter power spectrum types cause segfaults! We also have a number if transfer function types (like 'camb') that aren't supported.

**Comment by elisachisari** [comment]
@philbull shall we close this?

**Comment by philbull** [comment]
Fixed in PR #340.
