### ISSUE TITLE
test class 2.6.0 for compatibiltity 

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#204]
We will eventually want to update the version of class. I've updated to class 2.6.0 on the branch update_class_version and tested that the checks pass, but we also want to try more aggressively to break any new features of class and find workarounds before incorporating this in master.

The "science" checks pass for make check (C) and run_tests.py (python), but for the C checks I'm getting a swig error I can't get rid of (I follow the directions about rerunning swig but the files to commit do not seem to have changed relative to remote). However, this probably has nothing to do with the version of class.

**Comment by elisachisari** [comment]
Let's check the difference between our current version and the newest one and see if we need to implement the new one.

**Comment by elisachisari** [comment]
@damonge @c-d-leonard Following the new CLASS installation, do we need to do anything else about this issue?

**Comment by c-d-leonard** [comment]
I think this is resolved by the new class installation procedure.

**Comment by philbull** [comment]
Closing this issue as resolved.
