### ISSUE TITLE
Redefine the N_K parameter per log10 bin

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#208]
The N_K parameter in the INI file is set to 1000. The minimum and maximum K for splines and integration is fixed as well by our convergence tests. There was a suggestion from @jablazek to re-define N_K such that it is defined per log10 bin so that changing the K range does not imply changing the resolution of the splines.

**Comment by tmcclintock** [comment]
This is addressed in #240. @wagoner47 make sure that you reference the issue(s) that you work on next time you do a PR so it's easy to cross-reference for the reviewers and anyone else that looks.
