### ISSUE TITLE
Consider using linear theory without neutrinos for wide z bins to get RSD in neutrino cosmologies.

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#209]
From a comment by @jablazek in the ccl note draft: "RSD should be pretty minimal for angular power spectra, at least with wide enough z bins. Why not use linear theory with no neutrinos in any case and just warn about potential loss of accuracy?". We should consider this possibility.

**Comment by damonge** [comment]
We're already doing this!
