### ISSUE TITLE
Add documentation for FFTLog

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#217]
The file fftlog.c is included in CCL for speeding up the computation of the correlation functions. It is currently a black box and needs documentation. 
Source: http://casa.colorado.edu/~ajsh/FFTLog/

**Comment by tmcclintock** [comment]
Would there ever be a need to make a python interface to this file or no? If so we might want to write it directly into @slosar 's FFTlog repo [here](https://github.com/slosar/FFTLog).

**Comment by slosar** [comment]
So note that CCL just has a copy of my repo, which is just two files stolen from another project, so no need to link back to my repo. If you can make interface exactly the same and juts changeable by a flag in CCL that would be great, as you could check speed and accuracy. So I'd just change FFTlog in CCL to be a wrapper to an abstract class that can do FFTlog-like calculations

**Comment by slosar** [comment]
No, I isolated it from copter by carlson (as clearly indicated in README).

**Comment by jablazek** [comment]
ah, yeah. sorry, i knew that.
