### ISSUE TITLE
Link CCL to FAST-PT

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#225]
We want to link to FAST-PT in order to get better nonlinear modeling on CCL. @jablazek

**Comment by xfangcosmo** [comment]
I'm going to write a CFASTPT, since I have already written a C version of fast covariance (double-Bessel) code to interface with CosmoLike. Please let me know whether that's helpful.

**Comment by damonge** [comment]
@jablazek and myself have plans to start working on this now

**Comment by jablazek** [comment]
Lots of progress, along with @damonge, @c-d-leonard, @elisachisari, and @rmjarvis.

`nonlin_bias` branch in CCL and CCLX repos have the new functionality. In particular, NonlinearBiasFASTPT.ipynb in CCLX. You need to be in the correct branch in both repos.

**Comment by jablazek** [comment]
As of now, the nonlinear biasing from FASTPT works. Nonlinear IA is next. Also, z-dependent bias parameters and the option to calculate PT at every z, instead of using the growth function.

**Comment by jablazek** [comment]
There is also a potential issue related to correlation functions. It matters whether the k->0 contribution is left in the power spectrum or subtracted (i.e. renormalizing the shape noise) due to numerical issues in the FT. This is worth examining.

**Comment by c-d-leonard** [comment]
HEY GUYS WE DID IT @jablazek @damonge , I'm closing this longstanding issue.
