### ISSUE TITLE
Upload CCL note to arxiv

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#228]
I am opening the discussion of whether and when to upload the note to the arxiv. What needs to be done before we upload?

**Comment by elisachisari** [comment]
Consider submitting to this journal:
https://www.journals.elsevier.com/astronomy-and-computing/

**Comment by damonge** [comment]
I think we should have a discussion of what functionality we would like to see in CCL when we make it globally public (as in advertising it on arXiv) vs. when do we want this to happen. For instance I'd like to see:
 - Non-limber power spectra
 - CMB lensing
 - A more complete halo model module
 - Faster correlation functions?

Maybe we could set up a deadline for when we want the arXiv thing to happen, and try to implement as many of these things as we can until then.

Also, AAS has a relatively new policy on software papers that might be interesting:
http://journals.aas.org/policy/software.html

**Comment by drphilmarshall** [comment]
I was just about to say, what if we hit `make apj` and submitted it to AJ?
I had a very good experience with AJ last fall, they are pretty receptive
to "software papers" these days. @sethdigel what's the Pub Board guidance
for submitting Notes to the arxiv?

In any case, you should get a DOI when you have the made the release
(including the Note) - that makes the software and Note citeable. GitHub
enables this through zenodo, see the blog post [here](
https://guides.github.com/activities/citable-code/).

One more thing: now that the repo is public, we can get travis to
continuously build the PDF of the note and check it into an orphan PDF
branch (thus avoiding repo bloat). Someone should issue me with that task.

**Comment by sethdigel** [comment]
The DESC Publication Policy defines software as a publication but does not define the process by which it can be released.  The policy does seem to assume that software would be released only when its associated journal paper is released (accepted for publication and posted on the arXiv).  It does say that DESC Notes associated with a journal paper can be released when the associated paper becomes publicly available.  Regarding the latter, the intent is that the Notes would be released if they provide useful supporting information, and not generally as stand-alone documents. 

In my opinion, DESC has more work to do in defining standards for releasing software; this is in no way a comment on CCL or a statement that releasing it has violated some policy, but as a collaboration we need some articulated process.  

I would strongly encourage the authors to convert their DESC Note to a journal paper, though.  This has some overhead, of course, including internal review, but it is the sense of the Pub Board that associated journal papers have increased the adoption and impact of other codes in the field, and internal review ensures that DESC releases excellent papers.

**Comment by elisachisari** [comment]
thanks @sethdigel! We plan to start working on the paper. Can you clarify the process/timescales from the Pub Policy? As far as I understand, we need to: 1) announce the paper (do we need to have a draft for this or should we do it now?), 2) go through review within TJP (suggested timescale?), 3) go through committee review (is there a timescale?), 4) go through collaboration-wide review (2 weeks). 

![screen shot 2017-07-14 at 2 27 31 pm](https://user-images.githubusercontent.com/9137015/28214092-d1b52ce6-68a0-11e7-8d0f-fb7c064dc1a3.png)

**Comment by sethdigel** [comment]
@elisachisari, sorry to have somehow missed your response until now.  

> Can you clarify the process/timescales from the Pub Policy? As far as I understand, we need to: 1) announce the paper (do we need to have a draft for this or should we do it now?), 2) go through review within TJP (suggested timescale?), 3) go through committee review (is there a timescale?), 4) go through collaboration-wide review (2 weeks).

1) The Publication Policy defines the research work of the collaboration as being organized into Projects that have one or more associated publications.  The latter are defined quite broadly, including software, journal papers, and associated DESC notes.  The idea is that Projects are proposed ('Announced') to the relevant working groups early on, and then publications are defined within the projects as appropriate.  The leads of the relevant WGs formally approve the project, and part of announcing the project is to give the opportunity for interested DESC members to register their interest in contributing.  Regarding this step of the procedure I think that you can consider CCL to effectively have been proposed, accepted, and announced.
2) There's no suggested time scale for internal review within the relevant working group; the Pub Policy basically says that the WG leads should request a review committee to be formed no later than when a draft paper has converged enough to be ready for a committee 
3) The concept in the Pub Policy is that for journal papers in Projects, the internal review committee may be appointed as soon as you have analysis results and 'supporting documentation' but not necessarily a draft paper.  So far we have not managed that yet.  The committee is defined to have three members and is appointed by the Pub Board, who wants recommendations from the WG leads and primary authors.  The idea is that the committee should get involved early, like reviewing analyses.  The Pub Policy says that review committees have to provide feedback within two weeks.  This means per iteration, and it should be considered on a best-effort basis.
4) The collaboration-wide review period happens after the review committee is happy with the paper and it is considered to be in 'nearly final form'.  This period is defined to be two weeks.  After this period the Pub Manager signs off on submitting and posting the paper.

In the Pub Board we have been discussing the case raised here of potentially posting a DESC note to the arXiv without an associated journal publication, to document and advertise a software package that DESC has released.  This falls into a gap in the Pub Policy so we want to proceed carefully, but we do not see it as being ruled out by the Pub Policy.  If you would like to pursue this we can come up with specific advice about the level of internal review (short of a review committee) and other considerations.  It is still the sense of the Pub Board that a journal paper likely would have greater impact and potentially increase adoption of the code but we recognize that there will be cases when releasing only a DESC note is desirable and that there should be a defined way to do that.

**Comment by elisachisari** [comment]
This is a list of what remains to be done for CCL paper submission.

From the point of view of code development
- [ ] Merge the cosmic emulator 
- [ ] Merge angpow @jeremyneveu 
- [ ] Get a CMB lensing benchmark then merge @sukhdeep1989 @damonge 
- [ ] Test accuracy of splines, merge after checks 
- [ ] Develop multiple neutrino mass branch, check & merge @c-d-leonard 
- [ ] Decide on CLASS dependency and licensing @damonge @elikrause 
- [ ] Tidy up and additional tests @philbull 

Specific issues to this milestone are here:
https://github.com/LSSTDESC/CCL/milestone/2

From the paper point of view
- [ ] Update paper according to the code development above
- [ ] Fill out remaining sections (intro @mishakb, outlook @damonge @elikrause, validation @philbull)
- [ ] Identify potential DESC reviewers

Please add to this list if anything is missing.
