### ISSUE TITLE
Update the github wiki

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#229]
The github wiki is out of date. We should update it now that the repository is public.

**Comment by elisachisari** [comment]
Made general updates. The only page that is still out-dated is 
https://github.com/LSSTDESC/CCL/wiki/Basic--usage
@vrastil, do you think you could take a look at that one?

**Comment by vrastil** [comment]
I`ll get to it on Monday

**Comment by elisachisari** [comment]
Recently updated to include:
- new CLASS installation
- license details
- code updates following implementation of baryons
