### ISSUE TITLE
Serializing ccl_cosmology structs

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/CCL#230]
For several uses (I'm thinking of a cosmosis interface and results saving results for later for making plots) it would be useful to be able to serialize a ccl_cosmology struct (save it to disc or to another form) and deserialize it (load from disc or somewhere else).

I think the first step in a way to do this would be to do this by writing two functions:
```
int ccl_cosmology_serialize(
    ccl_cosmology * cosmo,
    int (*serialize_double)(double, int, void*),
    int (*serialize_int)(int, int, void*),
    int (*serialize_double_array)(int, int, double*, void*),
);

int ccl_cosmology_deserialize(
    ccl_cosmology * cosmo,
    int (*deserialize_double)(double*, int*, void*),
    int (*deserialize_int)(int*, int*, void*),
    int (*deserialize_double_array)(int *, double**, int*, void*),
);
```
where the user would supply functions that (de)serialize individual types which took the value, a tag of what kind of value it is, and a context pointer.  Then we could support multiple ways of serializing.

Does this seem sensible?  Any thoughts?

**Comment by philbull** [comment]
This seems a little complicated, but perhaps I'm not properly understanding how it would be used. Can you provide a bit of example code showing how you would use these functions?

**Comment by joezuntz** [comment]
Okay, so let's say that User "Tim" wants to save things to flat text files with no headers.

```
int serialize_double_text(double value, int tag, void* context){
    FILE * f = (FILE*) context;
    fprintf(f, "%d  %e\n", tag, value);
}
```
and similar functions.  We could supply a few example serialize_* functions 

Then we would call:
```
ccl_cosmology_serialize(
    my_cosmo,
    serialize_double_text,
    serialize_int_text,
    serialize_double_array_text,
);
```
This structure separates the part of the code that knows what's *in* the ccl_cosmology struct from the part that knows how to save things to disc. So we could write several sets of serialize_* functions, without worrying that we have to update them all every time something changes in the ccl_cosmology struct.

The only thing I'm not sure about is the second argument (an int), which I envisaged as an identifying tag, so that formats like yaml that might want to save things as a dictionary could identify what they are saving by name somehow. Maybe it should be a string instead? Or several strings?

**Comment by philbull** [comment]
After speaking to @joezuntz about this in person, it sounds like he already has some working infrastructure for this inside Cosmosis. It provides a standard data structure for interchanging tables etc. between different parts of a pipeline.

**Comment by beckermr** [comment]
Code for this has been merged and is working. I am closing this issue. Feel free to reopen if needed!
