### ISSUE TITLE
Formulate a policy for external dependencies

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#239]
CCL is growing rapidly to include new external codes. We have varying levels of control over these codes, especially in terms of:
- The programming language used and their own external dependencies
- The level of testing and accuracy validation of the code
- Fixing bugs, adding features, and other issues surrounding keeping the external code up to date
- The level of documentation and performance optimisation

Some examples of questions that we should be able to answer are:
1. What do we do if an external dependency depends on (e.g.) a different FFT library to the one we are using? What if the dependency doesn't run on some systems (e.g. Macs)?
2. What should we do if the dependency has license restrictions that means it can't be distributed with CCL? How do we deal with citation clauses in licenses of the external codes?
3. What should we do if the dependency is written in a different programming language? Should we re-write Python codes so that they are more easily available to the C library?
4. Should some of the codes be hard dependencies, while others are optional? How do we decide which to choose?
5. If we heavily depend on a code (e.g. CLASS), should we fix bugs in our own local version of the code? Or should we work around them in the CCL code only? Or should we try to get them fixed upstream?
6. What standards should we apply to these codes in terms of the levels of validation and documentation?

**Comment by philbull** [comment]
Also, should we keep a 'roadmap' document spelling out which codes we are planning to integrate with CCL in the future? And should we have a formal process (with a set of 'minimum standards') for people who want to propose their code for integration within CCL?

**Comment by brianv0** [comment]
For (1) and sort of (5), If it's a C library, @jchiang87 or or @rmjarvis should help out a bit with figuring out a build dependency system (CMake, Spack, or similar) and/or a packaged build system. Including too many dependencies is going bring up this issue over time.  Alternatively, we only use versions of libraries packaged with brew (os x), apt/yum, (and/or package them) or switch to Conda. If you want to keep using PyPI, I think it's best to go the brew/apt/yum route. This also helps with (2) - you aren't distributing those libraries.

For (3), everything is either going to be C, C++, Fortran, or Python. Those are all reasonably interoperable (nobody uses Fortran directly). It's not very practical to use anything other than that (technically Rust and Julia might still work fine, R is more of an issue).

(4) is still wrapped up in the decision for (1) and (2)

For (5), bugs should definitely be fixed locally (ideally via a fork of CLASS in LSSTDESC) which is maintained and PRs it's easiest to handle that if you actually. Again, this leads back to (1) to an extent

Alternatively, make sure every external library is either available in brew (or package it in brew) and/or apt/yum, depending.

For (6), this is again a question for @rmjarvis and @jchiang87, but for C we probably should be using Clang-format and for Python we should probably adopt a style checker based on PEP-8 (with reasonable exceptions when necessary). It's relatively easy to configure both of those. For external libraries which are imported/patched (e.g. CLASS), you should always try to code consistently with the explicit or inferred style of that library.

**Comment by brianv0** [comment]
I left something out: if there's not too many dependencies, the current behavior is fine and a packaging system is probably overkill for (1), but we should have a complexity line-in-the-sand that, if it's crossed, another solution should be considered.

**Comment by rmjarvis** [comment]
> For (1) and sort of (5), If it's a C library, @jchiang87 or or @rmjarvis should help out a bit with figuring out a build dependency system (CMake, Spack, or similar) and/or a packaged build system.

I think the main bit of advice I have about this is to do your best to keep your core dependencies to a minimum.  Especially dependencies that are not pip installable.  

It's usually ok to have sub-modules that have additional dependencies, so only people who want to use the features in these sub-moduels have to worry about these extra dependencies.  E.g. in GalSim, we have an lsst module that depends on the LSSTDM stack, but the main GalSim code does not depend on it.

But I would try to keep the core dependencies to be both few in number and as light-weight as possible in terms of pain of installation.

**Comment by c-d-leonard** [comment]
@philbull is this still something we are concerned about? Things have changed wrt install / dependencies a lot since this issue has been touched. @beckermr any thoughts?

**Comment by beckermr** [comment]
I think as long as the deps are easily installed or optional, we should not worry too much and simply use common sense. I think we can close this.
