### ISSUE TITLE
Implement some useful presets (Planck15, etc)

### ISSUE THREAD

**Issue by dkirkby** [LSSTDESC/CCL#243]
These should probably be singleton instances of ccl.Parameters.  Design questions:
- Could these be implemented in the python layer only? (easier to implement and maintain).
- How do we support the typical use case where to you want Planck15 with one or two parameters changed?  Currently a Parameters instance is immutable so this isn't easy.
- Which presets do we want?  For reference, astropy's equivalent is documented [here](http://docs.astropy.org/en/stable/cosmology/#built-in-cosmologies).

**Comment by beckermr** [comment]
I think we decided to keep a single LCDM preset and then punt on the rest due to maintenance. Closing this issue. Feel free to reopen!
