### ISSUE TITLE
Check not needed in ccl_power.c?

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#249]
In ccl_power.c, there is a check for the value of kmin as follows:
![screen shot 2017-09-06 at 18 33 16](https://user-images.githubusercontent.com/9137015/30125896-e8d83a56-9331-11e7-9d7b-09b3e98171b2.png)

Since kmin is set above this check to 2*exp(sp.ln_k[0]), I think this check is currently not doing anything.

**Comment by beckermr** [comment]
fixed IIRC
