### ISSUE TITLE
Make CCL exit gracefully if parameters are outside Halofit valid ranges

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#252]
We should make sure that CCL exits gracefully if the parameters passed are outside those allowed by Halofit. What are those ranges? And does CLASS do this automatically? @damonge @elikrause

**Comment by jablazek** [comment]
Can we do better than this (eventually)? the z=10 limit is set by halofit, right? Could we just default to the linear P(k) at higher z? (Or something similar)

**Comment by elisachisari** [comment]
Yes, we plan on extending the redshift range. I think the z<10 limit is self-imposed because this is where we've checked the accuracy of the splines. But perhaps HaloFit has additional restrictions.

**Comment by damonge** [comment]
Unsure if this issue was initially triggered to deal with the z_max=9 problem or to deal with cosmological parameters being passed to CLASS outside its allowed range.

In any case, the z_max issue is fixed in PR #255 , so that should be merged soon.

**Comment by elisachisari** [comment]
This referred to cosmological parameters and redshift. There was also issue #272, which suggested generalising this to making sure we are within the allowed range of parameters for CLASS (not just Halofit).

**Comment by damonge** [comment]
Since @beckermr implemented our own homegrown version of halofit, I think this should be fixed now.

**Comment by beckermr** [comment]
Someone should test but yeah the range should hopefully be less restrictive now.

**Comment by c-d-leonard** [comment]
I am assigning myself to test this.

**Comment by aferte** [comment]
Hi, did some checks with Danielle during a sprint at the DESC meeting: halofit is now running fine even for redshift of 30 and for extreme values of Ω_c and sigma8.

**Comment by c-d-leonard** [comment]
I think we can go ahead and close this issue, thank you @aferte!
