### ISSUE TITLE
background a sampling

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#256]
Currently the sampling scheme for the background splines is very suboptimal for high-redshift quantities. We should figure out something that samples high redshift and low redshift quantities sufficiently well simultaneously

**Comment by damonge** [comment]
The same is true for the a-sampling of the power spectrum (although here the problem may be less relevant)

**Comment by beckermr** [comment]
@damonge Was this addressed in #255? If yes, let's close this issue.

**Comment by c-d-leonard** [comment]
@damonge still an issue?

**Comment by damonge** [comment]
Close it!
