### ISSUE TITLE
Memory leak while performing MCMC

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/CCL#257]
While running the MCMC tutorial @WeikangLin and I found that after a while the kernel dies. I think that this might be due to be running out of memory at NERSC (where the resources are shared and maybe there's not that much memory available at "rush hour"). However, it is fishy that it runs out of memory with only 2 parameters and 10 walkers * 100 iterations. I tried it with fewer walkers and it still dies so, this probably means that the splines or CLASS aren't properly freeing the allocated memory. I have to say that I haven't done a proper profiling but I had trouble with the memory allocated by the splines before...

Any thoughts? @philbull @damonge @elisachisari

**Comment by damonge** [comment]
we've been discussing adding a script that runs valgrind on CCL, and this will pick up these leaks, so hopefully we can sort this out soon.

**Comment by tmcclintock** [comment]
@fjaviersanchez can you DM me the code you ran on slack? The thing I really need to get at is the kernel, or likelihood function.

My plan is to design a script w/ valgrind that looks like the tutorial on the CCL main page but substituted in with the functions you called.

**Comment by elikrause** [comment]
@fjaviersanchez Would you be able to test whether the leak disappears if you use BBKS instead of CLASS?

**Comment by fjaviersanchez** [comment]
Yes, when we ran `bbks` it worked with no problem!

**Comment by elikrause** [comment]
Fixed in PR #268 , which was merged into master.
