### ISSUE TITLE
Revisit accuracy of splines and extrapolation

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#258]
This refers to the spline for the total matter power spectrum. We need to check accuracy of the splines and extrapolation scheme for the linear and nonlinear matter power spectrum and document this in the note and paper. We are currently seeing some problems achieving the desired 1e-4 level for the CLASS power spectra.

**Comment by tmcclintock** [comment]
Just so I understand, who desires the 1e-4 precision? Is that the precision that CLASS is gauranteed to? Is that some kind of DESC requirement?

**Comment by villarrealas** [comment]
The 1e-4 precision was our target for numerical accuracy for CLASS as a whole. I don't think we're worried about CLASS being accurate to 1e-4, but we want to match CLASS to that level. Currently the splines have some issues with that.

**Comment by elisachisari** [comment]
Addressed by @christianel in #319. Documented in note and paper.
