### ISSUE TITLE
add support for accepting Omega_nu for massive neutrinos 

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#261]
It would be useful, especially for validation of the cosmicemu power spectrum calculations, to be able to accept either m_nu (as currently) or Omega_nu for massive neutrinos.

**Comment by elikrause** [comment]
ccl_neutrinos.c:Omeganuh2_to_Mnu() implements this through root finding of ccl_neutrinos.c:Omeganuh2(); it is available in the cosmicemu branch (commit 4cf0981 )
Currently this is only implemented in the C layer.
