### ISSUE TITLE
Extend basic cosmology functions to higher redshifts?

### ISSUE THREAD

**Issue by anguta** [LSSTDESC/CCL#265]
Many of the low order cosmology functions throw errors above a redshift of ~>9 (e.g. h_over_h0, luminosity_distance, linear_matter_power) . 

This behavior makes sense when calculating quantities which have not been verified at high redshifts but it would be nice if 0th/1st order utility functions (like distances and linear matter power spectrum) could function at higher redshift.

**Comment by elisachisari** [comment]
@anguta Thanks for the feedback! This is being developed in one of the current PRs, so we will soon have capability for this.

**Comment by tmcclintock** [comment]
@elisachisari which PR?

**Comment by elisachisari** [comment]
That would be the CMB lensing PR: https://github.com/LSSTDESC/CCL/pull/255

**Comment by elisachisari** [comment]
PR #255 has been merged so I'm closing this issue.
