### ISSUE TITLE
Distutils screws up rpath on some systems

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#270]
The `setup.py` script passes a `runtime_library_dirs` kwarg to the distutils `setup()` function. This is supposed to setup the CCL library so that it knows where other libraries that it depends on have been installed, without those libraries necessarily being in the user's library path (a feature called 'rpath').

I just tried to install CCL on a system where distutils is doing the wrong thing with this argument. The value of the kwarg is generally passed to the compiler using the `-R` switch (which is then passed to the linker). This switch doesn't seem to be present on some systems though. I don't know why.

A possible remedy is to explicitly specify the rpath argument. To do this, we would comment out the following line:
    `runtime_library_dirs=[libdir],`
and modify the line below it to read:
    `extra_compile_args=['-O4', '-std=c99', "-Wl,-rpath=%s"%libdir],`

GCC version: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
python: Python 2.7.13 :: Anaconda, Inc.
uname -a
Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by fjaviersanchez** [comment]
I am adding setuptools as part of the solution of #269. Maybe it helps in this case too?

**Comment by fjaviersanchez** [comment]
@philbull did you find the error while installing or at runtime?

**Comment by elisachisari** [comment]
@EiffL can we close this following the new installation?

**Comment by EiffL** [comment]
I think we should be ok now, cmake should handle all of this, but I have to admit I'm not 100% sure why the problem happened in the first place...

**Comment by beckermr** [comment]
I am closing this issue since it appears we are not too worried anymore. Feel free to reopen if desired!
