### ISSUE TITLE
CCL linking fails with FFTW v3.3.6-pl2

### ISSUE THREAD

**Issue by j-dr** [LSSTDESC/CCL#271]
Installing CCL using 

python setup.py install --user

with FFTW 3.3.6-pl2 (the second to latest version of fftw) results in the following error:

/usr/bin/ld: /u/ki/jderose/.local/src/fftw-3.3.6-pl2/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/u/ki/jderose/.local/src/fftw-3.3.6-pl2/lib/libfftw3.a: could not read symbols: Bad value

I'm not sure if this is a machine specific issue, but I thought I would point it out since I spent a couple hours trying to get around it (ended up just using FFTW 3.3.4 which works).

**Comment by tmcclintock** [comment]
Did you try to compile the C code first?

**Comment by j-dr** [comment]
Nope. I would guess that wouldn't help since it seems to be a linking issue in the compilation of the C code though.

**Comment by rmandelb** [comment]
A few people had this issue with FFTW as a GalSim dependency (exact same error message).  See discussion and suggested solution here: https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ#why-does-scons-report-some-error-about-a-bad-value-and-recompile-with--fpic

**Comment by j-dr** [comment]
I recompiled FFTW with the --with-pic flag and still had the same issue. Maybe there's something else that I needed to do to make it a shared library though.

**Comment by rmandelb** [comment]
Well, my understanding was that `-fPIC` does *not* make a shared library; rather it makes a static one that has some set of objects included that otherwise would not be.  And if it isn't working, then you need to do something else in order to get a shared library. I think `--enable-shared` should do the trick; have you tried that?

**Comment by rmandelb** [comment]
Actually, stackoverflow [says](https://stackoverflow.com/questions/45321342/how-to-build-fftw-in-ubuntu) you should do both, i.e.
```
./configure --enable-shared
sudo make CFLAGS=-fPIC
sudo make install
```

**Comment by j-dr** [comment]
Yep, that appears to have worked. Thanks!

**Comment by zdu863** [comment]
I had exactly the same issue, but this isn't working for me. I'm still getting the same error message.

**Comment by zdu863** [comment]
$ make CFLAGS=-fPIC
make  all-recursive
make[1]: Entering directory '/home/zdu/Documents/CCL-master'
Making all in include
make[2]: Entering directory '/home/zdu/Documents/CCL-master/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/zdu/Documents/CCL-master/include'
Making all in class
make[2]: Entering directory '/home/zdu/Documents/CCL-master/class'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/zdu/Documents/CCL-master/class'
make[2]: Entering directory '/home/zdu/Documents/CCL-master'
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -fPIC   -o libccl.la -rpath /usr/local/lib src/libccl_la-ccl_background.lo src/libccl_la-ccl_core.lo src/libccl_la-ccl_error.lo src/libccl_la-ccl_lsst_specs.lo src/libccl_la-ccl_placeholder.lo src/libccl_la-ccl_power.lo src/libccl_la-ccl_utils.lo src/libccl_la-ccl_cls.lo src/libccl_la-ccl_massfunc.lo src/libccl_la-ccl_neutrinos.lo src/libccl_la-ccl_correlation.lo src/libccl_la-fftlog.lo class/libclass.la -lfftw3 -lgsl -lgslcblas -lm 
libtool: link: gcc -shared  -fPIC -DPIC  src/.libs/libccl_la-ccl_background.o src/.libs/libccl_la-ccl_core.o src/.libs/libccl_la-ccl_error.o src/.libs/libccl_la-ccl_lsst_specs.o src/.libs/libccl_la-ccl_placeholder.o src/.libs/libccl_la-ccl_power.o src/.libs/libccl_la-ccl_utils.o src/.libs/libccl_la-ccl_cls.o src/.libs/libccl_la-ccl_massfunc.o src/.libs/libccl_la-ccl_neutrinos.o src/.libs/libccl_la-ccl_correlation.o src/.libs/libccl_la-fftlog.o  -Wl,--whole-archive class/.libs/libclass.a -Wl,--no-whole-archive  -lfftw3 -lgsl -lgslcblas -lm    -Wl,-soname -Wl,libccl.so.0 -o .libs/libccl.so.0.0.0
/usr/bin/ld: //usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:567: recipe for target 'libccl.la' failed
make[2]: *** [libccl.la] Error 1
make[2]: Leaving directory '/home/zdu/Documents/CCL-master'
Makefile:961: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/zdu/Documents/CCL-master'
Makefile:448: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rmandelb** [comment]
@zdu863 - Sorry if I have misunderstood your comment, but it appears you
are trying to recompile CCL with that flag, which is not what is needed to
fix the problem.  Rather, you need to rebuild the FFTW library itself
(using the recipe I copied from stackoverflow) and then compile CCL
normally (no extra flag needed).
