### ISSUE TITLE
Segfault from calling mass function depending cosmology - CLASS errors not propagating correctly

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#272]
In the following three examples to calling ```ccl.massfunc()```, depending on how the ```ccl.Cosmology()``` object was created, there is a seg fault.

```python
import pyccl as ccl

params = ccl.Parameters(Omega_c=0.27, Omega_b=0.045, h=0.67, A_s=1e-10, n_s=0.96)
cosmo = ccl.Cosmology(params)
print ccl.massfunc(cosmo, [10**13], 1)

cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, A_s=1e-10, n_s=0.96)
print ccl.massfunc(cosmo, [10**13], 1)

params = ccl.Parameters(Omega_c=0.286-0.045, Omega_b=0.045, h=1.0, n_s=0.96, sigma8=0.82)
cosmo = ccl.Cosmology(params)
print ccl.massfunc(cosmo, [10**13], 1) #this call segfaults

cosmo = ccl.Cosmology(Omega_c=0.286-0.045, Omega_b=0.045, h=1.0, n_s=0.96, sigma8=0.82)
print ccl.massfunc(cosmo, [10**13], 1) #this call also segfaults
```

The top two calls are successful. The bottom two calls segfault (you can get to the last one by commenting out the third). I *think* it's because we use ```A_s``` in the first two and ```sigma_8``` in the second two. How can we fix this?

@j-dr found this while trying to use the mass function.

**Comment by damonge** [comment]
Actually the problem here is h: this leads to a value of Omega_b*h^2 that is too large for CLASS to handle. This is still a bug, since we should handle CLASS's crashing more gracefully than a segfault.

**Comment by damonge** [comment]
OK, this is a symptom of a much deeper problem, which is catching CLASS errors and propagating them all the way to python. This problem would have popped up in any other scenario, not just the mass function. I'm gonna tag @philbull here and will get back to this later on.

**Comment by tmcclintock** [comment]
Gotcha. I'm going to edit the title of the issue then.

**Comment by elisachisari** [comment]
This is actually already in issue #252, so it will be addressed there.

**Comment by damonge** [comment]
@elisachisari is that true? #252 has to do with Halofit (at least the title seems to imply that), rather than the parameters being passed to CLASS - in fact this issue has nothing to do with Halofit

**Comment by elisachisari** [comment]
I think we had intended for #252 to be more general than Halofit. I can clarify that there.
