### ISSUE TITLE
Revise nomenclature for correlation functions

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#275]
The ```correlation()``` function in [correlation.py](https://github.com/LSSTDESC/CCL/blob/master/pyccl/correlation.py) is actually only for projected correlation functions. This is confusing since it is not distinguishable from the (not yet implemented) 3d correlation function.

**Comment by beckermr** [comment]
Where do we live on this @tmcclintock? We have 3d correlations as `correlation_3d`. Are we cool with this?

**Comment by tmcclintock** [comment]
I guess I'm fine with how this is now.

Thinking ahead though, folks will want functions with names such as `halo_matter_correlation`, `halo_halo_correlation`, `galaxy_matter_correlation`, etc. all in both 2D and 3D. It's up to us to decide the standard naming convention. My preference would be for 3D things to have names such as `xi_hm` or `xi_gm`, and 2D things to be `w_hm`, etc., rather than appending `_3D` on to everything and spelling out the tracers fully.

**Comment by c-d-leonard** [comment]
@tmcclintock is this still something of concern for you or should we close this issue?

**Comment by damonge** [comment]
I think we don't to be naming correlations by the two specific physical quantities we correlate, but rather by what they are geometrically (i.e. 2D objects, which spins etc.). In that sense we could rename the current `correlation` to `correlation_2D`, but I'm not sure the pain of breaking the API warrants it...

**Comment by c-d-leonard** [comment]
I'm closing this.
