### ISSUE TITLE
Add support for accepting more keyword arguments (like Omega_m) in pyccl.Parameters

### ISSUE THREAD

**Issue by cosmicshear** [LSSTDESC/CCL#279]
This is how we set the cosmological parameters

`p = pyccl.Parameters(Omega_c=0.27, Omega_b=0.045, h=0.67, n_s=0.96, sigma8=0.83) `

but it doesn’t allow the user to use Omega_m as an input and says: 

`TypeError: __init__() got an unexpected keyword argument 'Omega_m' `

It exists in ccl_parameters Struct, though. One can use

`p.parameters.Omega_m`

to get the value for Omega_m, but it would be nice if the python wrapper can directly support this since many users care about Omega_m in particular.

**Comment by yymao** [comment]
Piggybacking on this issue --- Motivated by https://github.com/LSSTDESC/gcr-catalogs/issues/44, there were some discussion during the ANL Sprint Week about a cross-package implementation of a Python class for DESC to record Cosmology Parameter.  The idea is to have very light-weight class that only *store* these parameters using standardized labels for these parameters, and also allow storage of yet-to-be-defined parameters for potential future use. 

I made an attempt on this (see [this module](https://github.com/LSSTDESC/gcr-catalogs/blob/add-cosmology-parameters/GCRCatalogs/cosmology.py)). It uses the same labels as pyCCL but it does not support additional parameters (so it's not ideal). Then I feel that maybe CCL would be a better lead on this task. 

Any thoughts and plans? 

(cc people who have participated in this discussion: @philbull @jablazek @c-d-leonard @joezuntz @rmjarvis @elisachisari)

**Comment by beckermr** [comment]
We have deprecated the Parameters class. Support for Omega_m has not been added and realistically any transfer function computation will need Omega_b. I did add support for setting Omega_g.

I think given all of this we should close this issue. 

Thoughts @yymao @philbull @cosmicshear ?

**Comment by yymao** [comment]
I think having a syntax candy to allow setting `Omega_b` and `Omega_m` (instead of `Omega_b` and `Omega_c`) is nice. But maybe the discussion should be move to https://github.com/philbull/cosmoparams. As I mentioned above, I was hoping CCL and all other DESC packages will share a common lightweight cosmological parameter package.

**Comment by beckermr** [comment]
I'd rather just leave the parametrization here as is and deprecate yet another repo. CCL is the core tool, the cosmology objects now pickle, and they can be serialized into yaml. The installation issues are solvable.

**Comment by beckermr** [comment]
Unless we have more comments here I am going to close this issue. Feel free to reopen!
