### ISSUE TITLE
Add conventional IA model bias with the usual normalization

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#280]
This is a reminder for myself and @jablazek that when possible, we should add a b_I(z) function in CCL for the fiducial NLA model with the usual normalisation convention. See discussion in https://github.com/LSSTDESC/WLPipe/issues/26

**Comment by damonge** [comment]
For clarification: the way this is implemented in CCL is as follows (I'm quoting from https://arxiv.org/pdf/1506.02671.pdf, eqs. 4.14, 5.2):

1. In the large-ell limit, the IA kernel is basically proportional to W_IA = p_red*b_I, where p_red(z) is the redshift distribution of the galaxy population that aligns, and b_I(z) is some alignment bias function.
2. Writing p_red(z) = p_tot(z)*f_red(z), where f_red is the "red" fraction, this is just W_IA = p_tot(z)*f_red(z)*b_I(z). Currently users need to pass both b_I and f_red to CCL (as was initially suggested by @elisachisari and @jablazek).
3. According to Eq. 5.2 of the paper above, b_I can be related to the more common A_I as: b_I = -A_IOmega_MC_1*rho_crit/D(z)

If you confirm that this is really the parametrization that you want I could easily implement the modification in the code.

**Comment by EiffL** [comment]
@elisachisari @jablazek Quick question, there are 2 options:
  - Replacing the current implementation so that everywhere in the code b_I(z) gets replaced by A_I(z), thus changing the API, in particular the input parameters of `ccl_cl_tracer_new`
  - Give the user the option of providing b_I(z) or A_I(z) (for instance at the level of the python interface), then convert internally everything to b_I(z), thus preserving the current internal implementation.

Which one would you prefer ? Is option 1 ok ?

**Comment by elisachisari** [comment]
I would prefer the second option, so we can marginalize directly over b_I if we want without using A_I.

**Comment by damonge** [comment]
I'd suggest implementing this once the angpow branch has been merged (which should be soon).

**Comment by EiffL** [comment]
Ok great, happy to implement it, just ping me when the angpow branch is
ready then.

**Comment by jablazek** [comment]
I agree that you should be able to specify {A(z), f_fred(z)} or b_I(z), the latter of which would override the assumed 1/Growth(z) scale dependence. Is that the baseline plan?

We also want to be sure that the IA pipeline is sufficiently flexible to allow additional parameters in the future (assuming we want FAST-PT and/or halo model implementations to be in CCL eventually). Are there any technical challenges with adding new parameters in the future?

**Comment by damonge** [comment]
I think we're gonna have to deal with that carefully (e.g. right now linear parameters are easily implemented in the per-tracer transfer functions, but quadratic bias etc. are probably trickier). The same issues will arise for galaxy biases, so we'll make sure to do that sensibly

**Comment by jablazek** [comment]
Discussion on #639 reminded me of this, @elisachisari @damonge. I have essentially updated the normalization convention for IA (on CCL from ~1 year ago). I never pushed these changes, since it seemed like @beckermr made updates that took precedence over mine. Is this the case, or should I revisit this with the updated version of CCL?

**Comment by beckermr** [comment]
I’d wait for @damonge to do this all at once maybe?

**Comment by jablazek** [comment]
@beckermr : are we talking about the same thing? Did you update the IA normalization such that A_IA = 1 gives the fiducially assumed value (i.e. you don't need to specify some very small number with the relevant factors of rho_crit, etc)?

**Comment by beckermr** [comment]
I did not. That is in firecrown.

**Comment by jablazek** [comment]
Ah, OK. That makes sense. @elisachisari @beckermr , given the choice to primarily support the python interface, should this normalization update be made in C, or just at the python level?

I think that this update can be made in parallel with @damonge 's change.

**Comment by beckermr** [comment]
We should probably put it in the C so we find all of the code at once. There are two changes we are discussing

1. Make A = 1 mean the usual thing.
2. Get rid of or keep the two parameters that need to be set (something like A and f_red). 

I got confused about the issues. Both can be done at once. I think we decided to keep f_red?

**Comment by elisachisari** [comment]
A_IA=1 now implemented as fiducial. Only one bias parameter passed, so f_red does not exist anymore. This is all implemented in tracers.py, not in the C. See PR #630.
