### ISSUE TITLE
fails to build on some systems with SMP make flags

### ISSUE THREAD

**Issue by weatherhead99** [LSSTDESC/CCL#282]
I just tried to build this on opensuse with quite a few parallel jobs. The project fails at linking stage of the tests, unable to find -lccl, I think because a dependency is missing in the buildsystem. I am not very familiar with autotools but will try to find it. The build succeeds in serial mode.

Not a major issue because it's a fast build anyway

**Comment by damonge** [comment]
Hey Dan! Do you mean doing thing like "make -j8"? In that case, one final "make" after that will solve the issue. Do you think this is a good enough solution?

**Comment by beckermr** [comment]
Autotools has been deprecated. I am closing this issue. Feel free to reopen if you are still having trouble!
