### ISSUE TITLE
Fail to install PyCCL: GSL not found

### ISSUE THREAD

**Issue by jeremyneveu** [LSSTDESC/CCL#286]
Dear CCLers,
I failed again in installing PyCCL on my Mac OS (Sierra). GSL is installed via Macport (version 2.4) in `/opt/local/include/` and `/opt/local/lib/`.  The CCL installation works well. I tried many combinations of the command `python setup.py build_ext  --include-dirs=/opt/local/include/ --library-dirs=/opt/local/lib/ --rpath=/opt/local/lib/`, but no way, when typing `sudo python setup.py install` it ends with:
`checking for library containing pow... none required`
`configure: Using the built-in version of CLASS.`
`checking for library containing cblas_dgemm... -lgslcblas`
`checking for library containing gsl_spline2d_eval_e... no`
`configure: error: Couldn't find libgsl. GSL V2+ required.`
`Traceback (most recent call last):`
`  File "setup.py", line 282, in <module>`
`    'uninstall': PyUninstall`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup`
`    dist.run_commands()`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands`
`    self.run_command(cmd)`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command`
`    cmd_obj.run()`
`  File "setup.py", line 193, in run`
`    lib_path = self.build_library('ccl')`
`  File "setup.py", line 182, in build_library`
`    check_call(cmd, cwd='./', env=env)`
`  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call`
`    raise CalledProcessError(retcode, cmd)`
`subprocess.CalledProcessError: Command '['/bin/sh', 'configure', '--prefix=/opt/local/Library/Frameworks/Python.framework/Versions/2.7']' returned non-zero exit status 1
`
I checked that `/opt/local/lib/libgsl.a` exists. Any idea ?

**Comment by damonge** [comment]
@jeremyneveu : does this only fail for pyccl? Or does it also fail if you install only the C library? Do you know if it fails against your own installation of GSL 2+?

**Comment by jeremyneveu** [comment]
@damonge  : Only for pyccl yes. And this is on my laptop so yes it is my own Macport installation (if I have understood correctly your last question)

**Comment by damonge** [comment]
Then we have to ping @fjaviersanchez , since this has to do with the new version of setup.py

**Comment by fjaviersanchez** [comment]
@jeremyneveu could you please try `export LDFLAGS=-L$GSL_LIB_DIR` and export `CFLAGS=-L$GSL_INC_DIR`?

**Comment by jeremyneveu** [comment]
@fjaviersanchez Hi Javier. On my system by default $GSL_LIB_DIR and $GSL_INC_DIR are not defined. To test your solution, I defined `export GSL_INC_DIR=/opt/local/include/` and `export GSL_LIB_DIR=/opt/local/lib/`and then your two flags. But then the installation failed with the same error :(

**Comment by fjaviersanchez** [comment]
so `setup.py` as it is now, tries to install the C library and for some reason it is finding the wrong GSL version (or none). When you try to install the C version, what kind of flags do you have to define? Could you try to define the same ones and rerun `setup.py`? If it still doesn't work. I can try to make an option in `setup.py` to install just the python version and skip that part.

**Comment by jeremyneveu** [comment]
I do not define any particular flag. The C configure finds itself the /opt/local/include/ directory to find the GSL 2.4 that I installed, then the installation contains flags such as 
`/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -Wall -Wpointer-arith -O3 -fPIC -std=c++11 -fopenmp  -fno-common  -ffast-math -m64 -c -I./inc/ -I/opt/local/include/gsl  -g -O2 -MT src/libangpow_la-walltimer.lo -MD -MP -MF src/.deps/libangpow_la-walltimer.Tpo -c -o src/libangpow_la-walltimer.lo `test -f 'src/walltimer.cc' || echo './'`src/walltimer.cc`
`libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -Wall -Wpointer-arith -O3 -fPIC -std=c++11 -fopenmp -fno-common -ffast-math -m64 -c -I./inc/ -I/opt/local/include/gsl -g -O2 -MT src/libangpow_la-walltimer.lo -MD -MP -MF src/.deps/libangpow_la-walltimer.Tpo -c src/walltimer.cc  -fno-common -DPIC -o src/.libs/libangpow_la-walltimer.o`
So nothing particular. I would suspect that the `setup.py` options `--include-dirs` and `--library-dirs` do not work as they should. For instance if in setup.py I add `print libdir' at the end, I do not get the /opt/loca/lib path that I gave via the library-dirs option and the `setup.py  build_ext` procedure.

**Comment by fjaviersanchez** [comment]
So after a chat with @jeremyneveu we found out that for some reason sudo was not recognizing the export flags. I asked @damonge and he came up with a solution that is trying to put the `export LDFLAGS="-L/PATH/TO/GSL/lib"` and `export CFLAGS="-I/PATH/TO/GSL/include"` in the `.bashrc`. If this doesn't work I'll try to figure out another workaround to use your current configuration. (You can also try `sudo pip install pyccl` but I am not sure if that's going to work in my latest tests it installed it but got a segfault because of CLASS...)

**Comment by elisachisari** [comment]
@fjaviersanchez has this been documented in the README? If so, can we close this issue?

**Comment by fjaviersanchez** [comment]
@jeremyneveu were you able to install it with anaconda instead? @elisachisari I can add something in the README but I think this was a specific problem with Jeremy's setup.

**Comment by jeremyneveu** [comment]
@fjaviersanchez Hi. yes I was able to install it with anaconda and even my own python installation. The thing is that the default behaviour of my `sudo` command forget the environment variables. To get back them I had to use `sudo -E `....

**Comment by elisachisari** [comment]
Ok, thanks. I'm closing this issue then.
