### ISSUE TITLE
Code used to generate benchmarks should be collected and documented

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#290]
At the moment, we are validating CCL against benchmark datafiles generated by a variety of different codes -- mostly ones that were used during the code comparison project. We only keep the datafiles in version control, not the code, meaning that we can't systematically regenerate the benchmarks themselves, e.g. if we wanted to try different sets of cosmological parameters. The codes (versions, settings used etc.) that were used to generate the benchmarks are not documented in CCL either, which makes the whole validation procedure we are relying upon a little opaque.

We should collect the benchmark code together in one place, with run scripts and/or documentation to allow others to regenerate the benchmark files if they want to. If we can't collect all of it, we should at least have specific instructions on how to obtain and run the code, and what settings were used to generate the current set of benchmarks.

**Comment by philbull** [comment]
If we have the benchmark code available in one place, we can also automate running it for different sets of cosmological parameters. I can then add the data into the VARRIC visualisation tool.

**Comment by elisachisari** [comment]
As a compromise to address this issue before submitting the paper, I suggest listing who produced what [benchmarks in the wiki](https://github.com/LSSTDESC/CCL/wiki/Benchmarks) (if possible with links to the original code).

**Comment by c-d-leonard** [comment]
@philbull Would you consider this resolved now? Should we close it?

**Comment by villarrealas** [comment]
Resolved with the CCL paper.
