### ISSUE TITLE
Make CLASS optional?

### ISSUE THREAD

**Issue by elikrause** [LSSTDESC/CCL#292]
One short-term fix to the CLASS distribution/installation issue could be to make calls to CLASS optional, e.g. through a preprocessor directive: This would allow casual CCL users to check out the functionality of CCL (except for getting power spectra from CLASS), and while keeping the full functionality for users who already have CLASS installed/are willing to install it for CCL.

In practice, it would be possible to modify ccl_power.c such that include "class.h", and routines from "ccl_free_class_structs" through "ccl_cosmology_compute_power_class" are optionally included, with an alternate version for "ccl_cosmology_compute_power_class" that raises an exception if CCL attempts to call CLASS when it is not linked.

This would be very simple to implement on the C level. @damonge, do you know whether it would be an easy modification to autotools to check whether CLASS is installed, and set the preprocessor directive accordingly?

Please comment if you think this is bad style, or can think of a better short-term solution!

**Comment by elisachisari** [comment]
PR #295, which has an independent installation script for CLASS, has now been merged. It's slightly different than the approach suggested here, but it solves our license (PR #231) issues. Should we close this issue then?

**Comment by elisachisari** [comment]
Agreed. We'll leave this open for now.

**Comment by beckermr** [comment]
Once the python integration is done, this should be supported.
