### ISSUE TITLE
Consistency between tracer and Cls cosmology

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#299]
Currently, it seems possible to pass a given cosmology to build a tracer, and then use that tracer with a different cosmology to obtain Cls. Is there a way to prevent this inconsistency or at least issue a warning to the user?

**Comment by elisachisari** [comment]
@philbull Do you have any thoughts on this one?

**Comment by damonge** [comment]
I think there's a point in noting this in the documentation (that tracers hold some cosmology-dependent information) so people don't make that mistake, but there's only so much you can do to enforce consistency without losing modularity and ease of use (i.e. I wouldn't really implement any software measures to prevent this)

**Comment by beckermr** [comment]
I second @damonge on this. We can't save people from themselves. 

If we attach all of these methods to the cosmology struct, we will solve some of these issues. However ppl could still cheat the system. 

Are we good to close this one @elisachisari ?

**Comment by beckermr** [comment]
Any comments here or shall we close this?

**Comment by beckermr** [comment]
Mmmmk. No comments since Nov 1 of last year. Closing. Feel free to reopen.
