### ISSUE TITLE
ccl_tests*.c files fail to run

### ISSUE THREAD

**Issue by zdu863** [LSSTDESC/CCL#300]
Trying to run ccl_test_params.c under "tests" directory (or any other ccl_test*.c file.)

Following the procedure given in readme.md, I added "tests/ccl_test_params.c" in Makefile after the line starting with "TEST =":

TESTS = tests/check_ccl$(EXEEXT) tests/check_swig_timestamp.sh tests/ccl_test_params.c

Running "make test" in CCL main directory results in this error below:

~/Documents/CCL_new/CCL$ make test
make: *** No rule to make target 'test'.  Stop.

I'm not sure if this is the right way to do it. Also manually adding a line to "Makefile" feels weird since i believe it should be automatically generated.

**Comment by elisachisari** [comment]
Hi @zdu863. ccl_test_params.c runs automatically as one of the tests when you do:
```~/Documents/CCL_new/CCL$ make check```
You shouldn't need to add it manually to the Makefile.

**Comment by zdu863** [comment]
@elisachisari It works now, I was looking at the "better_c_tests" branch which tells me to use "make test" command.

So do I need to make that change to "Makefile" when I'm trying to write a new test?

**Comment by elisachisari** [comment]
Ok, thanks for letting us know. I don't recall that branch but I'll take a look to see at what stage it is.

If yo want to add new tests, you should follow the instructions in CONTRIBUTE.md within the main directory of CCL:
https://github.com/LSSTDESC/CCL/blob/master/CONTRIBUTE.md
You'll find there what needs to be modified in Makefile.am and how to re-configure.

**Comment by elisachisari** [comment]
BTW, that branch you mention was an earlier attempt by @philbull to improve on some of the tests, but we have plans to re-develop it, as it is quite behind our master branch at this point.
