### ISSUE TITLE
Establish procedure for changes to API

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#308]
We need to establish a procedure for when we make changes to the API. This should be documented in the wiki and/or in CONTRIBUTE.md

**Comment by damonge** [comment]
@elisachisari @philbull : it'd be good to know which steps in particular you'd like to add that are not already there.

**Comment by elisachisari** [comment]
We were discussing what kind of changes require a new release and concluded that anything that changes the API, including something like changes to function names, should come with a new tag and release notes. So we should make contributors aware of this.

**Comment by philbull** [comment]
Should this go in `CONTRIBUTORS.md`? We could add text along the lines of:

API Changes and Stability
An API breakage is anything that modifies the name or call signature of an existing public-facing function or variable (e.g. any function with the prefix `ccl_` in the C headers). Changes to keyword arguments of Python functions also fit this description, unless they are explicitly made backwards-compatible. Significant changes to the behaviour of a function also count as an API breakage (e.g. if an assumption is changed that causes different results to be produced by default). Fixing a bug that affects the output of a function does not count as an API breakage.

If the API is broken, the CCL version number must be incremented (e.g. from v0.1 to v0.2), and a new tagged release should be made shortly after the changes are pushed to `master`. The new release must include notes in the `CHANGELOG` that describe how the API has been changed. The aim is to make it clear to users how their CCL-based code might be affected if they update to the latest version, especially if the update is likely to break something.

There is not yet any absolute need to preserve backwards-compatibility between point releases (e.g. v0.2 does not need to support everything that v0.1 did). This will change as the code matures, though. After v1.0 is released, we expect to maintain backwards compatibility for all releases with the same major version number, i.e. v1.1 should support all the same behaviors that v1.0 supported, plus whatever new additions are made.

**Comment by elisachisari** [comment]
This looks like a good addition to CONTRIBUTE.md. In addition, I would say that before breaking the API, it's good policy to discuss with the team whether this is absolutely necessary. We don't want to have too many releases.

**Comment by philbull** [comment]
OK, I'll make a pull request.

**Comment by philbull** [comment]
See PR #336.
