### ISSUE TITLE
Pass T_cmb to CLASS

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#311]
We hardcode T_cmb in a couple of places in the C code (in ccl_core.c and ccl_neutrinos.c), but we don't currently pass this value to CLASS in ccl_power.c . This is potentially an issue because if we don't pass a value CLASS will assume its default value, which is very close but not quite the same as our hard-coded value. This means that the distances calculated by CCL use a slightly different Omega_{radiation} than is used in CLASS to compute the matter power spectrum. This probably has a very very low level effect but could be important at high z in some cases.

@elikrause I was told you implemented part of this and might be the one to have a look at it?

**Comment by elikrause** [comment]
Does this require more than simply passing cosmo->params.T_CMB to CLASS (as implemented in #4115c2e), e.g. a switch whether to to pass T_CMB or Omega_{radiation}?

**Comment by c-d-leonard** [comment]
Nope that's it I think! That change seems to cover it.

**Comment by elisachisari** [comment]
@c-d-leonard @elikrause Can we close this?

**Comment by c-d-leonard** [comment]
Yep, closing now.
