### ISSUE TITLE
Error message when running 'autoreconf'

### ISSUE THREAD

**Issue by zdu863** [LSSTDESC/CCL#314]
I was following the steps in `CONTRIBUTE.md` to create a new ctest file, running:
`~/Documents/CCL_3d/CCL$ autoreconf -i`
which gave an error message:
```
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and `rerunning` libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
```
However, this command still ended up modifying `Makefile.in`, and everything runs OK after I reinstalled CCL. I just thought I would point this out, maybe those lines should be added according to the error message?

**Comment by ellison-j** [comment]
Zilong: I talked to Phil Bull and he said this is fine. This will be checked and taken care of if necessary when they merge into master.

**Comment by philbull** [comment]
Thanks for filing this issue! Yes, there are just warnings, so no need to worry about them. We may try to fix them at a later date, but they seem to be harmless and so aren't a priority for now.
