### ISSUE TITLE
Is CCL thread safe?

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#316]
We need to check this, particularly for integration to TJPCosmo

**Comment by tmcclintock** [comment]
As per the [GSL docs](https://www.gnu.org/software/gsl/manual/html_node/Thread_002dsafety.html) anywhere that we use GSL is thread safe unless we do any really wacky things.

**Comment by damonge** [comment]
Actually, one thing that isn't thread-safe automatically is splines. Or rather, splines are thread-safe, but interpolation accelerators aren't. See #137

**Comment by beckermr** [comment]
Yes!
