### ISSUE TITLE
sigma8 is defined wrong

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#318]
In `pyccl.power.sigma8()`, the value of `sigma8` is computed for 8 Mpc, however this quantity is defined for 8 Mpc/h. This should be fixed.

**Comment by elisachisari** [comment]
That's strange: the ccl_sigma8 function is computing it for 8 Mpc/h in the C file:
https://github.com/LSSTDESC/CCL/blob/master/src/ccl_power.c
Is it maybe the case that the python docs are wrong but the function is ok?

**Comment by elisachisari** [comment]
Looking at:
https://github.com/LSSTDESC/CCL/blob/master/pyccl/power.py
it indeed seems to be a problem of inconsistency of the docs rather than the code.

**Comment by tmcclintock** [comment]
(Apologies if I wrote the docs for that way back when X-D).

**Comment by alexander-mead** [comment]
Via the python interface: if I find that ```ccl.sigma8``` gives me exactly the same result as ```ccl.sigmaR(cosmo,8/cosmo.params['h'])```, which I think is the correct behaviour.

**Comment by elisachisari** [comment]
Based on @alexander-mead's comment above, I'm closing this issue.
