### ISSUE TITLE
pyccl calls for sigmaR (and possibly others) fail on integer passes

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/CCL#324]
The function sigmaR takes parameters cosmo + a sphere size R. However, if it is passed an integer for R (something like 8), it simply crashes because it cannot take an integer value. Since it is feasible people will want to pass it something like linspace with integers, this might be a concern?

I suspect this may be elsewhere in pyccl wrapper work.

**Comment by tmcclintock** [comment]
@philbull wrote the vectorization wrappers. I think the cleanest thing to do would be to do type casting there. What do you think, Phil?

**Comment by philbull** [comment]
This should now be fixed in PR #334 -- please review!

**Comment by philbull** [comment]
Fixed and merged.
