### ISSUE TITLE
Error while running python tests

### ISSUE THREAD

**Issue by gvalogia** [LSSTDESC/CCL#326]
After completing the installation and when running the python tests with `run_tests.py`
I get the following error

`ERROR: Test top-level functions in pyccl.cls module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/George/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/George/Downloads/CCL_demo/CCL/tests/ccl_test_pyccl_interface.py", line 339, in check_cls
    assert_( all_finite(ccl.angular_cl(cosmo, lens1, nc2, ell_arr)) )
  File "/Users/George/Library/Python/2.7/lib/python/site-packages/pyccl/cls.py", line 311, in angular_cl
    check(status, cosmo_in)
  File "/Users/George/Library/Python/2.7/lib/python/site-packages/pyccl/pyutils.py", line 24, in check
    raise RuntimeError("Error %s: %s" % (pyccl.core.error_types[status], msg))
RuntimeError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cl(): error integrating over k
`
Out of the 4 tests I ran in total, the error showed up in 3 out of the 4.
Seems like a gsl integration-related issue.

gsl version: 1.16
Python 2.7.11
OS Sierra Version 10.12.6

**Comment by philbull** [comment]
I'm not getting this bug, and the tests are passing on `master`, so not sure what's going on. It might be something to do with your setup -- do the C tests work, i.e. when you run `make check`?

**Comment by philbull** [comment]
Actually, it looks like your version of GSL is old. We depend on GSL 2.1 or higher.

**Comment by gvalogia** [comment]
Yes,

Based on short discussions I had, others also seemed to agree that It probably has to do with the older version of gsl used.
I plan on updating it in the next few days, so I will let you know if the problem persists.

**Comment by elisachisari** [comment]
I have GSL 2.4 and I have ran into this this problem too. Python tests randomly give an error for C_ell integration. If you run the python tests several times in a row, sometimes it crashes, sometimes it doesn't. We think it might have to do with how GSL chooses seeds for integrations (@tmcclintock?).

**Comment by tmcclintock** [comment]
Definitely a problem. I'll get on it. My plan is to do the following:
- be able to run *just* the one test that causes this issue
- put in print statements figuring out the GSL RNG seed, and see if the seed is changing and if so, what seeds cause the crash
- figure out what causes the crash

Should I do this in a new branch?

**Comment by tmcclintock** [comment]
This is the specific unit test that is causing the issue:
`assert_( all_finite(ccl.angular_cl(cosmo, lens1, nc2, ell_arr)) )`

It is found in `cc_test_pyccl_interface.py` and it calls `ccl_angular_cls()`. Will update as I go.

**Comment by elisachisari** [comment]
@tmcclintock Sounds like a good plan. Yes, please open a new branch to incorporate any changes.

**Comment by elisachisari** [comment]
This seems related to #347

**Comment by elisachisari** [comment]
As PR #371 addressed #347 and this seems to be related, I'm closing this issue.
