### ISSUE TITLE
Distance calculation with bounce cosmologies

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#330]
First, let me apologise for posting this if this is a waste of time, but I was playing with CCL on the plane on the way back from SLAC...

I am getting a python kernel crash with the following script:

```
import pyccl as ccl

cosmo = ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, Omega_k=-1.3, h=0.7, A_s=2.1e-9, n_s=0.96)
print(cosmo)

a=0.9
print(ccl.comoving_radial_distance(cosmo,a))
```

This cosmology is quite extreme (Omega_vac = 2!) and exhibits a bounce around a ~ 0.6 (in this particular example, so 'a' is *never* less than 0.6): there is no big bang and as t -> -inf the universe is collapsing, and then has a bounce so as to be expanding today. Because of this, things like the distance as a function of scale factor are multi-valued.

Maybe the time spent supporting such absurd cosmological models should be limited, but it might be nice to have a warning and a graceful exit, rather than a kernel crash? A general way of testing for such multi-valued models, or those with no big bang, would be to integrate the full Raychaudhuri equation for the cosmology in question to check explicitly that 'a=0' for some 't'. It might not be worth the hassle...

**Comment by tmcclintock** [comment]
IMO for version 1 it should definitely just gently exit.

Just curious, but do you know ballpark what kinds of things would need to be implemented to support such a model besides the integral you mentioned?

**Comment by alexander-mead** [comment]
I guess it would depend. Obviously for such a model there isn't a CMB, so you couldn't really support that. If you still wanted to support the model in terms of being able to calculate distances and times as a function of scale factor then I think you need to reformulate the problem as calculating a(t) and Chi(t) because these are then not multi-valued. The problems arise when you ask for Chi(a), because that is multi-valued.

My suggestion for a check for a gentle exit would be to integrate the Raychaudhuri equation (starting from initial conditions set 'today' such that a=1 and \dot{a}/a=H_0) back in time and then to check explicitly that a(t) is (i) monotonic and (ii) has a=0 at some value of t.

FYI: Both http://www.astro.ucla.edu/~wright/CosmoCalc.html and http://cosmocalc.icrar.org/ also have problems for these type of cosmologies and do not produce helpful warning messages.

**Comment by asgr** [comment]
I think cosmocalc works reasonably out to OmegaL[0]=1.7, then something goes bad in the integral. Have a look a the plot tab to see the collapse and then "negative" comoving distances at the bounce z. (In case you are wondering, I occasionally get alerts to cosmocalc.icrar web mentions).

**Comment by c-d-leonard** [comment]
I'm just going through old issues, I'm going to assign myself to check if this cosmology still causes a kernel crash.

**Comment by t-ferreira** [comment]
This is still true. It happens for Omega_k < -1.0135 (approximately).

**Comment by nikfilippas** [comment]
Closing as CCL does not allow Ω_k < -1.0135 anymore. It would be fairly complicated to implement new functions with time as the time variable instead of the scale factor.
