### ISSUE TITLE
Read in arbitrary tomographic dN/dz

### ISSUE THREAD

**Issue by ssamuroff** [LSSTDESC/CCL#333]
As far as I can see, setting up a dNdz_tomog object requires a redshift error function p(z_phot | z_spec) to be provided, which is then integrated with the dN/dz from Chang et al. One possibly useful extension is the ability to read in an arbitrary set of tomographic dN/dz directly without having to specify an underlying analytic error model. So, for example, one might want to input the DES Y1 redshift distributions from a file, and pass them through the subsequent theory calculations to predict Cls, xi_+/- etc.

I appreciate this functionality is already there in CosmoSIS and CosmoLike, but I think it's a nice feature to have for forecasting. It would also be needed if we want to be able to call CCL for the modelling part of a likelihood analysis involving real data.
Do people agree this would be useful? If so I could look into implementing it.

(Also, I think this is similar but non-identical to issue #298 - sorry if I'm actually repeating what was requested there, or if I've misunderstood the code as-is and this is already possible).

**Comment by damonge** [comment]
@ssamuroff : I think this is already possible through the Cl tracers, right? The N(z) is one of the parameters you pass to them, and it doesn't have to come from the dNdz_tomog, any N(z) will do. See for example ClTracerLensing in https://github.com/LSSTDESC/CCL/blob/master/pyccl/cls.py .
Does it make sense?

**Comment by philbull** [comment]
We should make this a bit clearer in the examples, perhaps.

**Comment by ssamuroff** [comment]
Hi @damonge, @philbull - yes, you're quite right - thanks!
It could be worth stating explicitly somewhere that the n(z) required for the Limber calculation is just a numpy array, and that PhotoZFunction() and everything in ccl_lsst_specs.c are needed only for the purposes of generating analytic redshift distributions.
But to be honest the example about generating Cls is actually pretty clear - I think it was probably just me being slow on the uptake.
Sorry for the annoyance.
