### ISSUE TITLE
Fix / improve neutrino-related user interface

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#335]
This is related to what I am working on now in the multiple_neutrinos branch and I am about to code up the fix, so I am just posting here for completeness and to invite any comments:

As some of you know, I spent most of hack day at the recent meeting trying to come up with a good, intuitive method for accepting neutrino information from the user, so that when CCL is called the defaults for neutrinos basically do what people would expect. The idea here is (a) the neutrino API is kind of a mess due to the piece-by-piece way this support has been implemented so we might as well fix it now before the release and (b) we don't want different groups making different assumptions about default neutrino parameter behavior so we want to make this as intuitive as possible.

Here's what I've come up with after thinking about it:
- In python, the user should pass Neff and m_nu, where m_nu can be a float or a list / array of length 3. If it's a float, we interpret it as the sum of neutrino masses (more on that in a second).
- In C, same thing, only the user has to pass also a boolean variable, something like "mnu_is_sum", to tell C the length of the pointer to mnu (in python, this is automatically calculated and passed to C).
- In ccl_parameters_create (in C), if the user has passed a single value for mnu we take this as the sum of masses and assign three neutrino masses according to the normal hierarchy. 
- Either way, we then calculate the number of massive neutrinos by checking how many of the three are above the mass limit to be nonrelativistic today. We calculate the number of relativistic neutrinos using this information, Neff, and the "black magic" calculation from which the weird numbers in explanatory.ini come (it's not black magic, I know where this come from now, I will document in the note).
- Then, proceed as before.

The only issue with this is the emulator, which as we know, assumes fixed Neff = 3.04 and 3 equal mass massive neutrinos. To deal with this, after discussion the slack channel with @philbull, the current working solution is to by default force an emulator-using user to pass a list of three equal neutrino masses, but to include a new keyword in the configuration which can be switched to allow the user to mass a sum of neutrino masses and have the relevant emulator function in ccl_power.c split this into equal masses. This will cause internal inconsistencies (distances and the emulator power spectrum will be calculated using slightly different neutrino masses) but the user would have to actively choose to accept this, so we think it's okay.

The Omeganuh2 <-> mnu function is to test the emulator. Since we have to make an assumption about how to split the mass into 3 neutrinos here, we should split it equally to agree with the emulator.

Let me know if you have any comments. I'm going to start coding this up now.

**Comment by alexander-mead** [comment]
For what they are worth, here are some of my thoughts. Please feel free to ignore them though:

I think that if you want to allow users to just pass 'neutrino mass' then the solution you propose is a good solution.

What was the argument against forcing users to either (a) pass all three neutrino masses explicitly or (b) at least force users to specify the hierarchy they are interested in, along with a total mass? In the case of (b) you could allow 'normal', 'inverted' or 'equal mass', where the first two are consistent with the particle physics experimental data. At least in this case this forces the user to think about what they are doing. This would avoid your emulator-related problem as you could only allow the emulator to be activated when the user has specified 'equal mass' and n=3.04, in which case they are at least aware of assumptions that they are making and assumptions that are going into the emulator.

**Comment by c-d-leonard** [comment]
So, the argument against forcing users to pass all three neutrino masses was that it seems likely users who only want to care about the sum (probably many users / several working groups at least) will make adhoc choices of 3 masses to get the sum right. What we don't want is different people making different parts of a parameter inference pipeline to make different adhoc choices, so we want to give users an option to just pass the sum and let us sort out the rest in a reasonable way.

That being said, I think it makes sense to at least allow the user to specify the inverted hierarchy if they want, even if the normal hierarchy is a default (as suggested in the slack by @erozo).

**Comment by elisachisari** [comment]
@c-d-leonard can we close this?

**Comment by c-d-leonard** [comment]
@elisachisari Yep, this is done. I'll close it now.
