### ISSUE TITLE
Improved functionality / user interface of Omeganuh2_to_Mnu function.

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#338]
In working on the multiple_neutrino branch and beginning the changes discussed in Issue #335 , I have been looking at the function Omeganuh2_to_Mnu, which currently (in master) takes the value of Omeganu*h^2 and converts it to the sum of neutrino masses. This function was added because the CosmicEmu emulator accepts Omeganuh2 as input, and we wanted to be able to make consistent external runs of the emulator for testing purposes.

Adding support for non-degenerate neutrinos requires a choice in how we output the masses of neutrinos given Omeganuh2. The obvious choice is equal masses, because that is what the emulator requires. However, it has been suggested, and I agree, that it would be helpful for this to be a bit more of a useful workhorse function which can handle different cases. For example, the function could accept a label indicating how you want to split the masses, with possible values "equal" "normal" (for normal hierarchy), "inverted", or "sum" to just output the sum. This would still allow our emulator-testing case but would provide more functionality.

Another thing about this function in the python wrapper I would like to modify is the fact that the python wrapper version of the function accepts an array of scale factor a values. However, I don't think this makes sense - we want to convert between parameters of Omeganu*h^2 at z=0 and m_nu. To my understanding this conversion relies on Omeganu*h^2 taking it's z=0 value. Also, allowing a vector of scale factors / redshifts in the python wrapper introduces some difficulty with swig when we want to output 3 neutrino masses at each z (although I think this can be overcome). Does anybody see a reason to keep this z ( / a) dependence?

Tagging you @elikrause because I think you originally wrote this function? Thanks for any comments.

**Comment by elisachisari** [comment]
@c-d-leonard can we close this?

**Comment by c-d-leonard** [comment]
Yep, closing now.
