### ISSUE TITLE
convenience function for critical density in a given cosmology in Python

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#341]
It would be great to have a function for getting rho_critical in a given cosmology from the python wrapper (I know I'm not the only one who has to rederive this every time ...)

**Comment by alexander-mead** [comment]
I guess it would also be useful to have a function for rho_matter... and also for physical and comoving versions of rho_matter and rho_critical.

**Comment by sjoudaki** [comment]
I can do it.

**Comment by sjoudaki** [comment]
Hi Danielle, are you happy for the units to be M_sun/h / (Mpc/h)^3?

**Comment by alexander-mead** [comment]
I think that, in order to be consistent with everything else, the units should not have h factors in them.

**Comment by alexander-mead** [comment]
I wrote this function for the comoving matter density already, which I'm fairly sure is correct:

double comoving_matter_density(ccl_cosmology *cosmo){
  // The comoving density of matter. This is a constant. Units are Msun/Mpc^3 (no factors of h)
  return RHO_CRITICAL*cosmo->params.Omega_m*cosmo->params.h*cosmo->params.h;
}

**Comment by sjoudaki** [comment]
Sounds good, I can certainly make sure no factors of h. What you've written is correct for the present. I've created the redshift-dependent "ccl_rho_x", will try to push soon.

**Comment by alexander-mead** [comment]
I think ```CCL``` already has the constant z=0 ```RHO_CRITICAL``` defined, which has units of Msun/h / [Mpc/h]^3 (note this is with h factors) and has the value ~ 2.77466e+11 

Copying out from my Fortran halo-model code, I have four other types of densities defined. I think these are sensible things to define, but maybe you should check... note that I use units *with* h factors and my constant ```critical_density``` is the same as the ```RHO_CRITICAL``` from ```CCL```.

```
 FUNCTION comoving_critical_density(z,cosm)

    !Comoving critical density in (Msun/h) / (Mpc/h)^3
    IMPLICIT NONE
    REAL :: comoving_critical_density
    REAL, INTENT(IN) :: z
    TYPE(cosmology), INTENT(IN) :: cosm

    comoving_critical_density=physical_critical_density(z,cosm)/(1.+z)**3

  END FUNCTION comoving_critical_density

  FUNCTION physical_critical_density(z,cosm)

    !Physical critical density in (Msun/h) / (Mpc/h)^3
    IMPLICIT NONE
    REAL :: physical_critical_density
    REAL, INTENT(IN) :: z
    TYPE(cosmology), INTENT(IN) :: cosm

    physical_critical_density=critical_density*Hubble2(z,cosm)

  END FUNCTION physical_critical_density

  FUNCTION comoving_matter_density(cosm)

    !Comoving matter density in (Msun/h) / (Mpc/h)^3
    !Not a function of redshift!
    IMPLICIT NONE
    REAL :: comoving_matter_density
    TYPE(cosmology), INTENT(IN) :: cosm

    comoving_matter_density=critical_density*cosm%om_m

  END FUNCTION comoving_matter_density

  FUNCTION physical_matter_density(z,cosm)

    !Physical matter density in (Msun/h) / (Mpc/h)^3
    IMPLICIT NONE
    REAL :: physical_matter_density
    REAL, INTENT(IN) :: z
    TYPE(cosmology), INTENT(IN) :: cosm

    physical_matter_density=comoving_matter_density(cosm)*(1.+z)**3

  END FUNCTION physical_matter_density
```

**Comment by alexander-mead** [comment]
So, the comoving matter density is just a constant given by *Omega_m* multiplied by ```critical_density```. The physical matter density is just this comoving density times *(1+z)^3*.
