### ISSUE TITLE
k_pivot

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#342]
CCL should report in the documentation what k_pivot is assumed. This is relevant when the user sets A_s rather than sigma8.

Right now this is set to whatever the default of CLASS is. This is 0.05 Mpc^-1, but it could vary in future versions (or with other versions used by users). We could set it to 0.05 by hand to make sure that whatever we document will not vary with the CLASS version.

**Comment by elisachisari** [comment]
It could be included in ccl_params.ini but we need to make sure we pass it to CLASS correctly by adding an initialisation in `ccl_fill_class_parameters'.

**Comment by beckermr** [comment]
This can now be set globally from python. Closing this issue.
