### ISSUE TITLE
Clarification of the growth function

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#344]
The growth function in CCL is computed using some equations that assume that perturbations are much smaller than the horizon and that the universe is dominated by a single matter component. Under these assumptions a scale-independent growth function can be computed.

The assumption of scale-independence breaks down for massive neutrinos, but also for more standard models with baryons and dark matter because these two components have different power spectra after recombination due to different physics affecting them during the radiation era. Therefore, there is no such thing as a scale-independent growth function for any realistic cosmology.

The utility of the scale-independent growth function is that it closely approximates the growth of the total matter power spectrum during the post-recombination era. But does it approximate this closely enough to be within the accuracy requirements for CCL?

Attached is a plot I made that compares the CCL growth function to the (square root of the) ratio of the power spectrum evaluated at different wave numbers. You can see that there are differences of several per cent at high redshift. My question is: is this a problem? Probably the answer to this depends on exactly where CCL uses the growth function, which I don't think is currently documented.

![image](https://user-images.githubusercontent.com/9140961/36816794-c7b5cbfe-1c93-11e8-88c8-f2ce42d1c414.png)

**Comment by elisachisari** [comment]
@damonge @jeremyneveu Is the growth at any point used in computation of Cl's? (I.e., do we ever obtain the power spectrum at a given redshift by re-scaling with the growth?)

**Comment by jeremyneveu** [comment]
@elisachisari the growth rate is used, but the growth function itself is not used explictely as we use directly the P(k,z) function.

**Comment by elisachisari** [comment]
So we never do P(k,z)=P(k,z=0)D^2(z)? To my knowledge this is the only place where CCL might use D(z).

**Comment by jeremyneveu** [comment]
Actually it is used in the master branch for the Cl's computation in hte Limber approx, but not to rescale the P(k,z) but to rescale the RSD effect term. This is no more present in the non_limber branch because the limber integrals are coded in a different way.

**Comment by elisachisari** [comment]
If RSD is the only place where this appears now, I think we don't need to worry about the accuracy of the plot above for the time being. If we end up incorporating observables other than 3x2, then we can revisit this. I'm inclined to close this issue. @alexander-mead what do you think?

**Comment by alexander-mead** [comment]
@villarrealas @tmcclintock : does the growth function get used to scale sigma(R)/sigma(M) in redshift? I thought it did. This may not be accurate at the 1e-4 level given the plot above?

**Comment by damonge** [comment]
Yes it does!
https://github.com/LSSTDESC/CCL/blob/9bc95796b328e4b50b8a09970431786d2e3c2f14/src/ccl_massfunc.c#L498

**Comment by alexander-mead** [comment]
Further to this, here are a few other plots:

![image](https://user-images.githubusercontent.com/9140961/37306894-6c16dfec-25f6-11e8-9edf-545d32861e29.png)

![image](https://user-images.githubusercontent.com/9140961/37306902-72b7271c-25f6-11e8-818b-a0afeb5147ca.png)

![image](https://user-images.githubusercontent.com/9140961/37306908-782af124-25f6-11e8-8ca2-e561ddc5cf05.png)

They all show the growth factor (normalised such that *g(a=1)=1*) and the growth rate as a function of scale-factor, just with different axis types. 

At high redshift the curves deviate from power-law behaviour. I suppose this is because at high redshift the Universe is radiation dominated, rather than matter dominated. But then these growth equations aren't really valid during radiation domination... and I think the initial conditions are set such that the initial growth is in the matter-domination growing mode (*g=a*), right? Probably this does not make very much difference by *a~1* anyway, because the solution will get itself into the growing mode during matter domination.

I'm not quite sure what the correct thing to do here is. One alternative to what is currently implemented would be to calculate the growth function ignoring radiation completely in the Hubble parameter, so at high redshift the universe really is matter dominated.

In any case, I think the documentation needs to be updated so as to be very explicit about what exactly is being calculated and the limitations of the calculation. Personally I find the growth function a very useful thing, but it certainly has some limitations.

**Comment by alexander-mead** [comment]
Elisa asked me if this issue can be closed. I'm not sure. I guess the point of the original plot I posted over a year ago is that the approximation `P(k,z) = g(z)^2 P(k,z=0)` will not be accurate at all wavenumbers at all redshifts, particularly not at high redshift. From the plot I made it's not so obvious which redshifts and scales will be affected beyond the 1e-4 accuracy requirement of CCL, but clearly this will happen at high enough z.

I think most functions in CCL do not use the growth function for the redshift dependence, but some do, like sigma(R). Whether or not this is a problem I don't know. I'm happy for the issue to be closed if others think this will never be a problem.

**Comment by tmcclintock** [comment]
RE the growth function appearing in the halo mass function (and probably halo bias): this need not be the case. We could instead pass in P(k,z) directly, or just do the integrals for sigma(R,z) on the fly when the mass function is called. This would slow down the code _slightly_, but be correct up to the power spectrum being correct. I recommend this change, but maybe closing this issue and opening a new one with this implementation change as the main topic.

**Comment by damonge** [comment]
I would actually suggest the following: instead of computing sigma(R,z) on the fly, we promote the current sigma(M) spline (`cosmo->data.logsigma`) into a 2D spline. Otherwise any halo model calculations will also be affected and could slow things down significantly.

**Comment by tmcclintock** [comment]
Yea, that also works.

**Comment by c-d-leonard** [comment]
@damonge @tmcclintock is this resoled by the new halo model support?

**Comment by damonge** [comment]
No, but it's basically the same problem as #609 
I'd close this one if we're leaving 609 open

**Comment by c-d-leonard** [comment]
Okay, closing and leaving 609 open.
