### ISSUE TITLE
Building latest master at NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/CCL#346]
Hi,
@yymao asked that we install CCL in the shared python environment at NERSC on Cori. I'm using master.  The build is a little different now that the class library is a requirement.  I've been following the issues #307, #12, and the instructions here: https://github.com/LSSTDESC/CCL/wiki/Using-and-Installing-CCL-on-NERSC. After completing the `python class_install.py` we still only have a static `libclass.a` produced.  Issues #12 suggests we need to also create a shared library.  Is that still true?  I went ahead built libclass.so, since my `.configure` step consistently fails to find libclass even though it is in the default location and also tried setting `CLASSDIR`.
```checking for library containing pow... none required
configure: Using the version of CLASS from /global/common/software/lsst/cori-haswell-gcc/CCL/20180305/class
checking for library containing background_free... no
configure: error: Couldn't find libclass.
```
having the shared libclass doesn't make a difference.  I've tried using the default gcc 7 as well as the gcc 6.3.0 that I typically use to align with the version DMstack uses for its builds. Regardless, the configure step doesn't "find" libclass, but the error seems to be a linking problem, if I search in config.log:
```configure:13472: cc -o conftest -g -O2 -I/usr/common/software/gsl/2.1/gnu/include -I/opt/cray/pe/fftw/3.3.6.2/haswell/lib/../include -L/usr/common/software/gsl/2.1/gnu/lib -L/opt/cray/pe/fftw/3.3.6.2/haswell/lib -L./class -lclass conftest.c -lclass   >&5
./class/libclass.a(arrays.o): In function `array_logspline_table_lines':
/global/common/software/lsst/cori-haswell-gcc/CCL/20180305/class/build/../tools/arrays.c:800: undefined reference to `_ZGVbN2v___log_finite'
/global/common/software/lsst/cori-haswell-gcc/CCL/20180305/class/build/../tools/arrays.c:800: undefined reference to `_ZGVbN2v___log_finite'
/global/common/software/lsst/cori-haswell-gcc/CCL/20180305/class/build/../tools/arrays.c:802: undefined reference to `_ZGVbN2v___log_finite'
```
I've tried add `-lm` and that didn't fix it either.  Others much be building master?  I could go back to last 0.2.1 release and see if that works.
As the python installation now also builds the C libraries, perhaps I should be using that method instead, however, I would imagine I need to set up GSL and FFTW appropriately.  Any hints appreciated.

**Comment by fjaviersanchez** [comment]
@heather999 Have you tried including these flags:
``
export CRAYPE_LINK_TYPE=dynamic
export XTPE_LINK_TYPE=dynamic
``

**Comment by heather999** [comment]
Thank you @fjaviersanchez That fixed it.  I'm going to update the installing at NERSC wiki :)
