### ISSUE TITLE
Artefacts in lensing Cls

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/CCL#347]
I noticed that the lensing Cls have small artefacts (peaks at certain ell values). For the GG terms they are small (in this example < 0.1%) but become large (>1%) for the IA terms. The following plot shows the fractional difference between neighbouring ell-values:

![cl_artefacts](https://user-images.githubusercontent.com/26582252/37162250-aeab9f3a-22ec-11e8-84e1-78c1b81c012a.png)

I extract the GI term by computing G(G+I) and then subtracting the GG term. Since the GI term is much smaller than GG, this amplifies the effect of these artefacts.

I tried changing the A_SPLINE_NA_PK parameter but this doesn't seem to have an effect, nor changing the number of samples in the provided n(z).

Are there other parameters that can be used to tune the precision of the Limber integrals?

[Example code](https://github.com/LSSTDESC/CCL/files/1793917/test_ccl_stuff.py.txt)

**Comment by damonge** [comment]
There are GSL integration parameters that could be tweaked for this, but they're not accessible to the user right now. Some of this may be fixed when the Angpow PR gets merged, so I'd suggest waiting until then and checking again (I'll rerun the code).

**Comment by tilmantroester** [comment]
Since I was playing around with the GSL parameters for the other issue anyways, I figured I could check how ccl_angular_cl depends on the choice of GSL parameters. Plotted below are the fractional differences for different choices of epsrel and the number of Gauss-Kronrod points compared to the case where epsrel=1e-6 and 61 Gauss-Kronrod points. The grey band denotes a fractional difference of 1e-4.

![cl_artefacts_2](https://user-images.githubusercontent.com/26582252/38153576-64901b6c-3465-11e8-9694-d72caa104179.png)

The upshot is that the current settings aren't sufficient if a 1e-4 accuracy is required everywhere.

**Comment by elisachisari** [comment]
@tilmantroester thanks for doing this - none of the curves lie within the gray band then? What do you suggest to improve this? Is it as simple as decreasing epsrel (at the cost of extra computational time)?

**Comment by tilmantroester** [comment]
@elisachisari In case of the n(z) I used for the comparison, either using epsrel=1.0e-4 and GSL_INTEG_GAUSS61 or epsrel=1.0e-5 and GSL_INTEG_GAUSS51 gets us within the 10^-4 band everywhere. I haven't checked the impact on the computational time yet. 
I'll implement a structure to hold GSL parameters analogous to ccl_spline_params, which should make these comparisons a lot easier.

**Comment by tilmantroester** [comment]
Changing epsrel to something smaller than 1e-4 causes roundoff errors in the cls:histo test. Using GSL_INTEG_GAUSS61 is fine, however, and doesn't seem to incur any extra computational cost.
It might be worth considering a switch that allows the use of cquad instead of qag when necessary, since the latter seems to have problems with multiple integrals (e.g., this one, the one in issue #350) and cquad appears to work better (according to #353).

**Comment by tilmantroester** [comment]
Addressed with PR #371.
