### ISSUE TITLE
Consistent and robust error handling

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/CCL#355]
I have run into some issues with the way errors are currently handled. The problem is that status is set to 1 (and maybe even some error message is set) but the execution of the code proceeds uninterrupted. New errors can occur and overwrite the original error message or worse, the error is caught at completely different location than where it originally occurred. This makes it very difficult to troubleshoot problems and even causes bugs in places that would be fine by themselves. For example, in issue #354 (cl_tracer_new):
https://github.com/LSSTDESC/CCL/blob/f6f2d48e0a7653538a155cf02bf7982f53236eb6/src/ccl_cls.c#L164
Here ccl_h_over_h0 sets status to 1 (because a=1 is outside the spline domain). This is not caught, however, and status remains set to 1. At some point later, ccl_comoving_radial_distances is called (with valid arguments, line 306). The first check for status happens in ccl_comoving_radial_distances:
https://github.com/LSSTDESC/CCL/blob/f6f2d48e0a7653538a155cf02bf7982f53236eb6/src/ccl_background.c#L677
Here status != GSL_SUCCESS even though the spline interpolation was successfull, because status was still set to 1 from before. This causes ccl_comoving_radial_distances to return NaN, which isn't caught either. This then results in an undefined nchi, which finally breaks ccl_linear_spacing, resulting in the error message reported in issue #354.

In issue #350:
The function window_lensing does check whether the integration was successful:https://github.com/LSSTDESC/CCL/blob/f6f2d48e0a7653538a155cf02bf7982f53236eb6/src/ccl_cls.c#L67
But in case of a failure, the GSL error message is ignored and we are only told that there was an error in the lensing window function, while gsl_strerror(gslstatus) would tell us that the problem is a roundoff error.

The first example could be solved by calling ccl_check_status whenever status could be set to 1. In the second example, in addition to checking for a set error flag, reporting the GSL error message would be useful. Are there specific reasons this is not being done, such as performance?

**Comment by beckermr** [comment]
We now pass all errors up to python and they are dealt with there via centralized functions that call the swig wrapper. Closing.
