### ISSUE TITLE
Odd temporary directory during installation

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/CCL#358]
Hi all,

The current setup.py does a weird thing to find a temporary directory to install to:
```
        if self.user:
            self.build_temp = os.path.join(self.install_userbase, 'temp' + plat_specifier)
        else:
            self.build_temp = os.path.join(self.prefix, 'temp' + plat_specifier)
```
the dir that this returns is typically not user-installable without sudo.  Unless there's a reason for this odd path, this would be a better way of generating a temporary directory if that's what's needed:
```
        import tempfile
        self.build_temp = tempfile.mkdtemp()
```
though it should also be automatically deleted after install.

Best,
Joe

**Comment by elisachisari** [comment]
In light of PR #357, this might become obsolete soon. Let's see if we manage to merge #357 soon. Otherwise, we'll look into this change.

**Comment by elisachisari** [comment]
@joezuntz I'm closing this, as it no longer applies with the merge of #357.
