### ISSUE TITLE
Potential bug in ccl_test_cmblens.c

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#359]
When doing "make check", *if I run ccl_test_correlation_3d.c from the 3dcorrelation branch before or after the CMB lensing benchmark test, I get different results*. However, the order between tests should not matter. The difference is at the power spectrum level already. My suspicion is that the cosmology allocation/de-allocation is not working properly, and hence the second time I try to run ccl_test_correlation_3d.c, I'm somehow inheriting the CMB lensing test cosmology.  (Thanks @ellison-j and @zdu863 for bringing this to our attention.)

**Comment by damonge** [comment]
Fixed by #360
