### ISSUE TITLE
Round-off errors in Omega_l affecting benchmarks

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#368]
If I create the following cosmology in python:
`cosmo_ccl1 = ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, h=0.7, A_s = 2.1e-9, n_s=0.96)`
and then print it, I see that Omega_l is not 0.7 but 0.6999... This is sufficient to make CCL python outputs deviate from the benchmark accuracy, for example, when computing comoving distances. Is there a way we can correct this behaviour even if it requires passing Omega_l directly?

**Comment by tilmantroester** [comment]
According to https://github.com/LSSTDESC/CCL/blob/841a085ef7da5eaf2c90cb28c15caf32a1c05d27/src/ccl_core.c#L260,
Omega_l has contributions from Omega_g and Omega_n_rel, both of which are ~1e-5. Together they make up the difference between the reported Omega_l and 0.7.

**Comment by elisachisari** [comment]
Thanks @tilmantroester. I managed to match the cosmology from the benchmarks better now. I force omega_g to 0 and restore omega_l to the benchmark value. But it still doesn’t fully solve the problem.

**Comment by elisachisari** [comment]
Issue found and solved! The trick is to set up the parameters struct, then correct the cosmological parameters to the ones I want, and only then set up the cosmology. This does the trick and I'm now starting to reproduce benchmark checks in python. Thanks to @reneehlozek who helped with identifying this. See the notebook in the benchmark_notebook branch for more details.
