### ISSUE TITLE
Segmentation fault in cl calculation 

### ISSUE THREAD

**Issue by MarkusMichaelRau** [LSSTDESC/CCL#376]
Hey all, 

first of all thanks for this awesome package, which is one of the most significant contributions to the community in the last years.

I get a segmentation fault when I execute the following code: 
```
import pyccl as ccl
import numpy as np

cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, A_s=1e-10, n_s=0.96, 
                      transfer_function='bbks',  matter_power_spectrum='halofit')

# Define a simple binned galaxy number density curve as a function of redshift
z_n = np.linspace(0., 1., 200)
n = np.ones(z_n.shape)

# Create objects to represent tracers of the weak lensing signal with this
# number density (with has_intrinsic_alignment=False)
lens1 = ccl.ClTracerLensing(cosmo, False, n=(z_n, n))
lens2 = ccl.ClTracerLensing(cosmo, False, n=(z_n, n))

# Calculate the angular cross-spectrum of the two tracers as a function of ell
ell = np.arange(2, 10)
cls = ccl.angular_cl(cosmo, lens1, lens2, ell)
print cls
```
Output: Segmentation fault: 11

My ccl version should be quite new, I installed it about three weeks ago. My operating system is MacOS 10.11.6.

The error appears, if I calculate the angular cl's with a transfer function that doesn't come from class, i.e either 'bbks' or 'eisenstein_hu'. Creating the cosmology object works fine, but calling cl.angular_cl yields this error. The default from Class works fine.

Please let me know if you need more information to track down this bug. 

Best, 

Markus

**Comment by damonge** [comment]
@MarkusMichaelRau . Thanks for reporting this. Note that when using the BBKS or E&H power spectra you should specify sigma8 instead of A_s. Hopefully this will sort out your problem, but we should definitely do better at raising an exception when this happens rather than segfaulting.

**Comment by MarkusMichaelRau** [comment]
This solves the problem thanks!
