### ISSUE TITLE
C libraries remain after python install, even after make uninstall

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#384]
I wanted to report a small issue I was having with the C libraries that someone with the technical know-how may be able to fix very quickly.

If I run: `configure; make; make install` then the C libraries are installed to `/usr/local/lib`. I can then run `make uninstall` and the libraries are removed as I would expect. This is great.

If instead I run `./configure; make; make install` and then do the python install `python setup.py --user --prefix=` (the last bit I am forced to do, as per one of the 'known issues' on the README, not sure if this is related to the problem) and then follow this with `python setup.py uninstall`, `make uninstall` then the C libraries in `/usr/local/lib` are not removed! In order to have them removed I need to first re-run `./configure` and then run `make uninstall`.

My suspicion is that when I do the python install the configure script is automatically re-run and then when I come to `make uninstall` it looks for the installed C libraries in the wrong location. In fact, if I look at the output from the configure script after just running `./configure` then I see `- Prefix:` whereas when it is run as part of the python installation I see `- Prefix: '/Users/Mead/Library/Python/2.7`.

I am doing this all on a Mac using the most recent version of the master branch and the most recent OSx.

To reiterate. This is not really a problem for me since I already have a work around. But it caused me a bit of grief a few days ago and I lost several hours of my life. It would probably be worth fixing if it's easy to do.

**Comment by elisachisari** [comment]
@EiffL Does the new installation (already merged) solve this issue?

**Comment by EiffL** [comment]
@elisachisari yes, this shouldn't be possible anymore
