### ISSUE TITLE
Merge and simplify documentation

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#396]
At the moment, the documentation for CCL is difficult to keep up to date. There are two sets of docstrings: the C docstrings necessary for building the Doxygen files, and the docstrings in the Python wrappers which are merged automatically with the [API page](https://ccl.readthedocs.io/en/readthedocs_development/api/modules.html) on readthedocs. This is fine, since the functions necessarily have to have different signatures and take in different types of arguments. 

However, there are currently issues with the documentation in general.

1. Docstring content is inconsistent between the C docstrings and the Python docstrings. As an example, the contents of the [mass function](https://github.com/LSSTDESC/CCL/blob/master/pyccl/massfunction.py) in Python is different than that of any functions in [ccl_massfunc.c](https://github.com/LSSTDESC/CCL/blob/master/src/ccl_massfunc.c). At a minimum the following should appear in the docstrings regardless of the language: what units are used, what the function *means*, and if necessary a citation (in the case of specific models e.g. cosmic_emu or Halofit).

2. The README.md contents appear in two places, independently. When #321 gets merged it will contain identical content to the README.md. This is obviously problematic because when one gets updated the other will not unless the author remembers, which is unlikely. A common standard is to make the README.md file minimal, with only a list of badges, a brief description, the citation instructions, the license, and a link to the readthedocs page. As an example, see the [emcee](https://github.com/dfm/emcee) front page. This would make the readthedocs page the new standard and be the *only* place that people need to edit when they make changes to the installation instructions.

3. Point to the readthedocs in the GitHub project description (the short blurb at the top of the repository).

4. Create **clear developer instructions** about what to do when adding new featuers. There are really good instructions for the developers right now with regards to how to install and maintain a development build, but no instructions about how to write documentation or unit tests. At this moment, the [CONTRIBUTE.md](https://github.com/LSSTDESC/CCL/blob/master/CONTRIBUTING.md) is out of date with respect to the installation instructions and doesn't say where documentation should be put. When #321 is accepted then it should be made clear that developers should at least add Doxygen readable docstrings to their C code and [Google style](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings to their Python code. Otherwise it will be on other developers to write documentation after the fact (like the situation we are in now...).

**Comment by beckermr** [comment]
I am upping this issue. We have so much dead weight in docs and files. We need one source of truth.

**Comment by elisachisari** [comment]
Closing this as addressed by v2. All our docs are now concentrated in the README and readthedocs.
