### ISSUE TITLE
Incorrect error for sigma8 naming convention

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#399]
I recently got the following error from CCL:
`RuntimeError: Error CCL_ERROR_INCONSISTENT: ccl_power.c: ccl_cosmology_compute_power_emu(): sigma_8 is not defined; specify sigma_8 instead of A_s`

The problem is that the correct parameter name is `sigma8` with no `_`. I could not locate in what file the error message is written. This should be an easy fix.

**Comment by damonge** [comment]
Fixed in #401 . Review should also be easy @tmcclintock  ;-)
