### ISSUE TITLE
CCL can't find CMake

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#404]
@EiffL I have attempted to reinstall CCL using `python setup.py build`, however CCL cannot find my CMake installation.

If I run `brew install cmake` I get the message `Warning: cmake 3.11.4 is already installed and up-to-date`, so CMake is not the issue.

Now, from the CCL directory if I run `python setup.py build` I get a huge list of errors that concludes with:
```
File "setup.py", line 15, in run
    raise Exception("Could not run CMake configuration. Make sure CMake is installed !")
Exception: Could not run CMake configuration. Make sure CMake is installed !
```

The start of the error log contained this:
```
running build
running build_py
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    /Users/tmcclintock/Github/CCL/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)
```
which makes me think that a path is not being updated somewhere. Any thoughts on how to fix this besides a completely fresh install of CCL?

**Comment by tmcclintock** [comment]
Within `CCL/build/` there is no `CMakeFiles` directory. The only two files are `lib.macosx-10.7-x86_64-2.7` and `temp.macosx-10.7-x86_64-2.7`. 

I should mention, this error is occurring only after I tried doing `python setup.py build` before I had CMake installed. So I tried, it failed because CMake wasn't installed. I then installed CMake. I tried again and am getting this long winded error message.

**Comment by EiffL** [comment]
Can you try:
```
$ cd build
$ cmake ..
```
And see what happens ?

**Comment by tmcclintock** [comment]
Top level error:
```
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    /Users/tmcclintock/Github/CCL/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)
```
bottom level:
```
CMake Error at /usr/local/Cellar/cmake/3.11.4/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: /Users/tmcclintock/Github/CCL/build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /Users/tmcclintock/Github/CCL/build/CMakeCache.txt
CMake Error: : System Error: Permission denied
```

**Comment by tmcclintock** [comment]
This appears to be a Mac OS X issue. I'm going to close this, but for future reference the safest thing to do is make sure all dependencies (CMake, SWIG) are fully installed. This can help generate more useful messages during compilation.
