### ISSUE TITLE
Instructions run too many tests/the slow tests

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#405]
In three places, the instructions for installing CCL call for the user to run too many tests and/or tests that are too slow and should only be run on TravisCI. This includes any spot that directs the user to run `python setup.py test` including:
- the [README](https://github.com/LSSTDESC/CCL)
- the [readthedocs install page](http://ccl.readthedocs.io/en/readthedocs_development/source/installation.html)
- the [readthedocs install for developers page](http://ccl.readthedocs.io/en/readthedocs_development/source/installation_for_developers.html)

These should be updated to just include directions on how to run the nosetests (which I'm not sure how to run independently). This should be a very simple fix.

**Comment by beckermr** [comment]
fixed - tests are very fast now
