### ISSUE TITLE
Add 3D halo density profiles

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#407]
This issue serves as instructions for a hack day project at CMU.

Halo density profiles are necessary components for many cluster analyses. In DESC, they will form the backbone of cluster mass calibrations, for instance. At the moment, Fourier space halo profiles are implemented in the [halo model branch](https://github.com/LSSTDESC/CCL/pull/339), but these are not useful for the purposes of modeling clusters.

3D halo profiles are easy to implement and represent good hack day projects at CMU. In order of increasing difficulty, we could implement:
- [x] [NFW profile](https://en.wikipedia.org/wiki/Navarro%E2%80%93Frenk%E2%80%93White_profile)
- [x] [Hernquist profile](http://articles.adsabs.harvard.edu/pdf/1990ApJ...356..359H) rho(r) = rho_s/[(r/rs)*(1+r/rs)^3]
- [x] [Einasto profile](https://arxiv.org/abs/1401.1216) (second line in eq. 4)
- [ ] [Hayashi & White profile](https://arxiv.org/abs/0709.3933) (eqs. 5, 6, 7)
- [ ] [Diemer & Kravtsov profile](https://arxiv.org/abs/1401.1216) (all of eq. 4)

All four of the profiles mentioned above can either be implemented in a few lines (NFW, Einasto) or can be built from already existing splines computed within CCL (e.g. halo bias + matter correlation function for H&W).

**Comment by philbull** [comment]
A couple of points copied from Slack:
 (1) I think it would be best to keep the halo profiels in the same namespace as the other halo model stuff (which doesn't necessarily mean the same source file).
 (2) I think it would be good to support user-defined profiles instead of collecting a large library of particular profiles. The list of four mentioned above seem like a reasonable set of "built-in" ones to me, though.

**Comment by elisachisari** [comment]
Parallel hacks will take place for [SACC](url
https://github.com/LSSTDESC/sacc) and for [TJPCosmo](https://github.com/LSSTDESC/TJPCosmo) to ensure cluster number counts and lensing are integrated to the full combined probes pipeline. We should make sure all of this happens smoothly @empEvil @damonge.

**Comment by KuanWang-Astro** [comment]
I don't think Hayashi & White proposed a new halo profile. From what I understand from the paper, they describe the halo-matter correlation using the Einasto profile as the 1-halo term.

**Comment by elisachisari** [comment]
Three of the five options above have been integrated into CCL. Do we need to include the other two? @cavestruz @tmcclintock

**Comment by tmcclintock** [comment]
It depends on what people are going to use CCL for. The three implemented profiles are all 1-halo terms. The other two I listed include 2-halo terms. If someone wanted to model the lensing around a single cluster, then they probably only need a 1-halo term. If they do a stacked analysis then they will need a 2-halo term. That being said, I'm fine with this issue being closed since this is a very low-priority topic, I think.

**Comment by elisachisari** [comment]
We discussed this with @cavestruz and for now NFW is all that is needed. We will therefore close this issue and re-open it if in the future we find need for more options.
