### ISSUE TITLE
Ability to specify which version of Python to build against

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/CCL#416]
@j-dr and @damonge ran into an issue recently which has to do with selecting the correct python interpreter. Right now the install script uses whichever interpreter is returned when running `python` to identify the target interpreter. This is robust and should cover the majority of use cases, however sometimes people want to be able to explicitly use another command, like `python3` or `python2`. 
We can do that by having CMake check for a particular command line flag and making sure the python setup.py sends that flag to cmake.

**Comment by villarrealas** [comment]
Closed as we are depreciating Python2 support.
