### ISSUE TITLE
Missing CLASS files trigger GSL warning mechanism

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#417]
In a previous version of our `pip install pyccl`, missing CLASS files were triggering a chain of errors which got caught by the GSL warning mechanism, instead of being transmitted as a CLASS error. While the issue with missing CLASS files has been solved in (see #397), we need to make sure that we are passing the errors around correctly.

**Comment by beckermr** [comment]
I think I am getting this issue when trying to pip install into a conda environment. Has anyone else experienced this?

**Comment by beckermr** [comment]
I figured this out. See issue #461
