### ISSUE TITLE
Running only specific tests

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#421]
Is it possible to only run specific tests when doing development work? For example, a situation I have commonly found myself in is that I am only editing one specific .c file and I can be fairly confident that my meddling will only be having an effect on a few tests. It would be nice to be able to run these specific tests quickly, rather than having to go through the full test suite every time using `check_ccl`, which takes 140s on my laptop. 

It might be that this is just a documentation issue, and there already is an easy way to do this. Or that there is a way to do this and it is so simple that I am the only one not able to do it...

**Comment by tilmantroester** [comment]
You can specify the group of tests that are run, e.g., `check_ccl cls`, which cuts down the number of tests by a lot. I don't know how to run a single test though.

**Comment by alexander-mead** [comment]
Ah, yes, that works and is exactly what I wanted. Is this documented anywhere? If not, maybe it should be. Otherwise this can be closed.

**Comment by elisachisari** [comment]
Now documented in the README.
