### ISSUE TITLE
Development workflow for C

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#422]
I had a few questions recently about what exactly I should be doing when developing the C code. I couldn't find the answers I was looking for in the README and feel it could do with a few extra lines. The things confusing me were:

(1) Do I need to `make install` every time I want to run tests and see if my changes are okay? I think I can just run `make` and then run the tests, but this relies on CCL being installed (`make install` having been run previously), and me not having run `make uninstall`. Anyway, it's not clear exactly what to do from the documentation... maybe this is just my ignorance though.

(2) In the README it says to run `check_ccl` from the CCL root directory, but I have to run `build/check_ccl`. Actually @EiffL pointed out that `check_ccl` gets put into `usr/local/bin`, but this isn't visible until I update my PATH.

(3) If I run `check_ccl` from the `build` directory then the tests run okay until test 9, when it fails. This is a bit confusing.

(4) If I uninstall using `make uninstall` and then run the tests from the CCL root directory using `build/check_ccl` the tests run okay until test 39, when it fails with a CLASS BBN file error. This is a bit confusing.

**Comment by elisachisari** [comment]
Re: (3), I think this is because it can't find the path to the benchmark files it's supposed to read. It works when you run from the CCL root directory.

**Comment by elisachisari** [comment]
I'm running into (4) as well and could only overcome by actually running `make install` which I think it's not suggested in the development option.

**Comment by rainwoodman** [comment]
If possible I think we shall avoid requiring running make install for running tests. 

What are the benchmark files @elisachisari referred to?

**Comment by beckermr** [comment]
New docs answered this issue I think. I am closing for now. Feel free to reopen!
