### ISSUE TITLE
Typo in "Lensing angular power spectrum" example notebook

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/CCL#425]
@cwwalter highlighted a typo in the [Lensing angular power spectrum](https://github.com/LSSTDESC/CCL/blob/master/examples/Lensing%20angular%20power%20spectrum.ipynb) at cell 7 which crashes the python kernel with following error:
```
Assertion failed: (nz_ba == nba), function cl_tracer_new_wrapper, file /private/var/folders/4t/66c5hggs5_1f191_9f2dljh80000gn/T/pip-build-w625qxgq/pyccl/build/pyccl/cclPYTHON_wrap.c, line 4184.
```
it looks to me that it's only a typo and that cell 7 should use `bias_ia2` in the call to `ccl.ClTracerLensing`.

**Comment by rmjarvis** [comment]
I would add that you should be checking for whatever caused the assertion error in the C layer at the python layer and raise a suitable exception.  Crashing the python kernel is bad form.

Indeed this typo is probably a good unit test to add with `assert_raises`.

**Comment by beckermr** [comment]
Ahhh. This is fixed in the CR 1 Installment PR I have open now. Sorry for the confusion on my end @rmjarvis.

**Comment by beckermr** [comment]
Update: It is not fixed in the PR above. I have made a new issue on #479 to address these asserts.
