### ISSUE TITLE
UnicodeDecodeError when printing Cosmology in python 3

### ISSUE THREAD

**Issue by rmjarvis** [LSSTDESC/CCL#427]
In running @elisachisari's example 1 for her DE School lesson, I'm getting the following error when doing `print(cosmo_field)`:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-549953e78c26> in <module>()
----> 1 print(cosmo_fid)

~/anaconda3/lib/python3.6/site-packages/pyccl-0.3.5-py3.6.egg/pyccl/core.py in __str__(self)
    512 
    513         # String from internal CCL status
--> 514         status_str = self.status()
    515 
    516         # Return composite string

~/anaconda3/lib/python3.6/site-packages/pyccl-0.3.5-py3.6.egg/pyccl/core.py in status(self)
    607 
    608         # Get status message
--> 609         msg = self.cosmo.status_message
    610 
    611         # Return status information

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: invalid continuation byte
```
This is using the tag 0.3.5 (current master when I installed it).

**Comment by rainwoodman** [comment]
I suspect this has something to do with the status_message become corrupted due to memory issues. 

What about forcing the lower level swig binding to use byte strings? It would help debugging these issues. The information here may be relevant:

http://www.swig.org/Doc3.0/Python.html#Python_nn77

**Comment by beckermr** [comment]
We have changed the printing of the Cosmology struct and I have not seen this error. Are we good to close this @rmjarvis ?

**Comment by rmjarvis** [comment]
Probably, but I haven't tried it again with the master branch.  It's probably fine to close it without prejudice, and if it crops up again for someone, they can reopen it.
