### ISSUE TITLE
Generalize tracers

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#430]
We need to generalize tracers in CCL such that they can take, for example, non-linear biases. This is needed for [TJPCosmo](https://github.com/LSSTDESC/TJPCosmo).

**Comment by damonge** [comment]
Should we close this @elisachisari ?

**Comment by c-d-leonard** [comment]
@damonge @elisachisari bumping the question of whether we can close this?

**Comment by damonge** [comment]
Yes, let's close it
