### ISSUE TITLE
N(z) not normalized for ClTracerNumberCounts

### ISSUE THREAD

**Issue by wagoner47** [LSSTDESC/CCL#431]
I didn't see this in an issue yet, so I apologize if it's already an open issue. I was trying to get power spectra for HSC, and was noticing some very large values (see first plot). I tried a few things, and settled on the N(z) being the issue. When I plot the N(z) from pyccl against the raw N(z) divided by the sum of all N(z) values, I noticed a difference (see second plot). I just thought I should flag this, since it says that the N(z) will be normalized.

![funny_cls](https://user-images.githubusercontent.com/11187527/43339751-38498bec-91a8-11e8-9a14-911b8b30c7be.png)

![n_of_zs](https://user-images.githubusercontent.com/11187527/43339823-6d47a9a0-91a8-11e8-8780-25a2adc1cd73.png)

**Comment by wagoner47** [comment]
Actually, it looks like it’s just that the order of redshift, N(z), and bias might be different between the NumberCounts tracer class and it’s parent class, which I didn’t realize.

**Comment by damonge** [comment]
I'll close this, since we realized it was due to us using an outdated script.
