### ISSUE TITLE
Enable linear-theory-only Cells and angular correlation functions

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#438]
At the moment, we have it hard-coded that we use ccl_nonlin_matter_power for the power spectra required to get the C_ells and hence the angular correlation functions. However, there are use cases where we might want to compute these observables in linear theory only (e.g. in combination with modified gravity models where we don't have good models for nonlinear behaviour). It would be good to add an option to compute things other than just the power spectrum with linear theory only.

**Comment by jablazek** [comment]
+1. This should be a standard option in addition to the mode general (user generated) option that @damonge is working on.

**Comment by damonge** [comment]
@c-d-leonard Agreed regarding @jablazek 's statement. However, note that this is already possible, you just have to select the linear power spectrum as your choice of non-linear power spectrum (matter_power_spectrum='linear', instead of e.g. 'halofit')

**Comment by jablazek** [comment]
@damonge @c-d-leonard : given this existing capability, is this issue already resolved?

**Comment by c-d-leonard** [comment]
I think the existing capability solves the issue as I was thinking about it, thanks for reminding me of that.
I'll close this issue.
