### ISSUE TITLE
Error when running C tests within development workflow

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#439]
If I am using the C library development workflow (which means I don't install the library, only build locally) and then run the tests with build/check_ccl, the tests fail on number 39, corrs_3d:model 3 with error: 'ERROR 1032: ccl_power.c: ccl_cosmology_compute_power_class(): Error running CLASS thermodynamics:thermodynamics_init(L:304) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:1143) :could not open fA with name /usr/local/share/ccl/bbn/sBBN_2017.dat and mode "r" '

This is because the test is not finding the local CLASS. You can solve this problem by doing 

export CLASS_PARAM_DIR=your_ccl_path/CCL/build/extern/share/class/ 

each time you run the tests in a new terminal instance, but it would be good to have a more permanent fix or at least add this to the readme.

**Comment by rainwoodman** [comment]
Is this still occuring?

What is your `CLASS_PARAM_DIR` before you modify the enviroment?

CCL is built against its own CLASS library, and I would have thought it would have preferred a hard-coded path of the class data files.

**Comment by beckermr** [comment]
fixed
