### ISSUE TITLE
Updates needed to CCL Note

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#443]
I reviewed the current status of the CCL note in master branch for any glaringly out of date aspects. Here's what I found:

- Author list may need updating
- Abstract says "These routines have been validated to an accuracy level, documented here, against the results of the Code Comparison Project.", but for most of our code base we do not validate against Code Comparison Project anymore.
- The functionality listed in the abstract no longer reflects everything we have.
- The version number of the release mentioned in the abstract is not up to date (most recent release is 0.3.5)
- The installation procedure documented in Section 2 is totally out of date (does not describe Francois' updated procedure).
- Physical constants may need updating?
- method for splitting sum of neutrino masses into appropriate 3 masses needs updating (my job, sorry)
- neutrino cosmologies tests description in Section 4 needs to be updated (@tilmantroester )
- the python installation procedure in Section 5 is probably also out of date
- there may be some updates needed to the comments about when swig is run in Section 6
- Section 7 says the link to angpow is still work in progress
- We may want to update the Citing CCL section to reference the paper when available.
- Contributions could probably all do with a bit of updating.

**Comment by villarrealas** [comment]
Relevant to the author list: what is the procedure for authors changing institution on the DESC Note? Should it just contain the most recent institutional data or all institutions during CCL development? i bring this up because the DESC Note feels like more of an evolving document than something locked on submission like the paper.

**Comment by elisachisari** [comment]
@c-d-leonard The constants are updated but in the paper branch unfortunately. They will merge when we merge that branch.
@villarrealas I would list your current institution and I would check this is up-to-date every time you add a new feature to CCL & the note. I added some lines in CONTRIBUTING to clarify this.

**Comment by elisachisari** [comment]
Abstract, functionality, version umber, installation, angpow mention - all fixed. After updates from @c-d-leonard and @tilmantroester, and everyone updating their contribution, we should be ready for a review.
@EiffL could you check you are happy with the new installation sections?

**Comment by elisachisari** [comment]
Fixed that last point
