### ISSUE TITLE
Power spectrum normalisation accuracy

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#445]
The following code:

```
import pyccl as ccl

sigma8=0.8
cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, sigma8=sigma8, n_s=0.96)

print(ccl.sigma8(cosmo))
```

prints out: 0.7998469805666433

This seems a bit strange to me. I would have thought it would be exactly 0.8. Is this a problem?

**Comment by elisachisari** [comment]
When we provide sigma8 for a cosmology that calls CLASS, there is a shooting method that looks for the corresponding A_s value (which is what CLASS really takes as input). From this, I gather that perhaps we should improve on the precision of that method. Pinging @elikrause to comment on this.

**Comment by elikrause** [comment]
To run CLASS, CCL computes an approximate A_s for the input sigma8 in the routine ccl_get_class_As in ccl_power.c:
A first guess A_s_guess = 2.43e-9/0.87659*sigma8 is computed based on a reference point (sigma8_ref = 0.87659), as in the shooting method within CLASS. As the mapping between sigma8 and A_s depends on all cosmology parameters, this is only very approximate.
Then we run CLASS (with low k_max, to reduce computing time), compute sigma_8 for this run (saved in sp.sigma8), and rescale A_s_guess*=pow(sigma8/sp.sigma8,2.).
If this is not accurate enough, we could repeat the second step + rescaling once more; however, this then requires three CLASS runs (with varying A_s) for a given point in parameter space... hence, it should be accompanied by a warning that sigma_8 should not be used as a sampling parameter if CLASS is used.

**Comment by elikrause** [comment]
That might work iff we don't get the non-linear power spectrum from the same CLASS run.
I am not sure whether that method has been deprecated.
