### ISSUE TITLE
 Benchmark_Comparisons.ipynb crashes in halo_model cell with python2

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#447]
I get a crash in the penultimate cell of Benchmark_Comparisons.ipynb (the one titled 'Halo Model Plots') when running the notebook with a python2 kernel. The crash is a severe kernel crash. The error is attached:

[Crash_information.txt](https://github.com/LSSTDESC/CCL/files/2354726/Crash_information.txt)

Tilman says that the crash is in the spline being called by the growth factor within the Eisenstein & Hu P(k) approximation:

```
Thread 0 Crashed:: ZMQbg/1  Dispatch queue: com.apple.main-thread
0   libgsl.23.dylib                   0x0000000108ca3f60 gsl_spline_eval_e + 10
1   _ccllib.so                        0x0000000108999d44 ccl_growth_factor + 84
2   _ccllib.so                        0x00000001089a4643 ccl_cosmology_compute_power_eh + 4323
3   ???                               0x00007f87fdc7ad60 0 + 140222055034208
```

I am using gsl 2.4, but upgraded to 2.5 and the problem persists.

**Comment by tilmantroester** [comment]
One thing to check is to set `ccl.debug_mode(True)` at the beginning of the halomodel cell and then check the output in the terminal the notebook is running in.

**Comment by alexander-mead** [comment]
When I do this I get a halo-model specific error in the terminal from the C:

`ERROR 1047: ccl_halomod.c: halo_concentration(): Duffy (2008) virial concentration only valid for virial Delta_v or 200`

**Comment by alexander-mead** [comment]
I'm worried that this might be because I have an IF statement check in the Duffy (2008) halo concentration for a number (odelta) to be exactly equal to the float 200. I guess it could be that numerical rounding changes this from 200 to 200+epsilon and then this causes an error.

**Comment by alexander-mead** [comment]
If I check the halo concentration routine directly it crashes nicely in the python when I give it an unsupported `odelta`:

```
import numpy as np
import pyccl as ccl
import pylab as plt
%matplotlib inline

cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, sigma8=0.8, n_s=0.96, Neff=3.04,
                      transfer_function='class',
                      matter_power_spectrum='halofit',
                      mass_function='shethtormen',
                      halo_concentration='duffy2008'
                     )

mmin=1e10
mmax=1e16
nm=101

m=np.logspace(np.log10(mmin),np.log10(mmax),nm)
a=1.

c=ccl.halo_concentration(cosmo,m,a,odelta=201.)
```

**Comment by villarrealas** [comment]
This all works on Python3. Since we are depreciating Python 2.7.x support, this is now being closed.
