### ISSUE TITLE
Test 71 fails: Error computing CLASS power spectrum

### ISSUE THREAD

**Issue by msyriac** [LSSTDESC/CCL#454]
I'm following the Development Workflow instructions. I get no errors during compilation.

The following is the output of `build/check_ccl`

```
TEST 62/80 corrs:analytic_bessel 0.000000 % [OK]
TEST 63/80 corrs:analytic_fftlog 0.000000 % [OK]
TEST 64/80 corrs_3d:model_3 [OK]
TEST 65/80 corrs_3d:model_2 [OK]
TEST 66/80 corrs_3d:model_1 [OK]
TEST 67/80 bcm:model_1 [OK]
TEST 68/80 emu:model_1 [OK]
TEST 69/80 emu_nu:model_1 [OK]
TEST 70/80 power_nu_nl:model_3 [OK]
TEST 71/80 power_nu_nl:model_2 ERROR 1032: ccl_power.c: ccl_cosmology_compute_power_class(): Error computing CLASS power spectrum
```

Any ideas why this test fails?

**Comment by c-d-leonard** [comment]
@EiffL @msyriac , I am not reproducing this behaviour and I'm not sure where it's from. What I can say is that I had similar issues if I tried to use the development workflow without ever installing the library. Apparently you have to install once to set certain environment variables, so if you just follow the development workflow right off the bat you can have issues. I think we should document this more carefully in the readme.

**Comment by philbull** [comment]
Could this be related to issue #518?

**Comment by beckermr** [comment]
fixed
