### ISSUE TITLE
change python package to `ccl` from `pyccl`

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#465]
This was brought up by @rmjarvis because most imports look like 

```
import pyccl as ccl
```

**Comment by beckermr** [comment]
We've had a lot of discussion on this. The general consensus was that we did not want to do this. @rmjarvis did mention keeping `pyccl` as the pypi name but calling the module `ccl`. This option did not get as much attention. 

Do we have any more thoughts on this? @elisachisari @damonge @c-d-leonard @tmcclintock @philbull 

If not, I am going to close this issue.

**Comment by beckermr** [comment]
To be clear, the proposal is that the following would be the standard.

`pip install pyccl`
'import ccl`

**Comment by rmjarvis** [comment]
In particular, I recommend that if you don't change it, then your tutorials and examples probably shouldn't always do `import pyccl as ccl`.  IMO, if you want to typically refer to the module as `ccl` in python, then you should just call it `ccl`, rather than `pyccl`.

**Comment by beckermr** [comment]
Does anyone have comments here? 

I agree with Mike on this point.

**Comment by tmcclintock** [comment]
I also agree with Mike.

**Comment by elisachisari** [comment]
We made a decision to leave this as is.
