### ISSUE TITLE
pragma once is not supported by Cray C compiler

### ISSUE THREAD

**Issue by rainwoodman** [LSSTDESC/CCL#466]
https://en.wikipedia.org/wiki/Pragma_once#cite_note-9 

I strongly suggest we get rid of these. I can sort this out as part of the include / cross object dependency clean up.

**Comment by beckermr** [comment]
Looks like we just need the standard include guard. What do you mean by cross-object dependency clean up?

**Comment by rainwoodman** [comment]
I meant some object files refer ro symbols and types in other obj files.
This information is currently descibed in both the header files and the c
files, and the description seemed to be incomplete hence the need to
multiple include a file.

I filed a PR to linearize most of this dependency in ccl.h. The include
sections look leaner after this.

**Comment by rainwoodman** [comment]
Fxied in #467
