### ISSUE TITLE
one and only one way to do things

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#472]
Right now the python interface has a lot of arguments that are redundant, polymorphic, or multiple ways to do the same thing. This is a lot of work to maintain and makes the API more confusing. Let's simplify and save ourselves headaches down the road.

For example,

```python
tracer_types = {
    'nc':               const.CL_TRACER_NC,
    'number_count':     const.CL_TRACER_NC,
    'wl':               const.CL_TRACER_WL,
    'lensing':          const.CL_TRACER_WL,
    'weak_lensing':     const.CL_TRACER_WL,
    'cmbl':             const.CL_TRACER_CL,
    'cmb_lensing':      const.CL_TRACER_CL,
}
```

We don't need to maintain all of the different options above and it is easier for people to remember one thing instead of having to guess which variants of 'weak_lensing' are allowed.

Other things I am seeing along these lines:

1. We probably should force users to specify the array of redshifts separately for each aspect of a tracer.
2. ~We should force people to make a `Parameters` object or just roll all of that functionality into the `Cosmology` object. I vote for the latter actually.~ (done)
3. The `has_magnification` and `mag_bias` keyword arguments are redundant. 
4. The `has_intrinsic_alignment` keyword can be inferred from the other settings on the tracer object.

**Comment by rainwoodman** [comment]
Point 2 reminds me that if we insist on passing in cosmology objects as input variables, then there is no clear way for one to efficiently compute a function over several cosmology parameters, even in the cases where the vectorization can be relayed to the C layer. (look at the vectorization functions in pyutils.py)

**Comment by beckermr** [comment]
I am addressing part of this issue now (combining the parameters and cosmology objects into a single thing).
