### ISSUE TITLE
make sure python layer only access the `Cosmology` object

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#475]
@rmjarvis pointed out that the python layer should only access the python object, not the C counterpart.

**Comment by rainwoodman** [comment]
I see. It smells like one just need to change the documentation, since the current code does pass all of the tests like these:

https://github.com/LSSTDESC/CCL/blob/master/tests/ccl_test_growth.py#L73

**Comment by rmjarvis** [comment]
Right.  That's my expectation.  But I don't think I followed everything through to make sure of that.

**Comment by beckermr** [comment]
We shouldn’t wait on this issue until I merge my stuff from cr 1. Otherwise the conflicts will be annoying.

**Comment by beckermr** [comment]
We we should wait. Autocorrect

**Comment by beckermr** [comment]
OK. It looks like `pyccl` allows both. When you call any of the `_vectorize_fnXYZ` functions, they pass the input cosmo to `_cosmology_obj` which reads:

```python
def _cosmology_obj(cosmo):
    """Returns a ccl_cosmology object, given an input object which may be
    ccl_cosmology, the Cosmology wrapper class, or an invalid type.

    Args:
        cosmo (ccl_cosmology or Cosmology): The input cosmology which gets
                                            converted to a ccl_cosmology.

    """
    if isinstance(cosmo, lib.cosmology):
        return cosmo
    elif isinstance(cosmo, Cosmology):
        return cosmo.cosmo
    else:
        raise TypeError("Invalid Cosmology or ccl_cosmology object.")
```

This is how the C object gets passed to the C layer.

IDK if the first branch is ever used FWIW.

**Comment by beckermr** [comment]
Actual code test:

```
In [7]: c = pyccl.Cosmology(sigma8=0.8, Omega_c=0.25, Omega_b=0.05, h=0.7, n_s=0.95)                                                                                                                    

In [8]: c.cosmo                                                                                                                                                                                         
Out[8]: <pyccl.ccllib.cosmology; proxy of <Swig Object of type 'ccl_cosmology *' at 0x11878d5d0> >

In [9]: pyccl.growth_factor(c, 1.0)                                                                                                                                                                     
Out[9]: 1.0

In [10]: pyccl.growth_factor(c, 0.5)                                                                                                                                                                    
Out[10]: 0.6118543092306038

In [11]: pyccl.growth_factor(c.cosmo, 0.5)                                                                                                                                                              
Out[11]: 0.6118543092306038
```

**Comment by beckermr** [comment]
So given this, I think we can close this issue and move on. We could raise an error here to force users to only use the python object, but IMHO if users want to shoot themselves in the foot, there is not a lot we can do to stop it.

I check the source and the docs have all been changed.

Thoughts @rmjarvis ?

**Comment by rmjarvis** [comment]
Personally, I would remove the option to accept a lib.cosmology instance in these functions.  One, obvious way is part of the python mantra.  Sometimes there are good reasons to have two ways, but this doesn't seem like one of them.

**Comment by beckermr** [comment]
Sure. Will do!
