### ISSUE TITLE
faster test suite

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#477]
The test suite is pretty slow right now. @rmjarvis suggested a hack from GalSim [here](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206374547) and [here](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206374656).

**Comment by tmcclintock** [comment]
For reference, the tests ran with `build/check_ccl` take much less time than `python setup.py test`. Not sure why though.
