### ISSUE TITLE
document/update LSST spec module

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#478]
We had some pretty extensive rewrites suggested by @rmjarvis for the `lsst_spec` module. The original comments are here:

- [user photo-z functions](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206142442)
- [documentation on the bias model](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206151766)
- [documentation on the photo-z classes](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206309899)
- [documentation question for photo-z's](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206313283)
- [general comments](https://github.com/LSSTDESC/CCL/pull/433#discussion_r206313036)

My personal feeling on this is that users can make all of these models themselves using other code in the library. Thus we should just `rm -rf` the module so we don't have to maintain it.

**Comment by beckermr** [comment]
Yeah I vote to deprecate lsst-spec and merge everything in a single namespace. I also prefer underscores to dashes. :p

**Comment by elisachisari** [comment]
I'm not very keen on deprecating lsst-spec. Though it might not feature very prominently in the paper, we are using it *a lot* to set up usage examples both in C and python. I looked over Mike's questions on the lsst-spec module (linked above) and I think we can easily answer the documentation questions.

**Comment by elisachisari** [comment]
Both emu17 and halomod are tightly coupled with power. They provide some routines that are then called by the matter power spectrum function depending on what "method" you choose.

**Comment by beckermr** [comment]
OK @elisachisari. I am closing this issue then. :)

**Comment by beckermr** [comment]
Ack. Reopening and renaming for address the comments!

**Comment by beckermr** [comment]
@c-d-leonard I think you are working on part or all of this issue?

**Comment by elisachisari** [comment]
We agreed to revisit when #526 is merged. LSST-specs discussion superseded by #528. Untagging for v1, but we will revisit.

**Comment by beckermr** [comment]
I am closing this issue for now. We can open another issues for further decoupling of CCL code and power spectrum models.
