### ISSUE TITLE
Generalized Limber integrator

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#511]
OK, so to get the angular power spectrum between two projected fields a and b, in the Limber approximation you need to integrate:
![codecogseqn](https://user-images.githubusercontent.com/8809493/47445411-c12d7d80-d7b0-11e8-8db5-31218e6f8f24.gif)
where the Deltas are "transfer functions" associated with each projected field (basically think of them as their radial kernels) and P_ab is the 3D power spectrum between whatever 3D quantities a and b are related to.

The idea would be to do the following:
- [x] Create a generalized power spectrum structure that represents the P_ab above.
- [ ] Create a generalized transfer function structure that represents the Deltas. This will be a generalization of the ClTracer structures we currently have.
- [ ] Implement typical use cases in CCL for both structures and ways for users to set those from python.

This is based on discussions with @elikrause , @jablazek and @tilmantroester during the Edinburgh sprint week, and they can add more info here.

**Comment by jablazek** [comment]
This looks correct to me. my guess is that there are a finite number of Deltas that will appear, except it very strange situations. Of course, allowing that to be general as well is helpful.

**Comment by damonge** [comment]
@jablazek @elikrause @tilmantroester I've had a first stab at point number 1 above in PR #526 
Have a look there and let me know what you think.

**Comment by damonge** [comment]
Part 1 of this just got merged
