### ISSUE TITLE
Passing bias=None to NumberCountsTracer crashed python kernel

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/CCL#512]
This snippet crashes my python kernel (python 3.6, CCL master):

```import numpy as np
import pyccl as ccl

ccl_cosmo = ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, h=0.7, n_s=1.0, sigma8=0.8)

z = np.linspace(0, 4, 100)
nofz = np.exp(-0.5*(z-0.3)**2/0.15**2)
nc_tracer = ccl.NumberCountsTracer(cosmo=ccl_cosmo, dndz=(z,nofz), bias=None, has_rsd=False)
```

`bias` is currently a required argument, contrary to the documentation.

**Comment by beckermr** [comment]
Ack. My bad. Putting in a patch now.

**Comment by beckermr** [comment]
So the bias is required. I changed the docs.

**Comment by beckermr** [comment]
The fact that the interpreter crashes is fun.

**Comment by beckermr** [comment]
You have to pass the bias. None is. I longer listed as a valid value. We can do more error checking I suppose but I don’t think we can account for everything. Happy to discuss more.

**Comment by tilmantroester** [comment]
If passing `None` (or something else) crashes the interpreter, that should probably be caught.

**Comment by beckermr** [comment]
Sure. Feel free to make a PR. I won't be able to get to it.

**Comment by rmjarvis** [comment]
If something crashes the interpreter, you definitely want to check for that in python before calling the SWIG-ed C function.  That should really never happen.
