### ISSUE TITLE
Intermittent failure to compute CLASS power spectrum

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#518]
CCL intermittently fails to compute the power spectrum using CLASS. This occurs for some sets of parameters and not others, and also seems to happen on some machines/architectures and not others. This issue tends to produce the following error messages:

```c
raise CCLError("Error %s: %s" % (error_types[status], msg))
pyccl.errors.CCLError: Error CCL_ERROR_CLASS: ccl_power.c: ccl_cosmology_compute_power_class(): Error running CLASS spectra:spectra_init(L:1307) :error in spectra_pk(pba,ppt,ppm,pnl,psp);
=>spectra_pk(L:2795) :error in spectra_sigma(pba,ppm,psp,8./pba->h,0.,&(psp->sigma8));
=>spectra_sigma(L:2887) :error in spectra_pk_at_k_and_z(pba,ppm,psp,k,z,&pk,pk_ic);
=>spectra_pk_at_k_and_z(L:699) :error in spectra_pk_at_z(pba, psp, logarithmic, z, spectrum_at_z, spectrum_at_z_ic);
=>spectra_pk_at_z(L:429) :error in array_interpol
```

Note that this error message is truncated, as the CLASS error message buffer seems to be too small to hold the whole thing.

The cause of this problem is a very small rounding error in the interpolation routines inside CLASS. When a z=0 power spectrum is requested, a slight rounding error in the conversion from redshift to conformal time tau causes a tau value to be requested from the 2D power spectrum spline that is very slightly larger than the maximum tau, which leads to this error.

Recent versions of CLASS apply a small correction at z=0 to avoid this issue; see [this CLASS commit](https://github.com/lesgourg/class_public/commit/8bd805102bca8fe06764d24db83ce4a1b26e4278) for more info.

The solution is to update CCL to depend on version 2.7.0 of CLASS or higher. Unfortunately the CLASS API seems to have changed since 2.6.x.

**Comment by philbull** [comment]
Even with this patch, we might run into rounding errors at z=0. To fix this, we can add a very small correction to the redshift passed to the CLASS power spectrum routines in `ccl_power.c`, e.g.

```c
newstatus |= spectra_pk_nl_at_k_and_z(&ba, &pm, &sp,exp(x[i]),1./a[j]-1.+1e-10,&psout_nl);
```
(There are 3 affected instances of this call.)

**Comment by beckermr** [comment]
I put in a PR for this.
