### ISSUE TITLE
Paths not properly escaped somewhere in CMake build tools

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#523]
We have a user who has a space character in their username(!). They get weird build system failures at the CLASS compilation step, presumably due to the space not being properly escaped in one of the paths. We should track down where this escape failure is.

**Comment by EiffL** [comment]
@philbull Can we have that user submit their entire CMake log when trying to build CCL?

**Comment by philbull** [comment]
Sure, I will ask.

**Comment by elisachisari** [comment]
With the new v2 installation this is likely deprecated. Closing this for now.
