### ISSUE TITLE
Problem with python3 install

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#541]
I am currently having trouble installing `pyccl` using `python3`, but it works fine with `python2`. I feel that this is probably a problem with my `python`, rather than with `ccl`, but I figured I'd open an issue and hope that someone took pity on me:

If I do: 

`python2 setup.py install`, then leave the `ccl` directory and then do `python2 -c 'import pyccl'` I get no errors and everything works fine.

However, if I do:

`python3 setup.py install`, then leave the `ccl` directory and then do `python3 -c 'import pyccl'` I get `ModuleNotFoundError: No module named '_ccllib'`. So, it certainly installs and is able to find the library, but for some reason it doesn't work. The full error is below. Any help would be much appreciated.

```
Mead:Mead/Physics> python3 -c 'import pyccl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/ccllib.py", line 20, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/_ccllib.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/_ccllib.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/_ccllib.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/__init__.py", line 21, in <module>
    from . import ccllib as lib
  File "/usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/ccllib.py", line 23, in <module>
    _ccllib = swig_import_helper()
  File "/usr/local/lib/python3.7/site-packages/pyccl-1.0.1.dev2+g2b4f3cf2-py3.7.egg/pyccl/ccllib.py", line 22, in swig_import_helper
    return importlib.import_module('_ccllib')
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ccllib'
```

**Comment by damonge** [comment]
@alexander-mead  I think what's happening is as follows: even if you run `python3 setup.py install`, the script will install ccl as if you were running `python setup.py install`. I.e. it uses whatever version of python the command `python` corresponds to. I imagine in your case this is python2?

If that's what's happening, I've encountered this in the past, and it's an issue that I hope can be resolved in the future.

**Comment by damonge** [comment]
BTW, to solve it I had to brute-force make `python` point to my `python3` (I tried making a symlink, but that didn't work, for some reason)

**Comment by alexander-mead** [comment]
@damonge you are right that my `python` points to `python2`. I made an alias so that `python` now points to `python3`, but that did not help. I got exactly the same problem. Let me know if you have any other ideas.

**Comment by damonge** [comment]
I literally did the following:
```
sudo mv /usr/bin/python /usr/bin/pythonb
sudo cp /usr/bin/python3 /usr/bin/python
python setup.py install
sudo mv /usr/bin/pythonb /usr/bin/python
```

**Comment by alexander-mead** [comment]
Ah, that worked! How ridiculous.

**Comment by alexander-mead** [comment]
Okay, on my Mac the default `python` is certainly `python2`. I wanted to install `ccl` for `python3`, which is how I ran into this problem. I don't know how to change the default `python` on my Mac.

**Comment by EiffL** [comment]
Ok, so the way to go about this, it to tweak the [FindPythonLibsNew.cmake](https://github.com/LSSTDESC/CCL/blob/master/cmake/Modules/FindPythonLibsNew.cmake) file to use the `FindPython3 or `FindPython2` cmake modules instead of `PythonInterp`, using some hints provided as a CMake command line flag probably. I can't do it rightaway, but I've flagged myself on this issue, and will try to fix this.

**Comment by EiffL** [comment]
Actually found a super easy solution to this, @alexander-mead feel free to try out the version in the above PR, it should solve your problems.

**Comment by EiffL** [comment]
(But note  that you can only  compile  pyccl for  a specific python version, the one you compile  for python2 will not work for python3 and vice-versa)

**Comment by EiffL** [comment]
Hey Eske, are you using `python setup.py install`, with the above PR, in a clean clone of CCL ? i.e. without an existing build folder ?
Could you post the setup log you get when you run that command ?

**Comment by empEvil** [comment]
Hi Francois, yes I am. I just cloned CCL onto my workspace on TACC. and ran setup.py install --user
[logCCL.txt](https://github.com/LSSTDESC/CCL/files/2814475/logCCL.txt)

**Comment by EiffL** [comment]
Everything looks good :-/ so, now if you run:
```
$ python3
>>> import pyccl
```
you say this fails ? To be even more explicit:
```
$ /opt/apps/intel17/python3/3.6.3/bin/python3.6
>>> import pyccl
```
This also fails ?
It's very weird, what's the exact error message you get? same as at the top of this thread?

**Comment by EiffL** [comment]
Ok... that makes zero sense ^^'
Unless....
Ok, so it's a long shot, but I see  that your C compiler is:
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
```
but python is  compiled with:
```
Python 3.6.3 (default, Dec 11 2017, 21:18:04) 
[GCC Intel(R) C++ gcc 5.4 mode] on linux
```
So... could you try this again, but  compiling ccl with the same (or above) gcc version  ?

I don't expect this to make a difference but that's the only possible reason I can think of right now....

**Comment by empEvil** [comment]
I just did that (had to use gcc 7) , and then did the pyhon3  import pyccl. And lo and behold no errors. It might have broken another module I had installed (fitsio) but I will just try and reinstall that.

**Comment by c-d-leonard** [comment]
I tried the fix detailed in PR #544 above, but found that when I try to import pyccl in python3 from anywhere other than the CCL directory, it fails with the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danielle/.local/lib/python3.5/site-packages/pyccl/__init__.py", line 21, in <module>
    from . import ccllib as lib
  File "/home/danielle/.local/lib/python3.5/site-packages/pyccl/ccllib.py", line 32, in <module>
    _ccllib = swig_import_helper()
  File "/home/danielle/.local/lib/python3.5/site-packages/pyccl/ccllib.py", line 28, in swig_import_helper
    _mod = imp.load_module('_ccllib', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__ccllib)`

**Comment by c-d-leonard** [comment]
@beckermr this is the issue from our discussion on the telecon just now.

**Comment by EiffL** [comment]
@c-d-leonard so.... If you import from the pyccl directory it works? That would mean that it's just a problem with the install, not the build, and that you may have a rogue install of a different ccl somewhere....
In any case, just to make sure, can you send me a log of the CCL build, just to make sure it's compiling against the right python

**Comment by c-d-leonard** [comment]
@EiffL Sorry for taking a while to get back on this. Attaching a log of my install procedure and a demonstration of the resulting problem 
[log_install.txt](https://github.com/LSSTDESC/CCL/files/3254084/log_install.txt)
Sorry about some weird characters in there, I don't know what happened when logging my terminal, I think it's still readable but let me know if not.

**Comment by EiffL** [comment]
lol, that's weird. Can you make sure you uninstall all ccl installs first? like `pip uninstall ccl` Because the only thing i can think of is that the  ccl version your interpreter is using wasnt actually compiled with python3...
You can also check if the files in `/home/danielle/.local/lib/python3.5/site-packages/pyccl/` are actually recently compiled or old

**Comment by c-d-leonard** [comment]
@EiffL Okay, you were right, I deleted a bunch of zombie versions of CCL and now it works. I am duly embarrassed. Closing issue.

**Comment by beckermr** [comment]
Heeeey! Winning all around! I am just happy I thought of the correct original solution (tell CMAKE where python is) and just missed it in the code like a dummy as well. 🤦‍♂
