### ISSUE TITLE
cmake not found by python setup.py install

### ISSUE THREAD

**Issue by anicola** [LSSTDESC/CCL#542]
Dear all,

I am sorry, but I have an installation issue again. I am trying to install CCL on a cluster where the default cmake is version 2.8. I installed a later version and created an alias i.e. alias cmake='/path/to/custom/cmake/'. When I install the C library of CCL everything works well. When I now run `python setup.py install`, I get

`running install
running bdist_egg
running egg_info
creating pyccl.egg-info
writing requirements to pyccl.egg-info/requires.txt
writing pyccl.egg-info/PKG-INFO
writing top-level names to pyccl.egg-info/top_level.txt
writing dependency_links to pyccl.egg-info/dependency_links.txt
writing manifest file 'pyccl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyccl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.2 or higher is required.  You are running version 2.8.12.2

-- Configuring incomplete, errors occurred!
See also "/home/anicola/WORK/HSC-LSS/code/CCL/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    'Topic :: Scientific/Engineering :: Physics'
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 15, in run
    raise Exception("Could not run CMake configuration. Make sure CMake is installed !")
Exception: Could not run CMake configuration. Make sure CMake is installed !`

So it seems that some paths are not passed on somewhere. Would you have any idea how to force the usage of my custom cmake in the python setup as well?

Thank you very much for your help!
Cheers,
Andrina

**Comment by anicola** [comment]
Dear Tom,

Wow thanks so much for your super quick reply :-). Let me try to answer your questions:

- Yes I have installed numpy version 1.16.0.
- I'm using Python 2.7.5.
- I'm using GNU 4.8.5 as a C compiler.

Please let me know if I can provide any other information. 
Cheers and thanks again!

**Comment by tmcclintock** [comment]
Hmm, very strange. Can you attach this file `/home/anicola/WORK/HSC-LSS/code/CCL/build/CMakeFiles/CMakeOutput.log` that appears in your stack trace? That might be helpful.

**Comment by beckermr** [comment]
You need to update cmake:

> CMake 3.2 or higher is required. You are running version 2.8.12.2

I'd pull a new copy from brew or some other source. You could also use conda-forge.

**Comment by anicola** [comment]
Dear Tom, dear Mat,

Thank you both for your replies. @beckermr I think that's what I did. I installed cmake version 3.12.4 and created an alias (`alias cmake='/path/to/custom/cmake/'`). The C installation worked alright, but when I run `python setup.py install` I get the error that the cmake version is outdated. I was thinking that maybe some paths are not passed along? 
@tmcclintock I have attached the `CMakeOutput.log`.

Thanks a lot again!

[CMakeOutput.log](https://github.com/LSSTDESC/CCL/files/2780974/CMakeOutput.log)

**Comment by damonge** [comment]
@anicola I wonder if adding the path to the directory where your new cmake has been installed to your `PATH` would work. (`export PATH=$PATH:/folder/where/new/cmake/is`).

**Comment by anicola** [comment]
Dear @damonge,

Thanks a lot for your reply. The path is already in my bash profile, with no luck unfortunately.

Thanks a lot!
Cheers,
Andrina

**Comment by beckermr** [comment]
The system calls in the installation script are not properly instantiating the shell (e.g., not using `shell=True`, https://github.com/LSSTDESC/CCL/blob/master/setup.py#L14).

@anicola Can you try installing from master modifying the lines using `call` by adding `shell=True`?

**Comment by anicola** [comment]
Dear @beckermr,

Thanks a lot for your reply. I tried setting `shell=True` in all subprocess calls, but I essentially get the same error:

`running install
running bdist_egg
running egg_info
writing requirements to pyccl.egg-info/requires.txt
writing pyccl.egg-info/PKG-INFO
writing top-level names to pyccl.egg-info/top_level.txt
writing dependency_links to pyccl.egg-info/dependency_links.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'pyccl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
cmake version 2.8.12.2
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Options
  -C <initial-cache>          = Pre-load a script to populate the cache.
  -D <var>:<type>=<value>     = Create a cmake cache entry.
  -U <globbing_expr>          = Remove matching entries from CMake cache.
  -G <generator-name>         = Specify a build system generator.
  -T <toolset-name>           = Specify toolset name if supported by
                                generator.
  -Wno-dev                    = Suppress developer warnings.
  -Wdev                       = Enable developer warnings.
  -E                          = CMake command mode.
  -i                          = Run in wizard mode.
  -L[A][H]                    = List non-advanced cached variables.
  --build <dir>               = Build a CMake-generated project binary tree.
  -N                          = View mode only.
  -P <file>                   = Process script mode.
  --find-package              = Run in pkg-config like mode.
  --graphviz=[file]           = Generate graphviz of dependencies, see
                                CMakeGraphVizOptions.cmake for more.
  --system-information [file] = Dump information about this system.
  --debug-trycompile          = Do not delete the try_compile build tree.
                                Only useful on one try_compile at a time.
  --debug-output              = Put cmake in a debug mode.
  --trace                     = Put cmake in trace mode.
  --warn-uninitialized        = Warn about uninitialized values.
  --warn-unused-vars          = Warn about unused variables.
  --no-warn-unused-cli        = Don't warn about command line options.
  --check-system-vars         = Find problems with variable usage in system
                                files.
  --help-command cmd [file]   = Print help for a single command and exit.
  --help-command-list [file]  = List available listfile commands and exit.
  --help-commands [file]      = Print help for all commands and exit.
  --help-compatcommands [file]= Print help for compatibility commands.
  --help-module module [file] = Print help for a single module and exit.
  --help-module-list [file]   = List available modules and exit.
  --help-modules [file]       = Print help for all modules and exit.
  --help-custom-modules [file]= Print help for all custom modules and exit.
  --help-policy cmp [file]    = Print help for a single policy and exit.
  --help-policies [file]      = Print help for all policies and exit.
  --help-property prop [file] = Print help for a single property and exit.
  --help-property-list [file] = List available properties and exit.
  --help-properties [file]    = Print help for all properties and exit.
  --help-variable var [file]  = Print help for a single variable and exit.
  --help-variable-list [file] = List documented variables and exit.
  --help-variables [file]     = Print help for all variables and exit.
  --copyright [file]          = Print the CMake copyright and exit.
  --help,-help,-usage,-h,-H,/?= Print usage information and exit.
  --help-full [file]          = Print full help and exit.
  --help-html [file]          = Print full help in HTML format.
  --help-man [file]           = Print full help as a UNIX man page and exit.
  --version,-version,/V [file]= Show program name/version banner and exit.

Generators

The following generators are available on this platform:
  Unix Makefiles              = Generates standard UNIX makefiles.
  Ninja                       = Generates build.ninja files (experimental).
  CodeBlocks - Ninja          = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles = Generates CodeBlocks project files.
  Eclipse CDT4 - Ninja        = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles
                              = Generates Eclipse CDT 4.0 project files.
  KDevelop3                   = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles  = Generates KDevelop 3 project files.
  Sublime Text 2 - Ninja      = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                              = Generates Sublime Text 2 project files.

Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    'Topic :: Scientific/Engineering :: Physics'
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/anicola/WORK/HSC-LSS/code/venvs/hsc_lss_python2_venv/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 15, in run
    raise Exception("Could not run CMake configuration. Make sure CMake is installed !")
Exception: Could not run CMake configuration. Make sure CMake is installed !`

However, running `cmake --version` gives `cmake version 3.12.4`.

I'll look into this more myself now as well.

Thanks a lot again!

**Comment by beckermr** [comment]
Grrr. Someone is messing with the path. Sorry I cannot be of more help.

**Comment by EiffL** [comment]
Hey Andrina,
Sorry it didn't work out of the box for you. What's happenning is that the python `call` command will not necessarily run your bashrc and use your declared aliases, see this post:
https://stackoverflow.com/questions/12060863/python-subprocess-call-a-bash-alias
We could change the code in `setup.py` but it's a bit messy. Instead, I would suggest adding your local installation path in front of the standard system path, so that when setup.py looks  for cmake it first finds yours. I would  add this to my bashrc file or just run it before running the  setup :
```
export PATH=/my/path/to/local/bin:$PATH
```
That should fix your problems

**Comment by anicola** [comment]
Dear @EiffL,

Thank you very much for your reply and for your help. This worked like a charm :-)!
Sorry for disturbing you all!

Thank you very much again!
