### ISSUE TITLE
CCL cannot find local version of fftw

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#543]
I have been testing fresh installs of CCL, and it appears that running `python setup.py install` fails to find FFTW when it is already install. When running this command, I see that the `libfftw` files appear in `CCL/build/extern/lib`, and `fftw3.h` appears in `CCL/build/extern/include`.

The problem is that these files already exist where one would expect. Right now I have `/usr/local/lib/libfftw3.a`, and `/usr/local/include/fftw3.h`.

I think this is a bug, unless we are specifying a particular fftw version? Fixing this would make the installation script a bit lighter.

**Comment by tmcclintock** [comment]
Sure, the output is `-I/usr/local/include -L/usr/local/lib -lfftw3`.

**Comment by EiffL** [comment]
ha :-D ok, indeed there is a problem.

**Comment by EiffL** [comment]
Did cmake printed out any useful message when runnning cmake .. in a  clean build directory ?
On my system it finds the installed fftw library, not sure why it doesnt work for you given that pkgconfig is working...

**Comment by tmcclintock** [comment]
What should I look for? If there is a diagnostic file I can upload let me know, or should I just dump all of the output from the setup script?

**Comment by EiffL** [comment]
If you delete the build folder in `CCL` and then run `python setup.py build` this should  output a bunch of messages, including whether it can find fftw or not

**Comment by elisachisari** [comment]
@tmcclintock is this problem still there in v2?

**Comment by tmcclintock** [comment]
I installed using pip but it's difficult to see what steps were taken during installation. I looked in `/anaconda3/lib/python3.7/site-packages/pyccl-2.0.1.dist-info/` as well as `/anaconda3/lib/python3.7/site-packages/pyccl/` for any information but wasn't able to see if it found my local FFTW.

Since it appears nobody else has had this problem, I'll just go ahead and close it.
