### ISSUE TITLE
Magnification bias not working properly

### ISSUE THREAD

**Issue by zdu863** [LSSTDESC/CCL#545]
I'm testing the `mag_bias` option of `NumberCountsTracer`, but it doesn't seem to work. The percent difference between the number count auto correlation power spectrum with/without `mag_bias` is too small (~1e-4) and gives weird spikes.

Attached is the ipython notebook i used to test the feature. The s(z) function i used follows Joachimi and Bridle (2010), arXiv:0911.2454 (Appendix C).
[cclmagbias.zip](https://github.com/LSSTDESC/CCL/files/2834566/cclmagbias.zip)

**Comment by zdu863** [comment]
If I reduce the upper limit of z array from 3 to 1, I get a reasonable percent difference of 0.5%-1.5%. Could this be that the s(z) formula is not accurate at high z and messed up the calculation?

**Comment by zdu863** [comment]
I'm also getting reasonable results if I change the limit of tomographic bin from z=[0.1,3] to z=[0.1,1] or change dN/dz to a Gaussian centered at z=0.5 with sigma=0.2.

**Comment by damonge** [comment]
Pretty sure this must be the magnification kernel integrator thinking that the integral is zero (because it tests only points at the starts where the integrand is zero). Unfortunately I won't be able to look into this for now (probably until next week).

**Comment by ellison-j** [comment]
Hi @damonge -- any progress on this?

**Comment by damonge** [comment]
I think all problems with magnification should have been solved after the generalized tracers implementation. We've certainly been using it for the HSC project without any issues. Could we check this again?

**Comment by ellison-j** [comment]
OK, we are getting a difference between mag bias and no mag bias now so presumably it is fixed. I don't have an idea of how big a difference to expect, but here is the plot.  
![image](https://user-images.githubusercontent.com/26935923/69467880-c60b8a80-0d3e-11ea-853a-8e38483fe8b7.png)
The notebook we used is attached.
[cclmagbias_new.zip](https://github.com/LSSTDESC/CCL/files/3881872/cclmagbias_new.zip)

**Comment by ellison-j** [comment]
> OK, we are getting a difference between mag bias and no mag bias now, so presumably it is fixed. I don't have an idea of how big a difference to expect, but here is the plot.
> ![image](https://user-images.githubusercontent.com/26935923/69469296-ea6a6580-0d44-11ea-9805-20fd36875a0c.png)
> 
> The dN/dz and s(z) used are shown below. We go out to z=3. If we go to z=2 the difference is ~10%, and up to z=1 it is ~1%. Also, if we use the Analytic bin 2 dN/dz from the CCL paper Fig 11, we get ~15%.
> ![image](https://user-images.githubusercontent.com/26935923/69469756-65cd1680-0d47-11ea-98c0-18b3ef510f27.png)
> 
> The notebook we used is attached.
> [cclmagbias_new.zip](https://github.com/LSSTDESC/CCL/files/3881872/cclmagbias_new.zip)
