### ISSUE TITLE
new installation using cmake need more instructions/hints when using local installation of gsl. Simple setting of env variable GSL_ROOT_DIR does't  seem to work. 

### ISSUE THREAD

**Issue by mishakb** [LSSTDESC/CCL#546]
new installation using cmake need more instructions/hints when using local installation of gsl. Simple setting of env variable GSL_ROOT_DIR does't seem to work

**Comment by mishakb** [comment]
our tech support helped to get gsl installed where cmake expect to find it so I got CCL installed and all check_ccl  passed: RESULTS: 94 tests (94 ok, 0 failed, 0 skipped) ran in 236511 ms
But it will be useful to have a few lines in the installation to indicate how cmake can use another specified directory for gsl.

**Comment by elisachisari** [comment]
This is outdated with the new v2 installation, so I'm closing this issue.
