### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#547]
Currently CCL has a memory leak here: https://github.com/LSSTDESC/CCL/blob/3e8fa86214435833afbfb2ff53d0bd572c9e1389/src/ccl_power.c#L409

If, after calling CLASS, CLASS returns with an error, CCL returns after freeing all of the CLASS structures except for the parser (which would only be freed afterwards). This creates a memory leak of ~100kB.

No biggie, right?
But now imagine you're running an MCMC that wanders into weird parameters spaces often enough, now you have to multiply that by a couple hundred/thousand points. 
But that's not all: if CCL cannot compute the Pk it doesn't just fail, it returns NAN. So anything that integrates over the Pk (e.g. sigma_8 or C_ell), will call Pk a bunch of times before it realises that it's integrating rubbish, so multiply that by ~10. Even worse, for C_ell, it will do that for each ell, so multiply that by ~100-1000. In the end, what you get is that a single computation of an angular power spectrum at a weird point in parameter space generates a memory leak of ~800 MB.

This needs urgent fixing, but I'd suggest that we do that after (or while) merging #526, since `ccl_power.c` has seen significant modification there.

**Comment by reneehlozek** [comment]
Wow, that's a good catch!
