### ISSUE TITLE
Include information for building in a conda environment

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/CCL#548]
I thought I would document what is needed to install CCL in a conda environment since that is a good way to work many of us use. It could be good to add this info to the documentation since only home-brew instructions are given for OSX now

This worked for me:

```
conda create --name CCL
conda activate CCL

conda install cmake pkgconfig automake swig
conda install gsl 

pip install pyccl
```

Two things to note:

- You can also install fftw with conda.  But, if you are also using the DM stack (which for right now has its own version of FFTW) it will get confused during the run time if that package is setup. So, it's safer to just let it build it's own version. If you never use the DM code it is safe.

- On OSX 10.14 CLASS won't build.  Actually their code is wrong, but the issue is now being triggered by the fact that on Mojave the /usr/include directories have been removed.  I filed an issue:

https://github.com/lesgourg/class_public/issues/260

in the CLASS repo and in that issue I also write down the work around for now if you don't want to mess with the CLASS code.

**Comment by cwwalter** [comment]
Although this works on OSX, it seems not to work on my Centos7 machine. I am getting a very odd cmake error.  I'll report back once I figure that out.

**Comment by cwwalter** [comment]
Hmm... I tried it again and it just worked the second time. I'm not really sure what was wrong the first time.   It's possible it was because I forgot to match the python version with some other LSST DM software I have around.  But it could have been something setup from before.  In anywise I think that setup should work for both OSX and Linux.

Just as a note: You might think since it is a Linux machine you could skip all of the prereqs but the version of cmake etc seems to be too old on RHEL7 to install CCL, so installing the conda versions makes it work.

**Comment by elisachisari** [comment]
Addressed.
