### ISSUE TITLE
deprecate the C API

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#554]
Reasons:

1. We are spread too thin between the Python and C APIs. This is slowing down development and features, like being able to use fastpt or adjust integration parameters. Most CCL developers don't have a ton of time. 

2. We don't gain that much from the C API in terms of speed. Most of our code is passing data into C and then letting the C code do its thing. We don't need a C API to do this. 

3. We loose too much in terms of being able to catch and handle errors, especially when using the library from Python. This is imperative for long running computations.

4. Centralizing to a single interface for CCL will let us simplify documentation, tests, tutorials, etc.

**Comment by joezuntz** [comment]
I agree with this, but it's a pretty major shift so of course we need a proper discussion about it and a final decision from the project lead, which I think is @elisachisari .

**Comment by beckermr** [comment]
Turns out GitHub issues are a great place to discuss things. ;p

**Comment by joezuntz** [comment]
Absolutely; just encouraging everyone to contribute.

**Comment by philbull** [comment]
@beckermr What would "deprecating C" look like in terms of refactoring the code? Are you thinking of an "on paper" deprecation, where we just release ourselves from certain obligations (like keeping C <-> Python feature parity), or are you thinking of fundamentally changing the way certain things are done (like error handling)?

**Comment by beckermr** [comment]
A bit of both. First it would be "on paper." Then as we develop the code it would get more serious.

**Comment by rainwoodman** [comment]
I like the idea of dropping the requirement on feature parity -- if a feature is much easier to implement in Python than in C, then C is probably not the right tool for the downstream applications neither. 

I would still suggest some `informal` separation between the very low level routines in C and the higher level logic, which can be implemented either via Python C-API, or python.

**Comment by philbull** [comment]
Here are some things we could do as part of a phased deprecation (just ideas):

1. Remove C<->Python feature parity requirement. All C features must be present in the Python API, but not all Python features need to be available through C.
1. Remove unnecessary bits of user-facing C API (e.g. multiple ways of constructing `ccl_cosmology` objects)
1. Convert all precision validation tests to Python-only
1. Remove C unit tests (Python only)
1. Simplify INSTALL and CONTRIBUTORS files (and other docs) to relax C-related requirements
1. Simplify C code examples (but do not remove yet)

**Comment by beckermr** [comment]
Y’all are way overthinking this. 

1. Deprecating the public C API doesn’t mean we can’t have internal APIs. In fact we should have those. It simply means we are free to change those as we see fit with no warning. 

2. We don’t have to fully move every example or benchmark to python right now. 

3. We don’t have to refactor existing code. All of this kind of work can be done in the future. 

All we have to do now is mark it deprecated in hr changelog and update the main documentation to indicate python as the only user interface.

**Comment by philbull** [comment]
@beckermr I agree, but the point is to highlight the implications of this decision for what might change in the future as a result.

**Comment by joezuntz** [comment]
Definitely no need to remove unit tests in the C code if we deprecate.  Regression tests maybe, but not unit tests, those would still be useful.

**Comment by beckermr** [comment]
Yup. Tests of the c code make a lot of sense in some cases though we could be hitting the same code paths with a test from python. 

My point here @philbull is that we don’t actually have to do most of the things on that list. Marking the C api as deprecated is simply letting other people know that we are not maintaining it for anyone but ourselves for use inside CCL. 

There are probably good reasons to *not* move a lot of code from C to python.

**Comment by villarrealas** [comment]
Cross-reference with previous discussion with #227. (I don't think we needed both open at this point though)

**Comment by beckermr** [comment]
Whoops. Thanks for fixing!
