### ISSUE TITLE
typo in fftlog

### ISSUE THREAD

**Issue by xfangcosmo** [LSSTDESC/CCL#558]
In gamma_fftlog function in fftlog.c, in line 31:
```
if(creal(z) < 0.5)
    return M_PI / (sin(M_PI*z)*gamma_fftlog(1. - z));
```
The function `sin` should be replaced by `csin`. This causes wrong results when creal(z)<0.5.

**Comment by beckermr** [comment]
Are you sure? 

https://en.wikipedia.org/wiki/Lanczos_approximation

**Comment by beckermr** [comment]
Ohhh wait. You mean the complex sign function. Yeah def. Sorry!
