### ISSUE TITLE
enable context manager for memory management of CCL Cosmology objects

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#573]
Right now, the C memory held by CCL `Cosmology` objects is not freed until the garbage collector actually runs and calls the `__del__` method. This could happen sooner or could happen later. We don't control much about the python garbage collector.

We should add and recommend that in python people use a context manager API to enforce the timely freeing of memory like this 

```python
with Cosmology(...) as cosmo:
    # do things
```

This involves setting the proper methods on the `Cosmology` object.

**Comment by rainwoodman** [comment]
Does it mean outside of the context region, any calls to cosmo that needs memory will need to be protected and fail.

**Comment by beckermr** [comment]
Those calls will fail yes. They would now too so nothing new here.

**Comment by rainwoodman** [comment]
If the gc is collecting the object and has triggered `__del__` , there is shouldn't be any meaningful reference to the object.

Without a meaningful reference, how can a call be triggered?

**Comment by beckermr** [comment]
I’m not following here but that’s ok. In python we can introspect objects and their attributes to make sure we don’t do anything. I’ll put up a pr
