### ISSUE TITLE
Different results using pyccl and astropy for the calculation of luminosity distance

### ISSUE THREAD

**Issue by linan7788626** [LSSTDESC/CCL#583]
Hi there, I am trying to use pyccl to replace astropy in my codes now, but I found that the results of pyccl do not match the results of astropy perfectly (for example the calculation of luminosity distance).  More details are attached below.

```
from astropy.cosmology import FlatLambdaCDM
cosmo = FlatLambdaCDM(H0=71, Om0=0.264, Ob0=0.045)

DL = cosmo.luminosity_distance(4.0).value*cosmo.h  
```
This is the code for the calculation of luminosity distance with astropy; the result is 26120.75 Mpc/h

However, when I implement the same calculation with pyccl
```
import pyccl as ccl
cosmo = ccl.Cosmology(Omega_c=0.264, Omega_b=0.045, h=0.71, A_s=2.1e-9, n_s=0.96)

DL = ccl.luminosity_distance(cosmo, 1/(1+4.0))*cosmo['h']
```
The result is 24856.02 Mpc/h

I guess the difference is due to the initialization of cosmology models; Could anyone please help me to figure this out?  Sorry for bothering you with such a dumb question. Thanks a lot.

**Comment by tmcclintock** [comment]
The [documentation for astropy](http://docs.astropy.org/en/stable/api/astropy.cosmology.FlatLambdaCDM.html) states that `Om0` is Omega_m, meaning it is all matter, whereas `Omega_c` in ccl is for CDM only. Please set `Om0 = Omega_c+Omega_b` and test if you still get a different answer.

**Comment by tilmantroester** [comment]
CCL includes the contributions from radiation, so you'll need to set the `Tcmb0 ` parameter in astropy as well.

**Comment by villarrealas** [comment]
I can confirm that the difference between Om0 and Omega_c is sufficient to explain the difference to the 10^-3 level. I imagine Tcmb0 will bring it even more into line.

**Comment by linan7788626** [comment]
I am grateful for the prompt responses. I have updated both Om0 and Tcmb0, it did fix the significant difference, and 1e-6 is sufficient for my calculation.  problem solved. Thank you both.
