### ISSUE TITLE
CCL Developer Install Broken for OSX Mojave

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/CCL#586]
Attempting to install CCL on macOS Mojave hits an error of:
`fatal error: 'stdio.h' file not found` - this appears to be caused due to the Mojave moving files outside of standard locations. (see:  https://stackoverflow.com/questions/52702738/stdio-h-not-found-during-r-package-installation)

I have no clue how to fix this.

**Comment by beckermr** [comment]
https://silvae86.github.io/sysadmin/mac/osx/mojave/beta/libxml2/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave/

**Comment by villarrealas** [comment]
Is it possible to work a correction for this into the installer somehow, or is it just worth adding fix instructions to the install information if this works?

**Comment by beckermr** [comment]
This is all about macs. I'd say we let it ride. I'd rather not have cmake doing crazy shit on people's systems. We should add docs.

**Comment by villarrealas** [comment]
I've confirmed this fix works. I'll add it to known install issues and close this for now, since we don't want to change the installer to handle a specific absurdity of a specific Mac install.

**Comment by c-d-leonard** [comment]
FYI am sitting with someone at the DES meeting and we encountered this issue on her laptop with Mojave, luckily we found this issue so she is following the fix in that link now. Just flagging another instance of this issue for posterity.

**Comment by beckermr** [comment]
I don’t think we added docs on this? If not we should reopen.

**Comment by villarrealas** [comment]
I added to it here: https://github.com/LSSTDESC/CCL/wiki/Known-installation-issues

**Comment by beckermr** [comment]
Ahhh awesome. Closing again
