### ISSUE TITLE
Development Workflow On NERSC

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/CCL#587]
Need to add the following steps to the readme.md: 
module load fftw
module load python3

**Comment by cavestruz** [comment]
above to get the following working:
$ python setup.py build
but, still does not work for:
$ cmake ..
$ make 
Appears to have a problem with the fftw

**Comment by cavestruz** [comment]
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /global/homes/a/avestruz/desc/CCL/build/extern/lib/libangpow.a(angpow_chebyshevInt.cc.o): in function `Angpow::ChebyshevInt::Init()':
angpow_chebyshevInt.cc:(.text+0x33c0): undefined reference to `fftw_plan_r2r_1d'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: angpow_chebyshevInt.cc:(.text+0x345a): undefined reference to `fftw_plan_r2r_1d'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: angpow_chebyshevInt.cc:(.text+0x3518): undefined reference to `fftw_plan_r2r_1d'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: angpow_chebyshevInt.cc:(.text+0x3598): undefined reference to `fftw_plan_r2r_1d'
CMakeFiles/check_ccl.dir/build.make:773: recipe for target 'check_ccl' failed
make[2]: *** [check_ccl] Error 1
CMakeFiles/Makefile2:217: recipe for target 'CMakeFiles/check_ccl.dir/all' failed
make[1]: *** [CMakeFiles/check_ccl.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by elisachisari** [comment]
@cavestruz Did you try using the instructions for CCL usage on NERSC outlined here: https://github.com/LSSTDESC/CCL/wiki/Using-and-Installing-CCL-on-NERSC ?

**Comment by elisachisari** [comment]
@cavestruz reported the installation in NERSC is working for the CL group.
