### ISSUE TITLE
CCL and NumCosmo comparison

### ISSUE THREAD

**Issue by vitenti** [LSSTDESC/CCL#590]
Hello all,

We are creating a set of unit tests to compare the CCL outputs to NumCosmo's. Our final objective is to encapsulate CCL as one of the NumCosmo -- HICosmo (homogeneous and isotropic cosmology) models such that people can use CCL as the back-end for various analyses (we already do the same with CLASS, including the comparison). At this initial point we create a constructor method in NcHICosmoDECpl (dark energy with Linder parametrization) which takes a ccl_cosmology struct and creates a mirror NcHICosmoDECpl instance (equivalent parameters). Using this, we already elaborated two unit tests to mimic ccl_test_distances.py, ccl_test_bbks, ccl_test_eh, in doing so we found some minor issues:

1. In the BBKS formula in CCL the definition of "q" seems to be missing a factor of (T_0/2.7K)^2 [Eq. 3.9 Sugiyama 1995], anyway, we create a CCL "compatibility mode" for our BBKS which uses the same definition of "q" as CCL and the tests went through, we agree in 5 x 10^-5 (which increases as we include more knots in CCL splines). In these tests we also included the comparison between basic background quantities as Omegas, H/H0 and growth function. (We can breakdown these number in the future to get the largest error in redshift per observable)

2. In the Eisenstein and Hu fitting formula, the first issue was the additional +1 in Eq. 5 (which is already documented in footnote 8 of CCL's paper) and a missing +1 in the definition of alpha_b, argument of G (Eq. 14), it should be G((1+zeq)/(1+zd)) and in CCL it is  G(zeq/(1+zd)). Again we created a CCL compatibility mode and got an accordance of 5 x 10^-5 as in the BBKS case.

During the distances comparison we found two other issues which are more serious (but simple to fix!):

1. In the neutrino sector the parametrization of the massless neutrinos is done in terms of Neff. The problem here is that, if Neff is smaller than the contribution of the massive neutrinos when ultra-relativistic, you end up with a negative params->N_nu_rel and, consequently, negative Omega (ccl_species_ur_label). In your tests 34/94 and 39/94 you actually use a combination of parameters that implies in negative params->N_nu_rel (the contribution from the ultra relativistic massive neutrinos is slightly larger than Neff=3 used). It may be a good idea to use the number of massless neutrinos and compute Neff from it and the ultra-relativistic massive ones (that was our choice in NumCosmo and I think it is the same as CLASS). Moreover, in a MCMC analysis the use of Neff as parameter can be trick, one would have to use a complicated prior to avoid params->N_nu_rel < 0.

2. The use of global variables in ccl_test_distances.py makes the script hard to read and error prone. For example, the variables Neff and Neff_mnu are defined globally early on in the script. Then, we have them being used in different contexts:
    - Neff as an argument to other function. It is used in compare_distances, compare_distances_hiz;
    - Neff as an argument of compare_distances_mnu, which shadows the global Neff, but then the argument is ignored and the global Neff_mnu is used;
    - Neff_mnu as an argument of compare_distances_mnu_hiz, which shadows the global Neff_mnu, but then it is ignored and the global Neff is used;
    - Neff as an argument of compare_class_distances which has a default value and it is correctly used;
  It was time consuming to read the script and disentangle all variables to see which parametrizations are actually tested. 

3. The use of spline "accelerator". This is nothing more than a simple struct which saves the last knot used to evaluate the spline and use it as the first place to look in the next evaluation. The accelerators should never be used by two or more different splines even when the knots represent the same quantity. For example, we found the following problem:
    - When comparing NumCosmo distances with CCL's we found that once in a while CCL was giving really weird results. After investigating it, we saw that it had evaluated the spline to compute the Omega of massive neutrinos and the knot used was 950 (the neutrino spline has 1000 knots by default). Then just after the spline for h_over_h0 was evaluated, since the accelerator contained the last knot used (950), it started the search by evaluating the xi[950], however, the spline for h_over_h0 (cosmo->data.E) has only 499 knots (by default) and for this reason xi[950] is actually out-of-bounds and end up reading a random place in memory. This confuses the binary search and the spline evaluation giving a random result. 

    Furthermore, in NumCosmo we had several problems with the accelerator, they make the spline evaluation non-reentrant which caused several problems in our multi-threaded applications. Finally, it is not clear how much this actually accelerates things. It would be efficient if the application evaluates the spline several times at very close points (for which there are faster and better ways to use the spline). In other applications where one evaluates the spline at well spaced points the accelerator can actually make things slower since it uses the last evaluation knot to start the binary search possibly leading to more steps to find the correct knot.

    To perform the comparison with NumCosmo, we modified CCL by removing the accelerator (leaving it NULL), with this modification all tests were passed with 5 x 10^-5. It could be a good idea to have an option to turn off the accelerators or to just remove it altogether. In NumCosmo we have an option to use it which is disabled by default.

**Comment by beckermr** [comment]
Thanks for the bug reports! I am going to break this into individual issues that can be addressed in turn.

I agree that the spline accelerators are problematic. I have been considering what to do when I start to add threading to the library. Removing them as you suggest may in fact be the best option.

**Comment by vitenti** [comment]
Hello, I thought in doing it as separated issues but I ended up leaving them all together. Thanks for splitting it up! You misspelled my name in them :)

**Comment by beckermr** [comment]
Ohhhhhh no @vitenti ! now we are pinging random people. Sorry!

**Comment by elisachisari** [comment]
@beckermr @vitenti Which of these issues have been addressed and which have not?

**Comment by beckermr** [comment]
The only things that IDK if they hav been fixed or not are the bbks and eh98 stuff. Everything else has been addressed.

**Comment by nikfilippas** [comment]
It appears that bbks has been fixed.
old code:
``` C
static double tsqr_BBKS(ccl_parameters * params, double k)
{
  double q = k/(params->Omega_m*params->h*params->h*exp(-params->Omega_b*(1.0+pow(2.*params->h,.5)/params->Omega_m)));
  return pow(log(1.+2.34*q)/(2.34*q),2.0)/pow(1.+3.89*q+pow(16.1*q,2.0)+pow(5.46*q,3.0)+pow(6.71*q,4.0),0.5);
}
```
new code:
``` C
static double tsqr_BBKS(ccl_parameters* params, double k) {
  double tfac = params->T_CMB / 2.7;
  double q = tfac * tfac * k / (
    params->Omega_m * params->h * params->h *
    exp(-params->Omega_b * (1.0 + pow(2. * params->h, .5) / params->Omega_m)));
  return (
    pow(log(1. + 2.34*q) / (2.34*q), 2.0) /
    pow(1. + 3.89*q + pow(16.1*q, 2.0) + pow(5.46*q, 3.0) + pow(6.71*q, 4.0), 0.5));
}
```

Re. the other issue with the +1 missing in the EH formula, this has already been discussed in #143 .

So we will be closing this issue now.
