### ISSUE TITLE
BBKS bug

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#591]
from @vitenti

>>> In the BBKS formula in CCL the definition of "q" seems to be missing a factor of (T_0/2.7K)^2 [Eq. 3.9 Sugiyama 1995], anyway, we create a CCL "compatibility mode" for our BBKS which uses the same definition of "q" as CCL and the tests went through, we agree in 5 x 10^-5 (which increases as we include more knots in CCL splines). In these tests we also included the comparison between basic background quantities as Omegas, H/H0 and growth function. (We can breakdown these number in the future to get the largest error in redshift per observable)

**Comment by beckermr** [comment]
Who uses BBKS? Can we simply get rid of this option?

**Comment by damonge** [comment]
Fixing in #526

**Comment by damonge** [comment]
Fixed by #526

**Comment by beckermr** [comment]
A fix needs to be put on the v1x branch too

**Comment by damonge** [comment]
ok, just made a PR
