### ISSUE TITLE
document EH98 differences between the paper and the code in CCL

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#592]
from @vitenti

> In the Eisenstein and Hu fitting formula, the first issue was the additional +1 in Eq. 5 (which is already documented in footnote 8 of CCL's paper) and a missing +1 in the definition of alpha_b, argument of G (Eq. 14), it should be G((1+zeq)/(1+zd)) and in CCL it is G(zeq/(1+zd)). Again we created a CCL compatibility mode and got an accordance of 5 x 10^-5 as in the BBKS case.

**Comment by damonge** [comment]
I'd look at the conversation here: https://github.com/LSSTDESC/CCL/pull/143 before deciding whether this is worth wasting time on (since I doubt that the EH approximation is accurate at the 1E-4 level anyway).

**Comment by beckermr** [comment]
there are two separate things here - one is the thing in the footnote, the other is in the def of `G`

**Comment by beckermr** [comment]
Mmmmk. All differences from the published paper should be documented in both the CCL and the code documentation. I am changing the issue title in this PR.
