### ISSUE TITLE
deprecate use of GSL spline accelerators

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#594]
from @vitenti

> When comparing NumCosmo distances with CCL's we found that once in a while CCL was giving really weird results. After investigating it, we saw that it had evaluated the spline to compute the Omega of massive neutrinos and the knot used was 950 (the neutrino spline has 1000 knots by default). Then just after the spline for h_over_h0 was evaluated, since the accelerator contained the last knot used (950), it started the search by evaluating the xi[950], however, the spline for h_over_h0 (cosmo->data.E) has only 499 knots (by default) and for this reason xi[950] is actually out-of-bounds and end up reading a random place in memory. This confuses the binary search and the spline evaluation giving a random result.

**Comment by beckermr** [comment]
This is probably the best way to proceed wrt the introduction of openmp.

**Comment by tmcclintock** [comment]
Can you explain what you mean by "deprecate the use of [the] accelerators"? Wouldn't the obvious solution be to have an accelerator for each spline?

**Comment by damonge** [comment]
Duplicate: https://github.com/LSSTDESC/CCL/issues/316

**Comment by vitenti** [comment]
@tmcclintock you would need to have an accelerator per spline and having it reset every time the number of knots in the same spline change.

**Comment by beckermr** [comment]
This doesn't seem to be a duplicate issues @damonge. I mean in this issue actually just getting rid of them all together.

**Comment by beckermr** [comment]
You would need an accelerator per spline and thread @tmcclintock.
