### ISSUE TITLE
Analytic neutrino integral

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#596]
This is to document some partial progress towards potentially making the neutrino phase space integral analytic at some point in the future if desired. This was suggested by Zachary Slepian (I can't find his github handle), and worked on at the Berkeley 2019 meeting / hack day by @xfangcosmo, @aferte and me. Tagging @tmcclintock who was also interested. 

Zach's idea was that maybe the phase space integral for neutrinos, which we are currently doing numerically (see equation 6 of the CCL paper https://arxiv.org/pdf/1812.05995.pdf), could be done analytically a method similar to that described here: http://www.physik.uni-regensburg.de/forschung/fabian/pages/mainframes/teaching/teaching_files/files%20of%20mf_statistical_physics/BE_integrals.pdf 

@xfangcosmo worked through the math on this during the Berkeley 2019 meeting and at hack day; finding that because of the difference in form of the integral; the analytic result is not quite as nice as in those notes linked above and requires summation over a number of terms. However, it seems like those terms could converge pretty quickly. Xiao made a mathematica notebook showing the answer; I'll leave it up to him if he wants to upload that here. The answer is in terms of things Bessel functions evaluated at single points.

If we wanted to pursue this, the steps would be as follows:
- [x]  Check how much the numerical evaluation of this integral is or is not a bottleneck.
- [ ]  If it's a bottleneck, check if evaluating the analytic form up to the required number of terms for convergence is faster.  
- [ ]  Compare with the numerical results as a cross check.

I wouldn't say this is a priority issue, just something to look at at some point if we want to.

**Comment by tmcclintock** [comment]
The integral is computed when a cosmology object is instantiated, correct? Is the integral performed if the neutrino mass is not specified? If so, it would be very easy to test if this is worth spending any time on with the following script:
```python
import pyccl as ccl
import timeit

def test_noNus(): #no Nus is good Nus
    ccl.Cosmology(Omega_c=0.3, Omega_b=0.05, h=0.7, A_s=1e-10, n_s=0.96)

def test_hasNus():
    ccl.Cosmology(Omega_c=0.3, Omega_b=0.05, h=0.7, A_s=1e-10, n_s=0.96, m_nu=0.1)

print(timeit.timeit("test_noNus()", setup="import pyccl as ccl", number=100))
print(timeit.timeit("test_hasNus()", setup="import pyccl as ccl", number=100))
```

I think this should work fine (can't run it ATM). The output should show the runtime for 100 calls to both functions. @c-d-leonard, will the integral be performed if m_nu is specified? If not, the function call can just be modified appropriately.

**Comment by xfangcosmo** [comment]
I will share my derivation and Mathematica notebook after I clean it.
For reference, I timed the calculation in Mathematica, for rescaled neutrino mass \tilde{m} <1, it took <0.025 sec with a series expansion up to the 15th order (already better than 0.1% accuracy). Smaller \tilde{m} took shorter time. I attached the computation time vs. \tilde{m}.

![neutrino_integral_timing](https://user-images.githubusercontent.com/15255091/53850553-a7cfe580-3f89-11e9-9a73-6e4451b995b7.png)

**Comment by xfangcosmo** [comment]
@c-d-leonard @tmcclintock I used Tom's script and found it only took ~0.25ms for one computation. That means the analytic version is probably not needed?

**Comment by tmcclintock** [comment]
I don't mean to toot my own horn, but "nu Nus is good Nus" is very clever.

You're welcome.

**Comment by beckermr** [comment]
Yes this is not even close to the bottleneck. I am going to close this issue since we don't ever need to do this. Feel free to reopen.

**Comment by slosar** [comment]
You can also use Pade approximation and get to the same results even faster.

**Comment by xfangcosmo** [comment]
@slosar  Good idea! Or we can generate the integral results for a list of m (for 0<=m<1), and interpolate, since the function is very smooth.  however, given the current speed, this should be unnecessary.

**Comment by slosar** [comment]
See 
https://www.overleaf.com/16264600shmrnpdndtfq#/62267973/
by Martin White. This could be trivially made more accurate and I think it will be faster that those gamma functions.
See also
https://www.dropbox.com/s/0nmjyvcbq271z0k/pr.pdf?dl=0
for an alternative (but now I think that Pade is probably better).

**Comment by xfangcosmo** [comment]
very nice approximations!
