### ISSUE TITLE
Simplify parameter dumping

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#597]
We currently have a clunky way of dumping the parameters used to define a cosmology object to file. This requires doing things from the C layer through `ccl_parameters_write_yaml` and `ccl_parameters_read_yaml`. It'd be nicer if we were able to do this directly from python (and one could even imagine adding a class method that allows you to initialize a Cosmology object directly from a yaml file)

**Comment by elisachisari** [comment]
@damonge, is this not addressed by https://github.com/LSSTDESC/CCL/blob/master/examples/Reading-writing-Cosmology-objects.ipynb ?

**Comment by c-d-leonard** [comment]
@damonge bumping this, I think it's fixed here https://github.com/LSSTDESC/CCLX/blob/master/Reading-writing-Cosmology-objects.ipynb if yes, close?

**Comment by c-d-leonard** [comment]
@damonge bumping again can we close?

**Comment by tilmantroester** [comment]
I think the python part of this has also now been addressed in #852.
