### ISSUE TITLE
implement halofit

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#599]
Right now IIUIC, when people request EH98 for the transfer function, they are not getting halofit back out for the non-linear power spectrum. I think this is pretty weird TBH. We should have halofit for this.

**Comment by alexander-mead** [comment]
This is related: https://github.com/LSSTDESC/CCL/issues/445

It seems strange to me, and completely unnecessary, to get halofit from CLASS.

**Comment by beckermr** [comment]
FYI, I am pulling code from here: https://github.com/beckermr/cosmocalc/blob/master/src/nonlinear_powspec.c
