### ISSUE TITLE
separate out linear versus non-linear power spectrum computations 

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#600]
It would be nice to enable more options for the linear versus non-linear power spectra. For example, right now to use the comic emu, you have to also run class even if this may not be needed.

**Comment by alexander-mead** [comment]
This gripe of mine is related: https://github.com/LSSTDESC/CCL/issues/337

**Comment by beckermr** [comment]
So @alexander-mead this PR would do the following.

Restrict the transfer function to one of 
 - bbks
 - eisenstein_hu
 - boltzmann_class

It would restrict the non-linear matter power spectrum to one of 
 - linear (e.g., no corrections to linear)
 - halofit
 - halo_model
 - emu

Any restrictions on combining them have been removed. Users be warned!

I think this addresses #337 at the cost of still having two lists. Given everything else, this seems least worst. Thoughts?

**Comment by beckermr** [comment]
Also using the halo_model option with anything but class won't work until I do #599 later this week hopefully.

**Comment by alexander-mead** [comment]
This sounds very sensible to me.

**Comment by alexander-mead** [comment]
I suppose in the (far?) future it could be worth allowing users to initialise a cosmology object and then to compute lots of different non-linear P(k), which may end up going into different parts of the same cosmological analysis (e.g., Fast-PT for intrinsic alignments, halofit for non-linear P(k)).

**Comment by beckermr** [comment]
That sounds nice, but I am going to punt hard on that for as long as possible.
