### ISSUE TITLE
setup example benchmark in python by converting one of them

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#602]

**Comment by tmcclintock** [comment]
For example, converting [this file](https://github.com/LSSTDESC/CCL/blob/master/tests/ccl_test_correlation_3d.c) in `tests/ccl_test_correlation_3d.c` into Python.

@beckermr, is the idea to use a different testing framework, or just making this some kind of numpy.testing test?

**Comment by beckermr** [comment]
I am going to deprecate the use of nose. I don't care about numpy.testing functions etc.
