### ISSUE TITLE
Constant pc to meters

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CCL#606]
In ccl_core.c, line 166: Increase precision to 16 places in the conversion pc to m Increase (current version 13 digits), namely:

3.08567758149E+16 -> 3.08567758149136727891E+16

Modify pho_crit accordly (line 171).

There is no reason to truncate it below the machine precision. At first, this can seem irrelevant. But it is easier to compare to other codes.

**Comment by elisachisari** [comment]
What AU value are you using? We are trying to restrict to tabulated values from PDG. E.g. http://pdg.lbl.gov/2016/reviews/rpp2016-rev-astrophysical-constants.pdf

**Comment by vitenti** [comment]
That is exactly what we are using, however, in the table you used as reference they truncated at 
3.085 677 581 49 × 10^16 m, while the recommendation (see [7] of your table) is to use 1 AU / (π /648 000). Since 1 AU is now exact we computed 1 AU / (π /648 000) at the full double precision.

**Comment by elisachisari** [comment]
If I calculate this in python I get
`Decimal(149597870700)/(Decimal(3.14159265358979323846)/Decimal(180)/Decimal(3600)) 
= Decimal('30856775814913673.99198952281')`
I'm using the M_PI value from C supposedly. This is not the same number you have above, do you know where the difference lies?

**Comment by vitenti** [comment]
Yes, the difference comes from \pi, I used mpfr to compute pi with 40 places, you can use mathematica or even C with long double (and in this case M_PIl instead of M_PI).

**Comment by elisachisari** [comment]
Ok, so in CCL we are using M_PI throughout, so any objections to me using the number I quoted above? I.e., `Decimal('30856775814913673.99198952281')`? This should already be an improvement and its more consistent with the rest of the code.

**Comment by damonge** [comment]
sounds good to me

**Comment by vitenti** [comment]
Yes, it seems consistent.
