### ISSUE TITLE
Bessel j1 approximation

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CCL#607]
In ccl_power.c, line 1179: the coefficient of the third term is wrong. 
0.003561429 -> 0.003571429. 
Moreover, there is no reason to use this truncated expression. 
I suggest to write this expansion as:

w = 1. + kR2*(-1.0/10.0 +
                   kR2*(1.0/280.0 +
                        kR2*(-1.0/15120.0 +
                             kR2*(1.0/1330560.0 +
                                 kR2* (-1.0/172972800.0))))); 

Including the 10-th order term to match the GSL function.

**Comment by beckermr** [comment]
Or we can simply use the GSL function...
