### ISSUE TITLE
CCL and CLASS constants

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CCL#608]
Some physical constants defined in CLASS do not match the CCL values. 

 In order to perform consistent computations, we create a patch for CLASS in NumCosmo in order to match the NumCosmo constants. 
You could implement a similar solution in CCL.

**Comment by elisachisari** [comment]
Thanks @pennalima for reporting this. The difference in the physical constants between CCL and CLASS is already documented in the CCL note and is below 3x10^{-5} in general. I don't think this impacts our predictions significantly at this point, but feel free to re-open this if you noticed this propagated in any way that might affect our cosmological analyses.
