### ISSUE TITLE
ccl_sigmaR does not use the 2D P(k,z) spline to compute sigmaR

### ISSUE THREAD

**Issue by vitenti** [LSSTDESC/CCL#609]
Comparing CCL and NumCosmo, which already implements the 2D (k, z) spline for P(k, z), we noticed that the 5e-5 required precision fails: 
- sigma at z > 0.8 and is attained between 0 <= z < 0.8 and  0.1 < R < 100;
- dlnsigma_dlog10M at z > 0.8 and is attained between 0 <= z < 0.8 and  0.3 < R < 100, if the interval for R starts at 0.1 then it already fails at z = 0.

The lower bound for R is controlled by K_MAX_SPLINE. But even if we increase its value, we still have problems at high z (z ~1).

_Originally posted by @pennalima in https://github.com/LSSTDESC/CCL/issues/79#issuecomment-472574231_

I just realized that CCL does not use the P(k,z) to compute sigma_R at redshifts z>0. It always compute at z=0 and then multiply the result by the growth function. This leads to lower precisions at high redshifts.

**Comment by elisachisari** [comment]
ccl_sigmaR relies on the linear power spectrum, so the scaling by the growth function should be sufficient. Wouldn't using P(k,z) introduce additional uncertainties due to the splining of the matter power spectrum? To increase the precision, have you tried improving the sampling of the growth function instead?

**Comment by vitenti** [comment]
If I'm not mistake we tried improving the sampling in the growth and obtained the same order of magnitude for the difference. It is expected that the growth computed by the simple ODE (that both NumCosmo and CCL use) will differ from the actual growth computed by CLASS (or CAMB) which takes into account the (small at that point) coupling with the other components. To avoid this, when using CLASS and splitting P(k,z) = D^2(z)P(z), we use D(z) = sqrt (P(k_star, z) / P (k_star, 0)) with a fixed fiducial k_star instead of D(z) as the solution of the simple ODE. 

I'll test if using your growth the difference vanishes.

**Comment by c-d-leonard** [comment]
@vitenti was there any update on this?

**Comment by damonge** [comment]
Addressed by #800
