### ISSUE TITLE
remove the correlation 3d and RSD benchmarks

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#612]
It is pretty clear to me that the benchmarks made for the 3d correlation function and RSD measurements have issues. They depend on a few things, like the halofit implementation and there are the issues with the gamma function in #578. I don't see the point in keeping them given that the accuracies are at nearly 6% now which is pretty bad.

**Comment by elisachisari** [comment]
We agreed to keep these for now, so I'm closing this issue.
