### ISSUE TITLE
Scattered docs

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#617]
Our documentation is currently scattered in
- the CCL note
- multiple READMEs
- code examples (C and python)
- the wiki
- the CCL paper
- doxygen
- readthedocs

We should consolidate docs in as much as possible. The proposal is to put python code example snippets in the README, and ensure we maintain this as well as readthedocs and the README in the benchmark folder.

In this proposal, the CCL note and wiki would be deprecated (with the relevant information moved to the README) and the jupyter notebooks would move to a dedicated repository.

**Comment by beckermr** [comment]
I think we should keep descriptions of the core equations in the note, but remove the information on the code in it.

**Comment by beckermr** [comment]
We should remove doxygen too.
