### ISSUE TITLE
angular_cl fails for emulated power

### ISSUE THREAD

**Issue by NiallJeffrey** [LSSTDESC/CCL#618]
Using the emulated power spectrum gives an error (CCLError: Error CCL_ERROR_INTEG:) when used to calculate the lensing power spectrum. This cosmology set up works perfectly well to calculate the P(k) power spectrum though.

Code snippet:
```
cosmo3 = ccl.Cosmology(Omega_c=0.24, Omega_b=0.044, h=0.7, sigma8=0.8, n_s=0.95, w0=-1, wa=0., Neff=3.04, transfer_function='emulator', matter_power_spectrum='emu', Omega_g=0.0) 
cls3 = ccl.angular_cl(cosmo3, lens1, lens2, ell)
```

Output:
```
CCLErrorTraceback (most recent call last)
<ipython-input-91-c8ba4093cc5a> in <module>()
      6         matter_power_spectrum='emu', Omega_g=0.0)
      7 
----> 8 cls3 = ccl.angular_cl(cosmo3, lens1, lens2, ell)

/usr/local/lib/python2.7/dist-packages/pyccl-0.10.dev362+g8d7a9b6b-py2.7.egg/pyccl/cls.pyc in angular_cl(cosmo, cltracer1, cltracer2, ell, l_limber, l_logstep, l_linstep)
    330             cosmo, clt1, clt2, l_limber, l_logstep,
    331             l_linstep, ell, len(ell), status)
--> 332     check(status)
    333     return cl

/usr/local/lib/python2.7/dist-packages/pyccl-0.10.dev362+g8d7a9b6b-py2.7.egg/pyccl/core.pyc in check(status, cosmo)
    676     # Check for known error status
    677     if status in error_types.keys():
--> 678         raise CCLError("Error %s: %s" % (error_types[status], msg))
    679 
    680     # Check for unknown error

CCLError: Error CCL_ERROR_INTEG: 
```

I am using CCL version on the docker image as downloaded 5th April 19.

**Comment by elisachisari** [comment]
Could you give us lens1 and lens2 as well?

**Comment by NiallJeffrey** [comment]
The error occurs using the example "Lensing angular power spectrum notebook" with everything the same except changing the ccl.Cosmology() to my original code snippet.

https://github.com/LSSTDESC/CCL/blob/master/examples/Lensing%20angular%20power%20spectrum.ipynb

**Comment by damonge** [comment]
So this is due to the fact that you can't evaluate the emulator power spectrum beyond z~2.5 or so.
Not sure there's much we can do about that other than creating a better emulator Pk that extrapolates with linear growth or something like that (which isn't great).

Any thoughts @elisachisari ?

**Comment by c-d-leonard** [comment]
Any more thoughts on this issue?

**Comment by c-d-leonard** [comment]
I'm going to consider this closed, @NiallJeffrey please re-open if you disagree.
