### ISSUE TITLE
Only linear part of power spectrum is computed for certain transfer functions

### ISSUE THREAD

**Issue by ErikOsinga** [LSSTDESC/CCL#619]
Hi,

When I try to compute the angular Cls for transfer functions different than "boltzmann", it seems that only the linear part of the power spectrum is computed, even though I initialise my cosmology as follows:
```
    cosmo_fid = ccl.Cosmology(Omega_c=Omega_c, Omega_b=Omega_b, h=h
        , sigma8=sigma8, n_s=ns, w0=w0, transfer_function='eisenstein_hu'
        , matter_power_spectrum='halofit')
```

The result is this:
![issue](https://user-images.githubusercontent.com/12582441/55800830-e4d14f80-5ad4-11e9-8d2a-69e1893b76e1.png)

It seems that somehow the `matter_power_spectrum` keyword is ignored? I get the same behaviour when I set the transfer function to 'bbks'.

**Comment by ErikOsinga** [comment]
According to the issue you mentioned, the `bbks` and `eisenstein_hu` should be compatible with any `matter_power_spectrum` argument right?

Is there a method to use a transfer function other than `boltzmann` combined with `halofit`? I am not sure what you mean with defining two different cosmology objects.

**Comment by beckermr** [comment]
Yes @ErikOsinga. We are in the middle of implementing this for v2. In v2 we will be able to combine any transfer function with halofit.

**Comment by elisachisari** [comment]
_According to the issue you mentioned, the bbks and eisenstein_hu should be compatible with any matter_power_spectrum argument right?_

It is compatible in the sense that CCL will not crash, but you will be getting the `bbks` or the `eisenstein_hu` linear power spectra out, even if you ask for the nonlinear one.

_Is there a method to use a transfer function other than boltzmann combined with halofit? I am not sure what you mean with defining two different cosmology objects._ 

As Matt replies below, this will be possible in v2. Right now you can only get the CLASS halofit version out of CCL.

**Comment by ErikOsinga** [comment]
Ah I see now, thanks very much.
