### ISSUE TITLE
No bias for Tinker 2008 halo mass function 

### ISSUE THREAD

**Issue by anicola** [LSSTDESC/CCL#636]
Hi all, 

When I try computing the mass function and the halo bias for the Tinker 2008 mass function (i.e. specifying `mass_function='tinker'`) I get the following error message from CCL:

`pyccl.errors.CCLError: Error CCL_ERROR_MF: ccl_massfunc.c: ccl_halo_b1(): No b(M) fitting function implemented for mass_function_method: 1`

Would anyone know how to fix this?

Thank you very much!
All the best,
Andrina

**Comment by damonge** [comment]
I agree that this behavior is too conservative. Users should be able to compute the Tinker 10 (or Sheth-tormen or whatever) halo bias even if they're using a different mass function. We could include a warning if necessary.

**Comment by damonge** [comment]
Also got this query from @BenediktDiemer

**Comment by beckermr** [comment]
closing since superseded by #668
