### ISSUE TITLE
Make SigmaR take array(s) as arguments

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/CCL#638]
I want to be able to do something like this
```
ccl.sigmaR(C,8/0.7,np.array([1,0.5,0.3]))

```
Also for the R parameter or both (in which case it only makes sense if values are associated pairwise.

**Comment by beckermr** [comment]
This is an example of a broader issue in the library FWIW. Numpy's API typically likes anything that can be broadcasted together, but IDK if we want to support that.

**Comment by beckermr** [comment]
It takes R as an array, just not the scale factor. I actually think we don't want to fix this given the current API.

**Comment by c-d-leonard** [comment]
Are we okay to close this? @beckermr @slosar

**Comment by beckermr** [comment]
i'm fine but @slosar should weigh in

**Comment by slosar** [comment]
If it is OK with becker it is ok with me.  I'm closing this.
