### ISSUE TITLE
Issue with ccllib and SWIG when installing pyccl

### ISSUE THREAD

**Issue by ZeFon** [LSSTDESC/CCL#640]
Hi

I am trying to install the python wrapper pyccl. I get the following error message in the end:

`[ 79%] Performing configure step for 'SWIG'`
 `+ test -d Tools/config`
` + aclocal -I Tools/config`
`./autogen.sh: line 11: aclocal: command not found`
`make[3]: *** [pyccl/SWIG/src/SWIG-stamp/SWIG-configure] Error 127`
`make[2]: *** [pyccl/CMakeFiles/SWIG.dir/all] Error 2`
`make[1]: *** [pyccl/CMakeFiles/_ccllib.dir/rule] Error 2`
`make: *** [_ccllib] Error 2`
`Traceback (most recent call last):`
`  File "setup.py", line 77, in <module>`
`    'Topic :: Scientific/Engineering :: Physics'`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup`
`    return distutils.core.setup(**attrs)`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/core.py", line 148, in setup`
`    dist.run_commands()`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/dist.py", line 955, in run_commands`
`    self.run_command(cmd)`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command`
`    cmd_obj.run()`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run`
`    self.do_egg_install()`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install`
`    self.run_command('bdist_egg')`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/cmd.py", line 313, in run_command`
`    self.distribution.run_command(command)`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command`
`    cmd_obj.run()`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 170, in run`
`    cmd = self.call_command('install_lib', warn_dir=0)`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 156, in call_command`
`    self.run_command(cmdname)`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/cmd.py", line 313, in run_command`
`    self.distribution.run_command(command)`
 ` File "/Users/Ze/anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command`
`   cmd_obj.run()`
`  File "/Users/Ze/anaconda/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run`
`    self.build()`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/command/install_lib.py", line 105, in build`
`    self.run_command('build_py')`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)`
`  File "/Users/Ze/anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()`
`  File "setup.py", line 23, in run`
   `raise Exception("Could not build CCL")`
`Exception: Could not build CCL`

I am in a MacOS. I managed to install and compile the CCL C library although I was required to do 

`export CC=gcc-9 CXX=g++-9`

since saying gcc is not enough. Mac will still assume clang if we don't give the version. I did the same for installing the wrapper but didn't help. I am hinting there is a problem with my python but the PYTHONPATH seems to be correct. 

I looked for other issues with similar problems but a solution wasn't very clear to me. The info in the readme files don't indicate how to address this.

**Comment by EiffL** [comment]
Hi @ZeFon , I think the simplest solution is to install swig with anaconda before running the CCL install, this way it won't try to recompile it itself. Something like `conda install swig` I guess.

**Comment by ZeFon** [comment]
Hi @EiffL, that solved it. As it installed angpow on its I didn't think about this possibility.  Thanks.
