### ISSUE TITLE
Single mass option for neutrinos

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#643]
In discussion with @c-d-leonard: In issue #572, it was pointed out it would be convenient to have a "single mass" option for neutrinos, where instead of splitting a single number into a hierarchy or equal masses always, you could pass a single number and mean masses = (M, 0, 0). Obviously this is covered by the list option but there was a desire to have this simple option available as a named option as well.

**Comment by beckermr** [comment]
We can add this to the API post-v2 without breaking things. Going to remove from v2 milestone.

**Comment by c-d-leonard** [comment]
Closed by PR #730
