### ISSUE TITLE
mu / Sigma MG cosmologies specified by sigma8

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#654]
If the user specifies a cosmology in terms of sigma8 and then wants to use a class P(k), ccl gets the corresponding A_s with a guessed value of A_s and rescaling by a ratio of the specified sigma8 to the resulting sigma8. However, in cosmologies which also have mu / Sigma !=0 for modified gravity, this does not account for the modified growth rate affecting sigma8. 

Thanks @beckermr for pointing this out. @philbull @WeikangLin @mishakb @TessaBaker could you chime in to confirm that you agree that the current implementation is wrong?

This slipped by in the benchmarking process because all our benchmarks were specified in terms of A_s rather than sigma8.

**Comment by beckermr** [comment]
This is related to #651 in that we probably don't need to run class twice even in the pure GR case. We can specify a scaling factor to be used when tabulating the linear power spectrum. This factor should cover both cases.

**Comment by WeikangLin** [comment]
Hi @c-d-leonard, thanks for pointing out the issue. I probably will check this out during this weekend, but a fast way (if feasible) to confirm whether it is wrong is to see the two orders commute. That is, say in MG if one feeds in an As to get a sigma8, then see if the same sigma8 gives the same As. If not, I can think of two ways to fix it: 1. replace the P(k) in spline with the MG P(k) (if it is not ready so). 2. add to the sigma8 function the MG factor. Only one of them should be done, not both. I would suggest the first way in case there are other consistency issues.

I am not sure if CCL runs CLASS twice to get sigma8 (this reminds me some double message I used to receive long time ago though), but I agree with @beckermr that CLASS should not be run twice in either GR or MG cases. The guessed P(k) can be just scaled by a factor = (sigma8_specified/sigma8_guessed)^2.

**Comment by WeikangLin** [comment]
Hi @c-d-leonard, thanks for pointing out the issue. I probably will check this out during this weekend, but a fast way (if feasible) to confirm whether it is wrong is to see the two orders commute. That is, say in MG if one feeds in an As to get a sigma8, then see if the same sigma8 gives the same As. If not, I can think of two ways to fix it: 1. replace the P(k) in spline with the MG P(k) (if it is not already so). 2. add to the sigma8 function the MG factor. Only one of them should be done, not both. If one of them has been done, there are other problems.

I am not sure if CCL runs CLASS twice to get sigma8 (this reminds me some double message I used to receive long time ago though), but I agree with @beckermr that CLASS should not be run twice in either GR or MG cases. The guessed P(k) can be just scaled by a factor = (sigma8_specified/sigma8_guessed)^2.

**Comment by mishakb** [comment]
I concur that this is a problem that needs to be fixed.  When MG is used, there should be a sanity check to ensure that the MG P(k) is used all the time. I also agree that there is no need to call CLASS twice but juts do a rescaling using sigma8 ratio.

**Comment by TessaBaker** [comment]
Likewise, I agree that the relation between the ‘guessed’ A_s and the resulting \sigma_8 has to be calculated in MG in order for this rescaling technique to hold.

**Comment by WeikangLin** [comment]
Hi @c-d-leonard, I was trying to see whether 1. the As and sigma8 commute, and 2. whether the sigma8 in MG is different from that in GR for the same As specified. But I ran into installation problem. Could you see what are the outcomes of them? I will appreciate it.
