### ISSUE TITLE
mass function enhancements

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#655]
Some queries/comments from @BenediktDiemer

- A number of routines appear in counter-intuitive places (e.g., general routines such as ccl_dlninvsig_dlogm() are hidden away in the MF module).
- Concentration is hidden inside the halo model unit, though those are also not exactly the same things.
- Personally, it seems strange to me that c/MF are fixed when the cosmology is fixed, but I'm sure there are reasons for that?
- The naming scheme for c/MF models is somewhat inconsistent: The scheme is incoherent, e.g. "tinker" and "tinker10". There are some errors, e.g. "bhattacharya11" should be "bhattacharya13" (I think)

**Comment by villarrealas** [comment]
I believe the third one is related to issue #636. The last one is my fault (I think we just started with tinker and then decided to add on more and tinker wasn't updated).
