### ISSUE TITLE
Consistency in mass definitions

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#656]
We got this from @BenediktDiemer

- Overdensity mass definitions are not implemented in a coherent, functional manner
- Since all c/MF models refer to a particular mass definition, it's important to implement those cleanly. Currently, only one overdensity is passed, making it hard to understand for the user whether this refers to mean, critical etc.
- Checks on whether two mass definitions are the same are performed with lines such as `if (odelta == Dv_BryanNorman(cosmo, a, status))`. This is very dangerous, as such float comparisons can easily fail. For example, I computed Delta_vir using the same function in Colossus, and got an error about non-matching mass definitions.
- The mass definitions assumed in some models need to be checked. For example, I think Angulo+ used FOF, not M200m as in CCL.
- It would be good to add conversion between mass definitions, given that each c/MF model predicts only one or a few (typically).
- I'm not sure the implemented concentration models are best for cosmology. Both the Bhattacharya and Duffy models are calibrated on older simulations with limited mass range, calibrated at a particular cosmology, and/or valid only for particular redshifts. Power-law fits such as Duffy become demonstrably wrong at low masses. These are undesirably features in a cosmology code where cosmology is definitely going to vary! I realize that I have a bias here given that I've proposed some concentration models myself, but I think it'd be critical to have at least one model that automatically takes variations with cosmology into account (such as Bullock+01, Ludlow+16, Child+18, or our models).

**Comment by damonge** [comment]
I actually agree with most of these, and was hoping eventually someone would improve the current code into a more consistent halo-model module

**Comment by villarrealas** [comment]
I'd argue that it is very consistent in the sense that we always use the overdensity with respect to the mean background density of the universe (within the mass function side), though I don't know if that is the same across the halo model sections of the code, which I am less familiar with. Consistency across models (and halo definitions) is quite a bit of work though... but good work.
