### ISSUE TITLE
likelihood interface and data structures

### ISSUE THREAD

**Issue by elikrause** [LSSTDESC/CCL#67]
One key application for the CCL will be as theory backend for MCMC analyses. For this, a user may want to specify the angular binning (in \ell, or \theta), a set of CCL_ClTracer structures, and which (cross-) correlations of these tracers to compute.
It would be helpful if the CCL contained the necessary data structures and book-keeping code, as this will likely be common at least to LSS and WL.

Here are some ideas for the data structure, but it would be good to hear other ideas, and think about how to make the book-keeping easy.

Minimum data structure:
- pointers for vectors of \ell and \theta bins
- flag whether to compute power spectra or correlation functions
- lists of the CCL_ClTracer structures (preferably separated by type) 
(all immutable)

optional1:
- specify which cross-correlations between CCL_ClTracers to evaluate
- tables and splines for auxillary, cosmology independent functions
- pointers to systematics models (grouped by tracer type)
(all immutable)

optional2:
- splined versions of the angular power spectra to speed up the correlation function compution
- parameters for systematics models
(mutable, to be updated as relevant parameters change)

Does the basic idea for the use case make sense, or would you describe this application differently?
For the minimum structure, is it OK to impose a maximum on the number tracers supported to make the allocation easy (rather than using linked lists, or C acrobatics to mimic dynamic array sizes)?
What other features should we plan for, and what other information should be stored?

**Comment by beckermr** [comment]
Is this covered by firecrown?

@elikrause @philbull 

If yes, let's close this issue then.

**Comment by beckermr** [comment]
I am closing this. Feel free to reopen if you all feel differently.
