### ISSUE TITLE
Implement connected contributions to cov matrix for an ideal experiment.

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/CCL#671]
As discussed in the #desc-tjp-cov slack channel, in the spirit of, "integrals live in CCL", we want to implement calculation of the connected part of covariance matrix in CCL. 

This will be for an idelized experiment that observes a given generalized tracer over a compact sky area given by fsky. For a specific binning and fsky, it will return the connected part of the covariance matrix (or quantities needed to make it) for:
 * super-sample covariance matrix arising due to coupling to the modes bigger than the survey
 * traditional non-Gaussian covariance arising due to 4-point coupling modes inside the survey

These calculations exist in various codes around, but should be ported and integrated into CCL. @damonge @sukhdeep1989 @joezuntz @philbull @c-d-leonard @jablazek

**Comment by beckermr** [comment]
This issue has both "disconnected" and "connected" in title and description. Which one is it?

**Comment by slosar** [comment]
I mean connected. For afficionados, a 4-point function that enters covariance is of the form

<x y w z> = <xy><wz>+<xw><yz>+<xz><yw> + <xywz>_c,

where <xywz>_c is the "connected part" (the above equation is its definition) and vanishes when x,y,w,z are normally distributed.

**Comment by beckermr** [comment]
Yup! I was just confused by the issue title because you were talking about parts of the connected bits but had disconnected in the title.

**Comment by c-d-leonard** [comment]
@slosar @sukhdeep1989 is it still the plan that these parts of covariance functionality live in CCL or has this changed?

**Comment by slosar** [comment]
It's still the plan!

**Comment by carlosggarcia** [comment]
@damonge I think this is ready to be closed?

**Comment by damonge** [comment]
yes!
