### ISSUE TITLE
ENH allow mu-Sigma model for any transfer function / power spectrum

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#673]
Right now we can only call mu-Sigma for CLASS and the linear power spectrum. We should allow people to do anything.

**Comment by joezuntz** [comment]
This can get very ambiguous - the mu/Sigma ansatz is only defined for linear perturbations, and doesn't necessarily have meaning elsewhere.  Whatever we do should at the very least make this clear to users.

**Comment by beckermr** [comment]
We cannot coddle our users. If people do something dumb, they do something dumb.

**Comment by joezuntz** [comment]
If we produce a code that claims it is generating the correct non-linear matter power spectrum for a mu-Sigma, then that code is lying.  This is not good.

**Comment by beckermr** [comment]
I never claimed the code is correct nor should we.
