### ISSUE TITLE
Installation requires more specific version of cmake than documentation describes?

### ISSUE THREAD

**Issue by mclaughlin6464** [LSSTDESC/CCL#686]
I was installing pyccl via PyPi on the Stanford's Sherlock system. I was not able to get the package to install with cmake 3.13.1 or 3.8.1, but was able to with 3.11.1. The documentation says that only cmake > 3.2 is required. The installation errors I got when installing with other version of cmake were vague. Not sure if this issue applies to other folks, but happy to try to reproduce some errors if that is helpful.

**Comment by elisachisari** [comment]
@mclaughlin6464 Could you try this again with CCL v2 and report back if the problem still stands?

**Comment by c-d-leonard** [comment]
@mclaughlin6464 any update on this?

**Comment by nikfilippas** [comment]
Closing as outdated.
