### ISSUE TITLE
Error in CCL when running MCMC

### ISSUE THREAD

**Issue by YaoQianli** [LSSTDESC/CCL#696]
Hello,

I was using emcee for MCMC and CCL for the angular power spectrum, similar to the examples provided in the CCL jupyter-notebook. After 500 to 800 steps of the MCMC (depending on different data I use), there is always an error:

> File "/home/jyao/anaconda2/envs/py3/lib/python3.7/site-packages/emcee/ensemble.py", line 259, in sample
  lnprob[S0])
File "/home/jyao/anaconda2/envs/py3/lib/python3.7/site-packages/emcee/ensemble.py", line 332, in _propose_stretch
  newlnprob, blob = self._get_lnprob(q)
File "/home/jyao/anaconda2/envs/py3/lib/python3.7/site-packages/emcee/ensemble.py", line 382, in _get_lnprob
  results = list(M(self.lnprobfn, [p[i] for i in range(len(p))]))
File "/home/jyao/anaconda2/envs/py3/lib/python3.7/site-packages/emcee/interruptible_pool.py", line 94, in map
  return r.get(self.wait_timeout)
File "/home/jyao/anaconda2/envs/py3/lib/python3.7/multiprocessing/pool.py", line 657, in get
  raise self._value
pyccl.errors.CCLError: Error CCL_ERROR_CLASS: ccl_power.c: ccl_cosmology_compute_power_class(): Error running CLASS background:background_init(L:657) :error in background_solve(ppr,pba);
=>background_solve(L:1587) :condition ((tau_end-tau_start)/tau_start < ppr->smallest_allowed_variation) is true; integration step: relative change in time =1.402088e-16 < machine precision : leads either to numerical error or infinite loop

Since it can run several hundred steps, I think in general the code is fine. And the cosmological parameters are with KiDS-VIKING prior, so no unreasonable values. Could you help me with this issue?

Thanks a lot,
Ji Yao

**Comment by damonge** [comment]
This sounds to me like a CLASS error, which usually would happen when you hit extreme cosmological parameter values. You should have a `try: except:` section in your code that catches this and returns `lnprob = -np.inf` when it happens.

**Comment by YaoQianli** [comment]
> This sounds to me like a CLASS error, which usually would happen when you hit extreme cosmological parameter values. You should have a `try: except:` section in your code that catches this and returns `lnprob = -np.inf` when it happens.

Hi David,

Thanks for the reply! Sorry I forgot to mention I tried this. Then after 4000 steps MCMC, the posterior appears to be very flat... I attached the steps of the parameters below. Is there a possible explanation?

![image](https://user-images.githubusercontent.com/21094443/68192143-dce67900-ffeb-11e9-8577-7585a78834ba.png)

Thanks,
Ji

**Comment by tmcclintock** [comment]
This plot ^ isn't that helpful because in addition to the y-axes not being labeled (meaning it's tough to tell what the parameters are) and because your stack trace doesn't say which walker failed (i.e. which line in the plot you made we should be looking at.

One thing you could do is run metropolis hastings (not the ensemble sampler) chains with a single walker and see where it dies. Another approach could be to sample your posterior at the edges and corners of your prior volume to see if any locations cause CLASS to fail.

**Comment by elisachisari** [comment]
@YaoQianli Could you maybe try CCL v2, where the default is CAMB? Or maybe try the BBKS option? This is just to see if the failure depends on the transfer function.

**Comment by c-d-leonard** [comment]
@YaoQianli , did you have any further updates on this issue?

**Comment by YaoQianli** [comment]
> @YaoQianli , did you have any further updates on this issue?

Yes. Sorry I forgot to update on this. I tried CCL v2 and used CAMB. This error is still there. I tried to skip it and print it out as David suggested above. It seems it happens when Omega_b and Omega_m are both very small. I was using the KiDS450 prior (something like 0.01<Omega_m h^2<0.99). When I get rid of the very small values things are fine.

**Comment by c-d-leonard** [comment]
Okay, do you know how small Omega_b and Omega_m had to be to cause this issue? Thanks

**Comment by YaoQianli** [comment]
> Okay, do you know how small Omega_b and Omega_m had to be to cause this issue? Thanks

Sorry, I didn't record the numbers... The time it reported an error was something like Omega_m~Omega_b~0.02, just a little bit larger than the lower limit of the prior.

**Comment by c-d-leonard** [comment]
Okay, thanks. I think it's worth keeping this issue open, ultimately we should probably understand why values that are technically within the prior range are causing an error.

**Comment by damonge** [comment]
I'll close this, as this seems more of a CLASS/CAMB than CCL issue (and it hasn't seen much activity in >2 years). Feel free to reopen.
