### ISSUE TITLE
Memory alloc error for cosmic emu power

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#698]
I'm getting a memory allocation error for the nonlinear matter power spectrum whenever I use the  emulator. This is for v2.0.1. Here is a snippet of code to reproduce the issue.

`import pyccl as ccl`
`import numpy as np`
`k=np.logspace(-2,1,100)`
`cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, sigma8=0.8, n_s=0.96, matter_power_spectrum='emu',Neff = 3.04)`
`test_power=ccl.power.nonlin_matter_power(cosmo, k, 1.)`

And the error I get:

![Screen Shot 2019-11-05 at 5 30 30 PM](https://user-images.githubusercontent.com/9137015/68226272-11f5ca00-fff2-11e9-8386-ec0d9e9e1e70.png)

**Comment by elisachisari** [comment]
I verified that both benchmarks tests and unit tests of the emulator are actually running. I also reproduced them in the terminal and got no issues. This mem alloc error only seems to appear for specific cosmologies.

**Comment by elisachisari** [comment]
Further narrowing down of this issue:
I get a crash for this cosmology: 
`cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, sigma8=0.8, n_s=0.96, matter_power_spectrum='emu',Neff = 3.04)`
But not for this one:
`cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.05, h=0.67, sigma8=0.8, n_s=0.96, Neff=3.04, transfer_function=None, matter_power_spectrum='emu')`
It seems we need to define the TF explicitly when the emulator is called. @beckermr is this intended/documented somewhere?

**Comment by damonge** [comment]
The values of Omega_b are different in both, right? Could that be the problem instead? (which would be very surprising, I agree)

**Comment by elisachisari** [comment]
Good catch! It's the Omega_b value indeed. It's not within emulator bounds, but CCL is throwing out a mem alloc error instead. We should fix this. I checked and the same thing happens for other parameters, for example passing w0=-0.6 (outside emulator bounds). So it's only the error message we need to fix.

**Comment by c-d-leonard** [comment]
It would be nice to fix this before tagging v3. @elisachisari you are the emulator expert, any chance you will have time? If not I can have a go.

**Comment by nikfilippas** [comment]
I made a quick fix for this in PR925, which includes several improvements unrelated to one another, but there's no easy way because the C-code does not support error propagation at the moment. At least now the error message (and some other errors with the emu) are more useful.

(Also removed it from a v3 milestone, or I couldn't link the PR with the issue for closing. Either way, error handling at the C layer has become so complicated that I think if this is tagged for v3, then v3 will have to wait forever.)
