### ISSUE TITLE
No Windows support

### ISSUE THREAD

**Issue by cmbant** [LSSTDESC/CCL#699]
Lack of Windows support seems not to be documented (e.g. in install instructions). 

I wasted a few hours seeing how far I could get towards making it work on Anaconda on Win64. There are Anaconda packages for the main dependencies FFTW, swig, gsl. In case it helps anyone else this fork commit https://github.com/cmbant/CCL/commit/6c77d626c0171bc0937c66f562a313e019ce8bf3 is as far as I got trying to compile with them installed  (compiles first step using Visual C, but fails on linking FFTw).

**Comment by elisachisari** [comment]
Thanks for reporting this. Indeed we do not support Windows. We've added this to the documentation now.
