### ISSUE TITLE
ENH add methods to get out effective quantities from tracers

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#712]
It would be very helpful to have canned methods to get out the effective IA bias as a function of redshift etc from the new tracer objects. 

@damonge for viz

**Comment by damonge** [comment]
The straightforward thing to return would be the kernel and transfer functions. Would that suffice?
For IA, the transfer function would be directly the IA bias.

![tracer_F](https://user-images.githubusercontent.com/8809493/69710854-0466c800-10f8-11ea-85b9-ed5f08ebd767.png)

**Comment by beckermr** [comment]
We should add specific methods/attributes for things set in the constructor.

**Comment by damonge** [comment]
hmmh... what would be the point of that?
If you called the constructor, you should have access to the arrays that you used to call it, right?

**Comment by beckermr** [comment]
Not necessarily.
