### ISSUE TITLE
PERF add OpenMP to the lensing tracer window function integrals

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#719]
This is the next thing taking time.

**Comment by c-d-leonard** [comment]
@beckermr silly question perhaps but how would the parallelization work? It's not obvious to me how to split this computation up into nicely separated bits (this might just be me not understanding how OpenMP works)

**Comment by damonge** [comment]
@c-d-leonard we need to compute W(r) at different values of r, so one could parallelize the loop over those rs.

**Comment by beckermr** [comment]
Yes I should have added more notes. There is a loop of integrals that can be done in parallel.
