### ISSUE TITLE
Support 2.7

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#721]
Should we keep supporting python2.7?

Pros:
- Maybe someone is still using it.

Cons:
- Our tests take twice as long to run on travis.

**Comment by damonge** [comment]
As part of this, we could use the following trick from @rmjarvis (quoting from slack):
```
allow_failures:
        - python: 2.7
fast_finish: true
```
This will run 2.7, but leave it for last and return success when 3.6 passes.
Testing this in #723

**Comment by elisachisari** [comment]
Merged with #723
