### ISSUE TITLE
Call to unit tests generates unnecessary warnings

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#738]
Some of our unit test checks are generating warnings. For example 
`pyccl/tests/test_halomodel.py::test_halomodel_power_consistent
  /Users/Chisa002/Documents/LSST/CCL/pyccl/pyutils.py:403: CCLWarning: The function twohalo_matter_power is deprecated. Use halomod_power_spectrum instead.
    warnings.warn(s, CCLWarning)`
This can be avoided by updating the functions used in those tests to the new ones.

**Comment by damonge** [comment]
In our discussion of those PRs we decided that it was a good idea to keep those tests to make sure the deprecated functions still do what they're supposed to do (until we deprecate them)

**Comment by elisachisari** [comment]
Alright, I gave this a "v3 milestone" label so we don't forget to update the tests.

**Comment by c-d-leonard** [comment]
Is the idea that we are definitely deprecating the old halo model functionality before tagging v3? if so, should we start a PR for this soon / now?

**Comment by nikfilippas** [comment]
This is one of the things addressed now in #889 . No extra warnings anymore!
Have a look at the output of the unit tests [here](https://github.com/LSSTDESC/CCL/pull/889/checks?check_run_id=3041168011) and if you're happy, we can close this.
