### ISSUE TITLE
Update 3d correlation function to allow for specification of Pk

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#743]
Right now, 3d Pk appears to only allow the standard nonlinear Pk. We want to allow for any Pk to be passed. Copying a summary from @sukhdeep1989 

>I just looked into ccl_correlation.c . The projected correlation functions take power spectra as input but the 3d_correlation does not. Within the function, it should be an easy change to move the power spectrum to the arguments. Will require some care for upstream functions that might be calling it. I also noticed that the projected correlation function assume angular coordinates. I think we can easily generalize it to use physical coordinates as well. Shouldn’t require much change in the code and could be as  simple as passing it  k, pk and rp, and then checking the output.

**Comment by sukhdeep1989** [comment]
@jablazek I just started a branch, correlation_issue743, for this issue. To begin with, I modified the ccl_correlation_3d function. I couldn't quickly figure out how to compile the current CCL version. Can you please check it or point me to the instructions. If changes to ccl_correlation_3d is acceptable, then we can modify the subsequent functions as well. 

For the projected correlation function, I noticed that ccl_tracer_corr_fftlog function is hard coded to assume angular (ell) space. I think we can add a new flag to the function call, e.g. int ell_k_space, and then select k or ell spline inputs based on that. As to how this can be exposed to user, we can either add the same flag to ccl_correlation function or we can create two copies of this function, ccl_correlation2D_angular and ccl_correlation2D_physical. I think we should also add 2D to the function name. I prefer the latter (creating 2 functions). In ccl_correlation2D_physical, we can also add the method to account for RSD effects (eq. 15-18 in https://arxiv.org/pdf/2001.07700.pdf ).

**Comment by jablazek** [comment]
linking to #815 and #219

**Comment by jablazek** [comment]
Was speaking with @sukhdeep1989 earlier today about these related issues. It appears that there are two routes in CCL to calculate the correlation function.
1) the standard `ccl.correlation` which takes C_ell as input rather than Pk and so is currently only able to do angular correlation functions. However, it can handle general correlations using the general Pk functionality.
2) the 3d correlation function, which is hard-coded to use the CAMB nonlinear Pk (I believe). We will need to re-write this to be exposed to the general Pk.

We also want w_p(r_p) functionality, which can be done easily from (2), if the call to FFTLog can use different bessel functions.

**Comment by damonge** [comment]
We already do this!
