### ISSUE TITLE
How works pk2d module?

### ISSUE THREAD

**Issue by lingoglia84** [LSSTDESC/CCL#747]
As a PhD student in Federico II university (Naples) working in WL, I aim to compare my numerical projected power spectrum computed in Hoekstra+03 (https://ui.adsabs.harvard.edu/abs/2003MNRAS.339.1155H/abstract, eq.14) with the pk2d class in this module. I did not understood how does this class actually work: it provides a function called "eval" supposed to return the value of pk2d. This function computes from Pk2D (setting matter power spectrum), and input the wavenumber "k" and the distance "a", while the projected power spectrum is assumed to be dependent of the multipole "l" and evaluated for a given distribution of galaxy redshifts "pw" ("w" is the comoving radial distance of galaxy). I don't find any clue in CCL paper about how it works. 
If this is possible, could you please provide a short example on python in which you show how to use that class? Otherwise any brief explanation would be welcomed.
Thank you in advance.

**Comment by damonge** [comment]
Hi there

Pk2D objects are meant to store information about power spectra for three-dimensional quantities P(k,a). See for instance the documentation [here](https://ccl.readthedocs.io/en/latest/api/pyccl.pk2d.html) and cells 14 and 15 [here](https://github.com/LSSTDESC/CCLX/blob/master/GeneralizedTracers.ipynb).

I believe what you actually want is angular power spectra. These are documented [here](https://ccl.readthedocs.io/en/latest/api/pyccl.cls.html) and you can see several examples using them in our CCLX repo (e.g. [here](https://github.com/LSSTDESC/CCLX/blob/master/CellsCorrelations.ipynb))

**Comment by lingoglia84** [comment]
Thank you very much for your reply. Yes I'm interested in that function returning the projection of 3D power spectrum in the lensing frame.

**Comment by elisachisari** [comment]
This seems to be resolved so I'm closing it.
