### ISSUE TITLE
Check docs of halo mass function

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#762]
I think there is a mismatch in v2 between the mass function output: dn/dM, and the docs, which say that we are outputting dn/dlog10M (though in the units of dn/dM). Could we check this in master as well? @damonge @villarrealas

**Comment by damonge** [comment]
I'm pretty sure we return dn/dlog10M (and that's what we've always returned)

**Comment by damonge** [comment]
And the units should be Mpc^-3. Just checked that's what the docs say.

**Comment by elisachisari** [comment]
So the only problem is with the units here in v2?
https://github.com/LSSTDESC/CCL/blob/v2.0.0/src/ccl_massfunc.c

**Comment by damonge** [comment]
Ah, yes, those were wrong. Oh well

**Comment by elisachisari** [comment]
Alright, no problem - those docs don't face the public and all of this is gone in current master, so we can close this issue.
Bottom line: we always return dn/dlog10m.
