### ISSUE TITLE
"Lightweight" developer install for python updates?

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#772]
I have had persistent problems with developer installation using `cmake`. I suspect that some of these issues are related to mac OS X, and especially the increase of built-in restrictions, although I'm not sure. Installation of released CCL with `conda` is easy.

Since most new developer features are pure python, can there be a developer install for python-only features that doesn't touch `cmake`? Or does something like this exist already?

**Comment by EiffL** [comment]
Well...... in principle..... people could install the c library with conda, and then just work on the python+interface part as much as they want as long as they don't touch the C part.

I'm not a big fan of this however... But this being said, I know I failed to help you last time @jablazek  so if it means that in practice it makes CCL more usable....

**Comment by EiffL** [comment]
At the very least you need to keep the compilation of the SWIG interface with the python code, so there is still some compilation required.

**Comment by beckermr** [comment]
We could make it easy to compile CCL using the conda compilers. This would help I bet.

**Comment by EiffL** [comment]
yep I like that, if we can rely on conda to grab all dependencies and compilers, it should be a piece of cake. I don't have a Mac, I don't know how easy it is to set that up, with respect to PATHs and stuff, to avoid mixups with system tools

**Comment by beckermr** [comment]
I’ll make a pr on the docs and makefile.
