### ISSUE TITLE
Built-in NLA vs calculation with generalized tracers and nl_pt

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#773]
This issue is linked to this PR in CCLX: https://github.com/LSSTDESC/CCLX/pull/17
for the notebook: `PerturbationTheoryPk.ipynb`

I have found two things. They are probably separate, but there might be a connection, so I will put them together here.

**Comment by jablazek** [comment]
1) When defining the PTTracers, the z range is less than the z range later required by the n(z) of the Tracers. If passing a constant bias, this seems to be not a problem. `get_pt_pk2d` by default does the following:
>if a_arr is None:
        status = 0
        na = lib.get_pk_spline_na(cosmo.cosmo)
        a_arr, status = lib.get_pk_spline_a(cosmo.cosmo, na, status)
        check(status)

**Comment by jablazek** [comment]
2. When I compare the built-in NLA C_ells from WLTracers with what I get using nl_pt and generalized power spectra, I get differences of a few percent when I have a broad n(z) (e.g. sigma_z = 1). This seems to be partly due to extrapolation in z as mentioned above, but only partly. I tested increasing the input z range, and much of the difference persists.

For a narrow z range (e.g. sigma_z = 0.1), the difference between the two methods is much smaller - 1e-5 to 1e-7, depending on the ell.

I will keep looking into this. Ideas?

**Comment by jablazek** [comment]
@elisachisari : can you point me towards the built-in NLA normalization? or paste it here?

**Comment by jablazek** [comment]
UPDATE: It looks like much of the issue happens when n(z) is non-trivial near its edge. The two methods must be treating the edge differently. This is especially true at z=0, much more than z=zmax.

**Comment by jablazek** [comment]
UPDATE: This is almost certainly related to how `get_pt_pk2d` creates the Pk interpolation. If I instead pass P_NL calculated in the standard ccl way as a generalized power spectrum (i.e. skip the path through `nl_pt`) the agreement is back to 1e-5 or better.

It's definitely NOT related to the internal IA normalization. Using that vs. the normalization calculated by hand gives ratios of exactly 1.

**Comment by jablazek** [comment]
There is also a difference in how the k extrapolation is done. Internally, the nl_pt grid defaults to log10k = -4 to 2. Extrapolation beyond this AFTER the pk2d object is created must be done different than when CCL evaluates power spectra, e.g. with `ccl.nonlin_matter_power`. Is this something people understand?

**Comment by c-d-leonard** [comment]
Good to see you narrowed this down a little. @damonge can probably best answer questions about pk2d?

**Comment by damonge** [comment]
Sorry I've only been able to get to this now. I've read the above but I'm not sure what the problem really is. @jablazek Is there a code reproducing the problem I could look at?

**Comment by jablazek** [comment]
@damonge : see `JAB_updates` branch in CCLX. The PerturbationTheoryPk notebook has the  NLA C_ells calculated a few different ways. They should agree, but in some cases don't. I have been exploring with this, so it isn't very well documented right now.

**Comment by c-d-leonard** [comment]
@jablazek is this still work in progress?

**Comment by jablazek** [comment]
@c-d-leonard : indeed it is. Fell down a bit on my to-do list, but will revisit asap.

**Comment by jablazek** [comment]
update for @c-d-leonard @damonge @elisachisari : I think I have diagnosed the issue, but I'm not sure what the best solution is. In the nl_pt/power.py, we use `is_logp = False` when creating the Pk2d interpolation object. I *think* that the built-in power.py uses the equivalent of `is_logp = True` (although this is buried in the C library so not transparent to me).

It's good that we aren't using logp, since the PT calcs can yield negative Pk in some cases. But, as a result, the extrapolations are no longer nicely behaved power laws and instead appear to be roughly exponential fall-off, as you would expect with a semi-log linear extrapolation.

When the highest or lowest k values are relevant, the extrapolation difference becomes important.

I'm not sure how to best fix this. We don't want to require all PT calcs be done on a wider k range. We could wrap the output in a power-law extension function before passing it to `Pk2d`.  Or maybe there is a different extrapolation setting we could use in the `Pk2d` function itself.

**Comment by damonge** [comment]
Ok, but if someone needs the Pk at those scales, they shouldn't rely on any extrapolation anyway, right? Isn't this just solved by users using a broader k range if they need those scales?

**Comment by jablazek** [comment]
Well, we could add a function inside the nl_pt layer that extends the power spectra with a power law before passing it to PK2D. But we probably want to avoid requiring a wider range in k for the actual PT calculations.

Of course, in practice, if we are sensitive to Pk outside the range logk = -4 to 2, we probably can't trust those predictions anyway.

**Comment by jablazek** [comment]
The important extrapolation is at the high k end when the source n(z) has non-trivial support at z=0. In this case, high k (e.g. above log10k=2) contributes at all ell, and especially at high ell. This may not be important in too many cases.

I still think we should call the Pk2D in such a way that it does the same power-law or taylor expansion extension as with the camb/class output. We have something in FAST-PT that does a power law extension which we could use as well, but the fewer new functions we introduce to do existing things, the better.

**Comment by jablazek** [comment]
I think we have isolated this issue, so will close and open the specific issue in #816.
