### ISSUE TITLE
Add minimal isitgr install instructions to readthedocs

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#777]
It would be useful to have some pointers here:
https://ccl.readthedocs.io/en/latest/source/installation.html
as we do for FAST-PT.

**Comment by mishakb** [comment]
Agreed! I added some instructions on how to install isitgr via pip or conda in: 
https://github.com/LSSTDESC/CCL/pull/778. 
@elisachisari, let me know what you think.

**Comment by c-d-leonard** [comment]
@mishakb @elisachisari has this been resolved now? can we close this issue?

**Comment by c-d-leonard** [comment]
Great
