### ISSUE TITLE
ERROR STOP Fluid dark energy model does not allow w crossing -1

### ISSUE THREAD

**Issue by Andromedanita** [LSSTDESC/CCL#779]
I am using CCL installed on NERSC which is version 2.1.0 and when I try to calculate P(k, z) I get this error: 
> ERROR STOP Fluid dark energy model does not allow w crossing -1

which is due to CAMB using Fluid DE model instead of the PPF.

This is the cosmology I used:
cosmo =  ccl.Cosmology(Omega_c= 0.2139426, Omega_b=0.0441039, h=0.719, n_s=0.95, 
          sigma8=0.8, Omega_k=0.0, Omega_g=None, 
         w0=-1., wa=-0.01, transfer_function='boltzmann_camb', 
         matter_power_spectrum='halofit')

Is there an easy way to switch CAMB to use PPF model in CCL?

**Comment by c-d-leonard** [comment]
@Andromedanita just wondering how you're getting on with this or if you need any support?

**Comment by Andromedanita** [comment]
I was just wondering if it would be possible to get someone who knows C better than me on this?

**Comment by damonge** [comment]
@Andromedanita don't know enough about CAMB. How would you normally ask CAMB to use PPF? It should be possible to pass that through python without touching the C code.

**Comment by damonge** [comment]
And this would be the function to look at/modify: https://github.com/LSSTDESC/CCL/blob/641ba87226565f1f8c894f8d4570127c53fdec76/pyccl/boltzmann.py#L27

**Comment by Andromedanita** [comment]
@damonge Thanks for your response. In CAMB itself there is a parameter in the param.ini file that we can set to choose which DE model to use. So I basically just set "dark_energy_model = PPF" instead of fluid which is the default option.
Would I need to add "cp.dark_energy_model = PPF" similar to line 77 of the code you mentioned?

Also, this might sound stupid but I am currently using CCL that is already installed on NERSC and I have had issues installing it locally before so I am not sure how I can test and use it.

**Comment by damonge** [comment]
I think you'd need to modify [this line](https://github.com/LSSTDESC/CCL/blob/641ba87226565f1f8c894f8d4570127c53fdec76/pyccl/boltzmann.py#L133) specifically, and change it into `dark_energy_model=camb.dark_energy.DarkEnergyPPF`

Unfortunately you need to modify ccl for this, so you will need to install a new version yourself...

We can probably help with installation issues.

**Comment by Andromedanita** [comment]
Okay thank you. I will try installing it again and ask for help.
Also, is there a way to know what version of CAMB CCL uses? I think the ppf option is not available in older versions

**Comment by damonge** [comment]
it'll use whatever version of CAMB you have installed

**Comment by c-d-leonard** [comment]
I know @Andromedanita is having some trouble with the installation here and adding this as an option seems like a pretty straightforward fix for someone looking for a straightforward way to contribute. @t-ferreira, I know I've seen you at a few meetings recently, want to give this a go? I am sure me and @damonge will be able to answer general CCL questions and @Andromedanita will be available to discuss the specifics of the options she is looking to have added.

**Comment by t-ferreira** [comment]
Yes, I would be happy to look into it!

**Comment by c-d-leonard** [comment]
Great! I'm here to help if you need anything, let me know @t-ferreira

**Comment by Andromedanita** [comment]
Just following up to see if there is anything I can do to help with this issue :)

**Comment by Andromedanita** [comment]
Hi @c-d-leonard and @t-ferreira I just wanted to follow up on the status of this issue and see if there is anything I can do to help. Thanks

**Comment by t-ferreira** [comment]
Hi @Andromedanita I just created a pulll request where I added an option where you can choose your dark energy model as an optional argument in Cosmology. It works with your example!

Are you still having trouble with your local installation?

**Comment by Andromedanita** [comment]
Thanks so much  @t-ferreira ! Yeah I am not able to install it locally unfortunately! Not sure how I can use this option if its not integrated to the main code installed on NERSC

**Comment by c-d-leonard** [comment]
This should be solved with PR #857 being merged so I'm closing this issue.

**Comment by am610** [comment]
Hi, checking with others, I have the same error, so can someone summarize, what to do ?
