### ISSUE TITLE
Use PP constants

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#78]
We've noticed differences at >1e-4 between PP constants (currently implemented in CCL), CLASS constants and GSL constants. (G is one example.) We have agreed the best is to use PP constants and we need to contact the CLASS developers to ask them to incorporate these as well if possible.

**Comment by matthewkirby** [comment]
I ran comparisons between the constants in CCL and some other sources. The results are attached.

<img width="347" alt="screen shot 2017-07-14 at 1 27 55 pm" src="https://user-images.githubusercontent.com/5395125/28223235-a48ad32c-6898-11e7-847e-5318cba67280.png">

I submitted a PR where Msun is fixed to be the GSL value and rho_crit is derived.

**Comment by matthewkirby** [comment]
#

**Comment by tmcclintock** [comment]
This is a great analysis, @matthewkirby. Thanks for doing this.

**Comment by tmcclintock** [comment]
By the way, @matthewkirby make sure you cross-link the issue like so: #241 when you issue the PR, so it's slightly easier to locate the issue.
