### ISSUE TITLE
transfer_function to have boltzmann option to automatically choose CAMB/CLASS

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/CCL#781]
At the moment `transfer_function` is either `boltzmann_class` or `boltzman_camb` and if it is not set to whichever backend you have installed it would barf. It would be great to have an option `boltzmann` which would deafult to whichever backend you have. Or `boltzmann_any` or even `boltzmann_i_dont_give_a_shit` to be more explicit.

**Comment by beckermr** [comment]
I would think hard about these options. This one would make the actual numbers produced by CCL dependent in a serious way on the local environment. That could easily make things not reproducible and confusing. Explicit and annoying is better here.

**Comment by slosar** [comment]
Good point.
