### ISSUE TITLE
Malloc when computing NG correlation with separated redshift bins

### ISSUE THREAD

**Issue by ChristopherAJDuncan** [LSSTDESC/CCL#785]
Where the foreground redshift bin in a NG (galaxy-galaxy lensing) signal is at higher redshift than the background, and there is no overlap between the redshift distribution and lensing kernel, the NN signal is zero in power and correlation in the absence of a magnification signal. Where magnification is included, this is non-zero.

I am finding that where magnification is not included, that attempting to compute the correlation gives a memory error:
> `python3(62761,0x108f22dc0) malloc: *** error for object 0x1: pointer being freed was not allocated`
> `python3(62761,0x108f22dc0) malloc: *** set a breakpoint in malloc_error_break to debug`

which causes the kernel to crash.

This only happens when calculating the correlation (which should be zero): the spectrum (also zero) is computed without issue. 

Note that if magnification is turned on, this is not a problem.

It should be easy for the user to avoid this by coding a test based on the returned spectrum, but it would be beneficial for the code to supply a zero signal without interference from the user.

I have a Jupyter notebook that demonstrated this, but unfortunately I don't know the best way to supply this in an issue. If there is a way, I'm happy to.

Thanks!

**Comment by elisachisari** [comment]
Thanks for reporting this! Can you attach the notebook file (or a pdf of it) in here? (Drag and drop into the comment window.)

**Comment by c-d-leonard** [comment]
@ChristopherAJDuncan - just bumping this. Could you post a pdf of the notebook? As Elisa said this should work by just dragging it into the comment text box.

**Comment by ChristopherAJDuncan** [comment]
Unfortunately the straight ipynb isn't supported. ("We don't support that file type"). I've added as txt below (my jupyter won't output as PDF for some reason... and HTML is also not supported).

It's a bit messy with some sleep statements etc for testing, but it should be fairly obvious. Let me know if not.

If PDF would be much easier then let me know, and I can try and sort that out...
[bugged_ccl.txt](https://github.com/LSSTDESC/CCL/files/4858990/bugged_ccl.txt)

**Comment by c-d-leonard** [comment]
Hi @ChristopherAJDuncan , a bug-fix has just been merged into master for a similar issue - could you check if this solves you problem?

**Comment by c-d-leonard** [comment]
Hi @ChristopherAJDuncan - right, so we only would update the pip version when there is a new release, so this bugfix is not in the pip version yet. To check if it works, you'd want to clone master and install it directly.

**Comment by ChristopherAJDuncan** [comment]
Sorry for delay in doing this. I put in my own hack, but unfortunately in the process of fitting cosmologies there were certain combinations that caused this to come up again (circumventing my hack).

I cloned the master and reinstalled (though unless I'm missing something, there isn't much guidance on source installations, although there didn't seem to be an issues.) I no longer get malloc errors for this case, but I get another:

`/Users/Shared/env/astro/lib/python3.6/site-packages/pyccl-2.1.1.dev78+g46692a38-py3.6.egg/pyccl/correlation.py in correlation(cosmo, ell, C_ell, theta, type, corr_type, method)
    105                                           correlation_methods[method],
    106                                           len(theta), status)
--> 107     check(status, cosmo_in)
    108     if scalar:
    109         return wth[0]

/Users/Shared/env/astro/lib/python3.6/site-packages/pyccl-2.1.1.dev78+g46692a38-py3.6.egg/pyccl/pyutils.py in check(status, cosmo)
     46     # Check for known error status
     47     if status in error_types.keys():
---> 48         raise CCLError("Error %s: %s" % (error_types[status], msg))
     49 
     50     # Check for unknown error

CCLError: Error CCL_ERROR_SPLINE: ccl_correlation.c: ccl_f1d_t_new failed to create spline`
