### ISSUE TITLE
CAMB vs BBKS mismatch on simple LCDM?

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/CCL#786]
So, I must be doing something wrong or missing something very obvious, but I get a large disagreement between the BBKS and CAMB transfer Pks in a simple cosmoloy without neutrinos:

```python
import pyccl as ccl

cosmo_bbks = ccl.Cosmology(
    Omega_c=0.25, Omega_b=0.05, h=0.7, sigma8=0.8, n_s=0.96, Neff=0,
    transfer_function='bbks', matter_power_spectrum='linear', Omega_g=0.0, 
    Omega_k=0, T_CMB=2.7, m_nu=0.0, m_nu_type='normal'
    )

cosmo_camb = ccl.Cosmology(
    Omega_c=0.25, Omega_b=0.05, h=0.7, sigma8=0.8, n_s=0.96, Neff=0,
    transfer_function='boltzmann_camb', matter_power_spectrum='linear', Omega_g=0.0, 
    Omega_k=0, T_CMB=2.7, m_nu=0.0, m_nu_type='normal'
    )

k = np.logspace(-3, 0, 512)

pk_bbks = ccl.linear_matter_power(cosmo_bbks, k, 1.0)
pk_camb = ccl.linear_matter_power(cosmo_camb, k, 1.0)
```

![image](https://user-images.githubusercontent.com/861591/83775542-5b40f180-a687-11ea-9682-84b46a419442.png)

Any ideas what I'm doing wrong?

**Comment by EiffL** [comment]
In the example above, if change the following line:
https://github.com/LSSTDESC/CCL/blob/31dc0c911dc9f7f8cdf0389799554c274c1acc9b/pyccl/boltzmann.py#L157
by:
```python
k *= (0.8 * cosmo['h'])
```

It looks like I recover the correct amplitudes at both small and large scales:
![image](https://user-images.githubusercontent.com/861591/83814916-7f202980-a6bf-11ea-8aef-01e0244bd6e3.png)

Here is a notebook to try it out:
https://gist.github.com/EiffL/f99c19b2a9d02018d34b5152e0c2bee7

So it looks to me like a problem of unit conversions between camb and CCL. Any thougts/ideas/comments @beckermr ?

**Comment by beckermr** [comment]
Our code passed all of the benchmarks, so this is very confusing.

**Comment by elisachisari** [comment]
Have we ever done a BBKS vs CAMB comparison though? The original benchmarks for the BBKS power spectrum simply came from different users' implementations of BBKS. Then we added CLASS & CAMB. We have a consistency check between those two, but do we have anything else that could catch this?

**Comment by EiffL** [comment]
Yeah, I don't see a check for consistency between analytic PS and Boltzmann codes. For what it's worth, BBKS/EH seem to agree with each other on one hand, and CLASS/CAMB on the other hand.
I get the same result to EH with my own code, so I would say this one is ok, and then it must be a unit conversion problem, when CCL converts to `h`-less units. I just can't figure out why though, it looks ok when reading the `boltzmann.py` code....

**Comment by EiffL** [comment]
Ok, hold on >.< I think I was indeed doing something stupid which would explain why it didn't make sense ^^' 

In the example above I was naively trying to compare the PS without neutrinos, so I grabbed an example CCL config from a BBKS test, and just replaced the transfer function with CAMB. But, I had `Neff=0`, which CAMB didn't complain about, but which was apparently causing the issue. with the same config, CLASS wouldn't run. 

Now I get good agreement if I use the following config:
```python
cosmo_bbks = ccl.Cosmology(
    Omega_c=0.25, Omega_b=0.05, h=0.7, sigma8=0.8, n_s=0.9, Neff=3.046,
    transfer_function='bbks', matter_power_spectrum='linear', Omega_g=0.0, 
    Omega_k=0, T_CMB=2.7, m_nu=0.0, m_nu_type='normal'
    )
```
and just replace the transfer function:
![image](https://user-images.githubusercontent.com/861591/83858356-a78a4100-a71c-11ea-96f0-df1a8fd51189.png)

So, false alarm I think, as I was suspecting it's mostly me not knowing what I was doing. 

So that this is issue wasn't a total waste of time ^^' :
- Could I add a check somewhere that ensures a correct set of params is being sent to CAMB?
- Should I add a consistency check between analytic and boltzmann codes? If so, what test params would you recommend?

**Comment by beckermr** [comment]
Ahh yes. This makes sense. 

> Should I add a consistency check between analytic and boltzmann codes? If so, what test params would you recommend?

sure if you want

**Comment by beckermr** [comment]
As for correct camb params, IDK what camb thinks when we send if Neff=0. What did you think it was supposed to mean?

**Comment by EiffL** [comment]
I didn't think it through, didn't pay attention to it. CLASS, when I eventually managed to download the repo and install it, yelled at me with the following message:
```
Error in Class: thermodynamics_init(L:339) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:1695) :condition (DeltaNeff < deltaN[0]) is true; You have asked for an unrealistic small value of Delta N_eff = -3.046000e+00. The corresponding value of the primordial helium fraction cannot be found in the interpolation table. If you really want this value, you should fix YHe to a given value rather than to BBN
```
I guess I'm OK with saying if the user provides a stupid set of params, they get a stupid answer. But if there is a simple way to check the neutrino parametrisation is ok in CCL, may save some time for some people down the line.

**Comment by beckermr** [comment]
Right. @c-d-leonard has been working on the neutrino param a lot. Maybe she can weigh in?

**Comment by EiffL** [comment]
ok this was actually not a bug, I'm gonna close it because looks unlikely I'll get to adding these extra checks in the near future :-|
