### ISSUE TITLE
Use 2D (k,z) interpolation for linear power spectra

### ISSUE THREAD

**Issue by elikrause** [LSSTDESC/CCL#79]
Currently CCL only evalulates the linear power spectrum at z=0, and rescales to other redshifts using the growth factor.
This scaling is not exact for all cosmologies (e.g., massive neutrinos), and we should switch to a 2D (k,z) look-up table, as done for the non-linear power spectrum.

**Comment by pennalima** [comment]
Comparing CCL and NumCosmo, which already implements the 2D (k, z) spline for P(k, z), we noticed that the 5e-5 required precision fails: 
- sigma at z > 0.8 and is attained between 0 <= z < 0.8 and  0.1 < R < 100;
- dlnsigma_dlog10M at z > 0.8 and is attained between 0 <= z < 0.8 and  0.3 < R < 100, if the interval for R starts at 0.1 then it already fails at z = 0.

The lower bound for R is controlled by K_MAX_SPLINE. But even if we increase its value, we still have problems at high z (z ~1).
