### ISSUE TITLE
Interpolation error when calling pyccl.angular_cl with halo model

### ISSUE THREAD

**Issue by yanzastro** [LSSTDESC/CCL#802]
When I calculate the angular power spectrum with halo model, an error comes up:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-615-c4efe061c341> in <module>
      1 cosmo = ccl.Cosmology(Omega_c=Omc, Omega_b=Omb, h=H0/100., sigma8=sigma8, n_s=ns,
      2                               T_CMB=2.7255, matter_power_spectrum='halo_model')
----> 3 ccl.angular_cl(cosmo, gal_tracer, gal_tracer, gylbins)

~/.local/lib/python3.6/site-packages/pyccl/cls.py in angular_cl(cosmo, cltracer1, cltracer2, ell, p_of_k_a, l_limber, limber_integration_method)
     67         # if a power spectrum was not passed, we need the non-linear one
     68         # at the C level
---> 69         cosmo_in.compute_nonlin_power()
     70 
     71     # Create tracer colections

~/.local/lib/python3.6/site-packages/pyccl/core.py in compute_nonlin_power(self)
    870                 "spectrum is deprecated. Use the more general functionality "
    871                 "in the `halos` module.", category=CCLWarning)
--> 872             psp_py = self._get_halo_model_nonlin_power()
    873             psp = psp_py.psp
    874 

~/.local/lib/python3.6/site-packages/pyccl/core.py in _get_halo_model_nonlin_power(self)
    824         prf = hal.HaloProfileNFW(c)
    825         hmc = hal.HMCalculator(self, hmf, hbf, mdef)
--> 826         return hal.halomod_Pk2D(self, hmc, prf, normprof1=True)
    827 
    828     def compute_nonlin_power(self):

~/.local/lib/python3.6/site-packages/pyccl/halos/halo_model.py in halomod_Pk2D(cosmo, hmc, prof, prof_2pt, prof2, p_of_k_a, normprof1, normprof2, get_1h, get_2h, lk_arr, a_arr, extrap_order_lok, extrap_order_hik)
    545                                     prof2=prof2, p_of_k_a=p_of_k_a,
    546                                     normprof1=normprof1, normprof2=normprof2,
--> 547                                     get_1h=get_1h, get_2h=get_2h)
    548 
    549     pk2d = Pk2D(a_arr=a_arr, lk_arr=lk_arr, pk_arr=pk_arr,

~/.local/lib/python3.6/site-packages/pyccl/halos/halo_model.py in halomod_power_spectrum(cosmo, hmc, k, a, prof, prof_2pt, prof2, p_of_k_a, normprof1, normprof2, get_1h, get_2h)
    427         # Compute first profile normalization
    428         if normprof1:
--> 429             norm1 = hmc.profile_norm(cosmo, aa, prof)
    430         else:
    431             norm1 = 1

~/.local/lib/python3.6/site-packages/pyccl/halos/halo_model.py in profile_norm(self, cosmo, a, prof)
    132         """
    133         # Compute mass function
--> 134         self._get_ingredients(a, cosmo, False)
    135         uk0 = prof.fourier(cosmo, self._prec['k_min'],
    136                            self._mass, a, mass_def=self._mdef).T

~/.local/lib/python3.6/site-packages/pyccl/halos/halo_model.py in _get_ingredients(self, a, cosmo, get_bf)
     93         if a != self._a_current_mf:
     94             self.mf = self._massfunc.get_mass_function(cosmo, self._mass, a,
---> 95                                                        mdef_other=self._mdef)
     96             self.mf0 = (self._rho0 -
     97                         self._integrator(self.mf * self._mass,

~/.local/lib/python3.6/site-packages/pyccl/halos/hmfunc.py in get_mass_function(self, cosmo, M, a, mdef_other)
    151         rho = (lib.cvar.constants.RHO_CRITICAL *
    152                cosmo['Omega_m'] * cosmo['h']**2)
--> 153         f = self._get_fsigma(cosmo, sigM, a, 2.302585092994046 * logM)
    154         mf = f * rho * dlns_dlogM / M_use
    155 

~/.local/lib/python3.6/site-packages/pyccl/halos/hmfunc.py in _get_fsigma(self, cosmo, sigM, a, lnM)
    477         ld = np.log10(self._get_Delta_m(cosmo, a))
    478         nu = 1.686 / sigM
--> 479         pa = self.pa0(ld) * a**(-0.27)
    480         pb = self.pb0(ld) * a**(-0.20)
    481         pc = self.pc0(ld) * a**0.01

~/jupyter_py3/lib/python3.6/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

~/jupyter_py3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    661         y_new = self._call(self, x_new)
    662         if not self._extrapolate:
--> 663             below_bounds, above_bounds = self._check_bounds(x_new)
    664             if len(y_new) > 0:
    665                 # Note fill_value must be broadcast up to the proper size

~/jupyter_py3/lib/python3.6/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    690         # !! Could provide more information about which values are out of bounds
    691         if self.bounds_error and below_bounds.any():
--> 692             raise ValueError("A value in x_new is below the interpolation "
    693                              "range.")
    694         if self.bounds_error and above_bounds.any():

ValueError: A value in x_new is below the interpolation range.

It seems that the error has something with wrong scipy version but I'm not sure. Anyone could help me?

**Comment by damonge** [comment]
Hi @yanzastro 

it's not easy to tell without a code snippet, but my guess is that you're using one of the Tinker mass functions with an overdensity parameter that falls outside of the range of values for which these mass functions were calibrated. This happens often if you're trying to change from critical to matter overdensity mass definitions, or if you're using the virial overdensity (this one can easily become < 200, which is the lower limit for the Tinker parametrization).

**Comment by c-d-leonard** [comment]
It seems like this has been resolved; I'm going to close this issue (@yanzastro please re-open if you disagree)
