### ISSUE TITLE
Halo model covariances

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#806]
Discussing with @anicola on what we need to have non-Gaussian covariances within the halo model:

 - We need an `I_0_4` method in the `HMCalculator` to compute the 1-halo trispectrum. It will be a function of 2 wavenumbers and the scale factor.
 - We need a `I_1_2` method which is part of the power spectrum response. In principle this depends on 2 wavenumbers but the SSC only needs the case where both wavenumbers are the same. Still, because we need this quantity also for the n-halo terms, we will implement it in general, and allow it to calculate it more efficiently in the SSC case.
 - We need to compute the derivatives of `P_linear` wrt wavenumber. This may be easy since `P_lin` is stored as a GSL spline, so we just need to write a function that uses https://www.gnu.org/software/gsl/doc/html/interp.html#c.gsl_spline2d_eval_deriv_x.

The n-halo terms should be included in a different PR.

**Comment by c-d-leonard** [comment]
Progress report on this @damonge ? I'm a bit lost with all the different PRs on this :)

**Comment by damonge** [comment]
Right, this pertains mostly the 1-halo trispectrum (which was already implemented in #833) and the SSC (which is being done in #855). The work in #869 is to implement one of the n-halo terms.

**Comment by c-d-leonard** [comment]
Okay great. What about the derivatives of the power spectrum mentioned?

**Comment by damonge** [comment]
Those are needed for the SSC (and they've been implemented in that branch)
