### ISSUE TITLE
nu_masses returns nan sometimes

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#807]
We need to add a check in the python layer in nu_masses which throws an error if you pass a combination of Omeganuh2 and the mode of neutrino splitting which is not physical. Right now it returns nan or a meaningless error.

This is because this test used to be in the C layer and now relies on checks at a python level which haven't ever been added in this function.

**Comment by nikfilippas** [comment]
@c-d-leonard doesn't [this](https://github.com/LSSTDESC/CCL/blob/master/src/ccl_neutrinos.c#L284) line in `ccl_neutrinos.c` already solve this issue?
