### ISSUE TITLE
Correlation functions using built-in Pk->corr 

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#815]
Add functionality to allow an arbitrary Pk to be transformed into 3d or projected correlation functions. (This is a stub issue. @slosar @damonge can add more details/requirements)

**Comment by jablazek** [comment]
Linking this issue to #818. We need to be able to use general Pk for the correlation functions to allow BAO damping.

**Comment by jablazek** [comment]
Re-pinging @slosar @damonge @c-d-leonard.

**Comment by slosar** [comment]
Yes, I can iterate that that would be very useful.
Note that when CCL is used in the calculator mode, this would be possible by construction. But likely cumbersome.
So supplying a k,Pk array or even better a function that returns P(k) given k would be ideal (the latter means that someone else needs to worry about range in k req'd for convergence in typical usage)

**Comment by jablazek** [comment]
linking to #743 #219 #744

**Comment by jablazek** [comment]
Been exploring this issue as part of Sprint Week. The simplest solution will be to generalize `lib.correlation_3d_vec` to accept arrays k,Pk. This is analogous to how `lib.correlation_vec` now accepts ell, C_ell. We could do something fancier to allow it to pass a function, but as a first option, I suggest the former. I can start fishing around in C code, but I am definitely not the best person for that. @damonge

**Comment by jablazek** [comment]
for future reference: line 450 of ccl_correlation.c can be augmented with an option to use the passed Pk array.

**Comment by jablazek** [comment]
@slosar @damonge : is it worth implementing this functionality, or should we just use the generic Pk that can be inserted into the CCL cosmology object?

**Comment by damonge** [comment]
sorry for the delay @jablazek . I think it'd be a lot neater to accept an external Pk2D object (or an array of k/Pk) rather than having to update the cosmology object every time. Also, it doesn't make sense to have, for instance, an HOD P(k) as the cosmology's matter power spectrum.

**Comment by jablazek** [comment]
@damonge : I agree with this approach. I assume we should just follow how it is done already with ccl.correlation(), which can ingest an arbitrary ell,C_ell, except in this case for it to be k,Pk.

**Comment by damonge** [comment]
@jablazek Note that this is addressed in #843 
One extra question is whether or not we really need the correlation spline functionality (seems a bit spurious to me, but maybe people are using it).
