### ISSUE TITLE
read_yaml 

### ISSUE THREAD

**Issue by empEvil** [LSSTDESC/CCL#817]
The current yaml reader for cosmology information, is not optimal. An example is that if you don't define `sigma8: 'nan'` then the reader will crash, if you are using `A_s` instead. It also can't seem to just load in the default values for a bunch of other parameters, `bcm_log10Mc`, `bcm_etab` e.g.

**Comment by joezuntz** [comment]
The yaml functions were things I added as a quick fix for things I wanted to do in TXPipe.  They're not at all flexible or generic, and are due for a revamp.

**Comment by damonge** [comment]
Closed by #852
