### ISSUE TITLE
Halo model enhancements

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#820]
There are a couple of nice things in the latest [hmcode paper](https://arxiv.org/abs/2009.01858) that would be nice to add to our halo model calculator functions:
- 1-halo large-scale damping
- smoothing out the transition region

There are many other interesting things in the paper, but these two would be trivial to implement.
And this would be a separate issue from that of allowing CCL to use the latest hmcode to compute the non-linear Pk.

**Comment by c-d-leonard** [comment]
@damonge is this the same as what is being worked on in PR #877 ?

**Comment by damonge** [comment]
Partly, yes (although this doesn't address the halo exclusion thing at low ell for 1-halo)

**Comment by nikfilippas** [comment]
I've implemented everything in #877 after Danielle's suggestion, and I've linked this to my PR.
