### ISSUE TITLE
Generic Cell integration failure with generalized tracers

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#823]
Here's a case of generic failure of Cell integation for pretty standard inputs. It would be great if we could investigate what drives this. @vitenti @damonge 

[Failed_integr_Cl.pdf](https://github.com/LSSTDESC/CCL/files/5309776/Failed_integr_Cl.pdf)

**Comment by damonge** [comment]
@elisachisari did you try to create one of these directly as a `WeakLensingTracer` setting `has_shear=False` (see [here](https://ccl.readthedocs.io/en/latest/api/pyccl.tracers.html#pyccl.tracers.WeakLensingTracer))?

**Comment by c-d-leonard** [comment]
@elisachisari bumping David's above question here

**Comment by elisachisari** [comment]
ay, yes, sorry! I might have tried that in the past, but not for this example. I'll give it a go and report back.

**Comment by elisachisari** [comment]
Ok, this option does work for the same cosmology and alignment bias. I also tried changing the `use_A_ia` keyword and it still completes the calculation. Do we understand the internal difference between this and creating a generalized tracer? @damonge

**Comment by c-d-leonard** [comment]
@damonge thoughts on Elisa's question above?

**Comment by damonge** [comment]
OK, almost two years later, here's the answer: this line
```
transfer_b1 = (sf,bi1)
```
should be changed to
```
transfer_b1 = (sf[::-1],bi1[::-1])
```
Because scale factors need to be monotonically increasing.

I'm gonna try and either document this better or make CCL throw a more useful message.
