### ISSUE TITLE
sub_lowk option for P_II

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#831]
Straightforward addition. Requires the necessary coefficient in front of sigma^4 term. And unit tests.

Pinging @elisachisari.

**Comment by c-d-leonard** [comment]
@jablazek would you be able to add a slightly more descriptive comment on what needs doing here? I'm going through the issues and I'm not sure what this one is about.

**Comment by jablazek** [comment]
The quadratic terms in biasing and IA have nonzero k->0 contributions to P(k). These are typically subtracted and absorbed into shot/shape noise. However, for numerical reasons, it is usually better to leave them in when transforming to correlation functions (otherwise, the k->inf contributions that come from subtracting a constant cause problems in the bessel transform). But for fourier space analyses and theory curves, we want to have the option to subtract these pieces. FAST-PT can do this with a few extra lines of code.
