### ISSUE TITLE
Deprecate `z_mg` and `df_mg`

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#842]
Has anyone ever used these parameters? Otherwise I think they should go.
https://github.com/LSSTDESC/CCL/blob/593ed60ce7d9763590856fd253e6683ca18269f5/pyccl/core.py#L131

**Comment by mishakb** [comment]
I think no-one ever used these. I agree they should probably go.

**Comment by c-d-leonard** [comment]
I never use them and I don't know of anyone who has. This was our first attempt at including modified gravity as I recall - we may have outgrown it. @TessaBaker @gvalogia any thoughts? (These parameters allow a general non-standard growth factor to be passed as an array - but I think this functionality is preserved in generality in @damonge's new 'Calculator Mode' which should be merged shortly, right David?)

**Comment by TessaBaker** [comment]
I haven't used these either. I think having a modified growth factor option is still desirable, but sounds like David has it covered?

**Comment by damonge** [comment]
Yes, I think keeping these now is superfluous. The calculator mode allows a lot more freedom, and losing these parameters would simplify the API in the next version significantly.

**Comment by c-d-leonard** [comment]
Cool, let's get rid of them!

**Comment by gvalogia** [comment]
Yes, I also don't think this feature is necessary. I can see the logic behind this, I haven't seen anyone using this parametrization recently.
