### ISSUE TITLE
unable to install ccl on Mac from the source repo

### ISSUE THREAD

**Issue by borisbolliet** [LSSTDESC/CCL#845]
Hi,

I was still running into the Cmake problem when I tried to install CCL from the source repo (python setup.py install). 

As far as I can tell, I have clean installs of CMake and all ccl dependencies. 

I tried all the things provided in a solution from a previous post : https://github.com/LSSTDESC/CCL/issues/542
but none seemed to work. 

The only way I could get the install to work was by adding shell=True in 

```
def _compile_ccl():
    call(["mkdir", "-p", "build"])
    v = sys.version_info
    if call(["cmake", "-H.", "-Bbuild",
             "-DPYTHON_VERSION=%d.%d.%d" % (
                v.major, v.minor, v.micro)],shell=True) != 0:
        raise Exception(
            "Could not run CMake configuration. Make sure "
            "CMake is installed !")
```

and by commenting out:

```
    if call(["make", "-Cbuild", "_ccllib"]) != 0:
         raise Exception("Could not build CCL")
```

in setup.py.

But I fear, this broke other things. 
Please let me know if there is a better solution to this problem. 

Thanks a lot,
Boris

**Comment by damonge** [comment]
@EiffL may be able to help here... I'm very useless with mac.

**Comment by EiffL** [comment]
ahah, happy to see if I can help, but really not a Mac expert/fan ^^'. 

@borisbolliet after doing this, are you able to import pyccl ? If yes, then you should be ok :-) , if not, then it means that you are missing some important compilation steps.

Could you post the error message you get when you try to run `python setup.py install` ?

**Comment by borisbolliet** [comment]
Hi @EiffL and @damonge ,

Thank you very much for your fast responses on my issues. I am very sorry to bother you with these Mac/system specific problems... 

So the full story is that when I do the modifs, and import pyccl I get the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/boris/Work/CLASS-SZ/SO-SZ/CCL/pyccl/__init__.py", line 16, in <module>
    from . import core, constants, background, power, halomodel, pk2d, haloprofile, halos, massfunction, nl_pt
  File "/Users/boris/Work/CLASS-SZ/SO-SZ/CCL/pyccl/core.py", line 29, in <module>
    None: lib.pknl_none,
AttributeError: module 'pyccl.ccllib' has no attribute 'pknl_none'


```

If I then go into core.py and comment: `None: lib.pknl_none`, then I am able to do import pyccl without error.

**Comment by damonge** [comment]
sounds to me like you have lingering old versions of ccl. I'd make sure all previous versions are removed and then reinstall.

**Comment by borisbolliet** [comment]
Yes! I deleted the entire repository and cloned it again. Now it installs out of the box without modifying anything!

Thanks a lot,
Boris
