### ISSUE TITLE
module 'pyccl.halos' has no attribute 'HaloProfilePressureGNFW'

### ISSUE THREAD

**Issue by borisbolliet** [LSSTDESC/CCL#846]
Hi,

With ccl installed via pip install pyccl, I am trying to compute tSZ power spectrum using the code in benchmarks/test_sz.py  but run into the following error:

module 'pyccl.halos' has no attribute 'HaloProfilePressureGNFW'

It seems the last version of CCL doesn't recognize HaloProfilePressureGNFW anymore. 

Boris

**Comment by damonge** [comment]
I'm not sure the latest halo model is in pip, unfortunately, and you may have to install it from github. Unfortunately I don't use mac and can't help much with the other issue you opened, but I'll take a look.

**Comment by borisbolliet** [comment]
and this, now using the ccl install from GitHub repo that works fine!... (see https://github.com/LSSTDESC/CCL/issues/845)
