### ISSUE TITLE
AttributeError: module 'pyccl' has no attribute 'CosmologyCalculator'

### ISSUE THREAD

**Issue by borisbolliet** [LSSTDESC/CCL#847]
With CCL installed via pip install pyccl,
I run into the following error when I try to compute cl^gg using the code in benchmarks/test_hod.py

**Comment by damonge** [comment]
Same reason as in #846

**Comment by borisbolliet** [comment]
Rreinstalling after cleaning everything solves that as well ! (https://github.com/LSSTDESC/CCL/issues/845)

Sorry I hadn't carefully checked that there wasn't anything from older ccl's left in my system. 

Now the fun can start ! :)
Thanks very much

**Comment by damonge** [comment]
This has happened many times before, no worries!
