### ISSUE TITLE
segfault with transfer_function= "boltzmann_class"?

### ISSUE THREAD

**Issue by borisbolliet** [LSSTDESC/CCL#848]
Using ccl from pip install pyccl, when I call:

    cosmo = ccl.Cosmology(
        Omega_b=float(p_dict['Omega_b']),
        Omega_c=float(p_dict['Omega_cdm']),
        h=float(p_dict['h']),
        n_s=float(p_dict['n_s']),
        A_s=float(p_dict['A_s']),
        w0=-1,
        wa=0,
        m_nu=float(p_dict['m_ncdm']),
        m_nu_type='normal',
        Neff=3.046,
        Omega_k=0,
        transfer_function= "boltzmann_class")

I get a segfault. Am I missing something about the initialization?

**Comment by damonge** [comment]
Can I check what parameters you're using?

**Comment by borisbolliet** [comment]
Thanks a lot for the responses !
Oh sorry, sure:
p_dict['m_ncdm']  = 0.
p_dict['Omega_b'] = 0.05
p_dict['Omega_cdm'] = 0.27
p_dict['h'] = 0.7
p_dict['n_s'] = 0.9645
p_dict['A_s'] = 2.2e-9 
(k_pivot at 0.05 h/Mpc)

**Comment by damonge** [comment]
OK, this doesn't segfault for me at all...
Did you make sure to remove all previous versions of ccl before installing? I can't see how that would cause this, but it doesn't hurt.

**Comment by borisbolliet** [comment]
solves this too! sorry about this.... thanks again!
