### ISSUE TITLE
add pushing to PyPi to GH Action

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/CCL#858]
[See Slack](https://lsstc.slack.com/archives/C46JK16F6/p1613500131104400). While waiting for the new CCL release to make it to PyPi and ultimately conda-forge, @EiffL noted this was an [automated process when using Travis-CI](https://lsstc.slack.com/archives/C46JK16F6/p1613659290108200?thread_ts=1613500131.104400&cid=C46JK16F6), which is now disabled. This bit could be added your existing GH workflow - right? That way, no one need worry about this again hopefully :)

**Comment by EiffL** [comment]
Thanks Heather for following up on this, I actually just found just the thing we need :-D 
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by damonge** [comment]
This was closed by #948
