### ISSUE TITLE
non-Limber integrator not impelmented yet?

### ISSUE THREAD

**Issue by gs66-uhtred** [LSSTDESC/CCL#862]
I'm trying to compute Cl(z,z') for narrow redshift windows. To get off-diagonal (z!=z') terms, I think I need to use something other than the Limber approximation (angpow), but when I try this I get an error claiming non-Limber integrator is not implemented yet. Is this true? The relevant code snippet is

ells = np.arange(3*2048) 
tracer_test1 = ccl.NumberCountsTracer(cosmo_cls, has_rsd=True, dndz = (zs1, dndz1), bias = (zs1, biases))
tracer_test2 = ccl.NumberCountsTracer(cosmo_cls, has_rsd=True, dndz = (zs1, dndz2), bias = (zs1, biases))
cl_test_11 = ccl.angular_cl(cosmo_cls, tracer_test1, tracer_test1, ells, l_limber = float(ells[-1]))

This raises the following error:

CCLError: Error CCL_ERROR_INCONSISTENT: ccl_cls.c: ccl_angular_cls_nonlimber(); non-Limber integrator not implemented yet

Any help would be appreciated.

**Comment by damonge** [comment]
@gs66-uhtred yes, unfortunately this is not implemented yet. We're in the process of selecting a non-Limber method to be implemented soon, so stay tuned!

**Comment by SergeiDBykov** [comment]
@damonge But the CCL paper (Chisari 2019, ApJS) states that non-limber integration is implemented for galaxy clustering tracers. Still it yields an error when using l_limber which is not -1. 
Is such integration not realised yet?
