### ISSUE TITLE
Improve documentation on CCL MG param handling.

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#867]
I'm finding that as of recently, it seems like changing the value of mu0 doesn't change the matter power spectrum. Here's a pdf of a notebook where I demonstrate that changing this parameter seems to have no effect at all on the linear matter power spectrum.
[check_mg_functionality.pdf](https://github.com/LSSTDESC/CCL/files/6213270/check_mg_functionality.pdf)

What's going on here? mu0 should definitely change the linear matter power spectrum, right? Am I missing something big?

@damonge @mishakb any ideas?

(My project student @OSmotherly initially identified this behaviour so I'm tagging him so that he can follow.)

**Comment by c-d-leonard** [comment]
Looking into this a bit more, seems like there are at least two different questions going on here:
- if you make a cosmology object with mu_0 != 0 and you leave the transfer_function as the default (boltzmann_camb), when you call ccl.linear_matter_power is you run through cosmo.compute_linear_power() (in core.py) which sends you to get_camb_pk_lin which happily returns the matter power spectrum ignoring MG parameters. I don't think this is the intended behaviour, I think it should naively rescale the power spectrum if not using isitgr. I'm digging more into this.
- if you do use boltzmann_isitgr as the transfer function, it seems that the linear matter power spectrum is only altered from its GR value at very large scales (k<10^{-3}). This is not what I would expect either, I'd expect to basically match naive rescaling at intermediate scales (linear but not very very large e.g. k=10^{-3}-10^{-2} at least).

This issue seems to persist as far back as v2.0.0 (probably further but that's the first tag with MG), weirdly. I'll keep looking into it.

**Comment by mishakb** [comment]
thanks for bringing these questions up and I will have a look as soon as I can. I just came out of a Black Hole of work (to be mathematically correct, let's say a White Hole since outgoing geodesics are allowed there).

**Comment by c-d-leonard** [comment]
I have figured out what's going on I think, for both cases. This was originating from the fact that I was setting my cosmology in terms of sigma8 rather than A_s and then looking at P(k) at z=0. I now recall that we agreed that if a cosmology is defined in terms of sigma8 with a non-zero mu0 value we should enforce that the power spectrum at z=0 behaves as it should for the defined sigma8. If I either define in terms of A_s or look at a different redshift, I get the expected behaviour both using rescaling with camb and using isitgr.

This behaviour with cosmologies with sigma8 and mu0!=0 is not clear in the docs as far as I can see. I think the action item for this issue should probably be to fix the docs which describe the parameters / Cosmology object to note this.
