### ISSUE TITLE
pickle issue with CCL in emcee

### ISSUE THREAD

**Issue by jablazek** [LSSTDESC/CCL#872]
This comes courtesy of Kai Hoffmann, which appeared when using CCL objects in multiprocessing in emcee. Relevant code to follow.

Error message:
-------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-efc69962aecd> in <module>
----> 1 fit_wgp(corr_rcut, p_cosmo, p_bias, p_nla_ini, fname_chain, redshift, 'nla')

<ipython-input-45-628f63090c22> in fit_wgp(data, p_cosmo, p_bias, p_IA_ini, fname_chain, redshift, IA_model)
     91             sampler.run_mcmc(initial, nstep, progress=True)
     92 
---> 93     run_mcmc(new_chain, nwalkers, ncore, nstep, fname_chain)
     94 
     95     return 0

<ipython-input-45-628f63090c22> in run_mcmc(new_chain, nwalkers, ncore, nstep, fname_chain)
     89             )
     90 
---> 91             sampler.run_mcmc(initial, nstep, progress=True)
     92 
     93     run_mcmc(new_chain, nwalkers, ncore, nstep, fname_chain)

~/.local/lib/python3.8/site-packages/emcee/ensemble.py in run_mcmc(self, initial_state, nsteps, **kwargs)
    382 
    383         results = None
--> 384         for results in self.sample(initial_state, iterations=nsteps, **kwargs):
    385             pass
    386 

~/.local/lib/python3.8/site-packages/emcee/ensemble.py in sample(self, initial_state, log_prob0, rstate0, blobs0, iterations, tune, skip_initial_state_check, thin_by, thin, store, progress)
    283             state.blobs = blobs0
    284         if state.log_prob is None:
--> 285             state.log_prob, state.blobs = self.compute_log_prob(state.coords)
    286         if np.shape(state.log_prob) != (self.nwalkers,):
    287             raise ValueError("incompatible input dimensions")

~/.local/lib/python3.8/site-packages/emcee/ensemble.py in compute_log_prob(self, coords)
    425                 map_func = map
    426             results = list(
--> 427                 map_func(self.log_prob_fn, (p[i] for i in range(len(p))))
    428             )
    429 

/usr/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

/usr/lib/python3.8/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    535                         break
    536                     try:
--> 537                         put(task)
    538                     except Exception as e:
    539                         job, idx = task[:2]

/usr/lib/python3.8/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/usr/lib/python3.8/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

AttributeError: Can't pickle local object 'fit_wgp.<locals>.log_probability'

**Comment by timothydmorton** [comment]
Is the `log_probability` function here defined by some chance within the `fit_wgp` function?  That could explain the pickling issue; might not have anything to do with CCL.  Could you post more of what `fit_wgp()` looks like?

**Comment by jablazek** [comment]
Hi @timothydmorton. Indeed, `log_probability` is defined inside `fit_wgp`. The code from my colleague is pasted below.

----

def fit_wgp(nwalkers, ncore, nstep, ndim, a1_ini):
    
    zz_loc = 0.5
    cosmo_loc = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, A_s=2.1e-9, n_s=0.96)
    ptc_loc = pt.PTCalculator(with_NC=True, with_IA=True, log10k_min=-5, log10k_max=2, nk_per_decade=20)
    ptt_g_loc = pt.PTNumberCountsTracer(b1=1, b2=0, bs=0)
    
    
    def log_likelihood_loc(a1):

        rp_model, wgp_model = get_wgp_nla(cosmo_loc, zz_loc, ptc_loc, ptt_g_loc, a1)

        wg_model_interpol = np.interp(data_glob.rp, rp_model, wgp_model)

        delta = (data_glob.wgp - wg_model_interpol)/data_glob.wgperr

        ll = -0.5 * np.dot(delta, delta)

        if np.isnan(ll):
            return -np.inf
        return ll
    
    
    def log_prior_loc(a1):
        if -10 < a1 < 20:
            return 0.0
        return -np.inf
    
    
    def log_probability_loc(p):

        a1 = p[0]

        lp = log_prior_loc(a1)

        if not np.isfinite(lp):
            return -np.inf
        return lp + log_likelihood_loc(a1)
    
    
    a1_ini = 1.
    initial = a1_ini + 0.1 * np.random.randn(nwalkers, ndim)

    with Pool(ncore) as pool:
        sampler = emcee.EnsembleSampler(
        nwalkers, 
        ndim,
        log_probability_loc,
        moves=[(emcee.moves.DEMove(), 0.8), (emcee.moves.DESnookerMove(), 0.2)],
        pool=pool
        )

        sampler.run_mcmc(initial, nstep, progress=True)

**Comment by timothydmorton** [comment]
This won't work because the transiently-defined function is not able to be pickled, and the parallelization within emcee happens by sending pickled objects around between processes.  The solution would be to refactor this code to make sure the log_prob function is defined at the outer level of the script, not within the function.

**Comment by timothydmorton** [comment]
To be more specific, if the entire `fit_wgp` were not a function but just a standalone script (e.g., everything currently defined within the function just moved to the outermost level of the .py file, and the function arguments either hardcoded or taken in via argparse), the above code should work as is.

**Comment by jablazek** [comment]
Thanks @timothydmorton ! Just to be sure, this has nothing to do with CCL? I will close the issue and pass this along.

**Comment by timothydmorton** [comment]
Correct.  To be clear, I don't know whether pickling might be an issue with CCL in general or not, but I know that the above would raise an error with emcee whatever the guts of the likelihood.  If a pickling error still shows up after moving everything to the top level, then you could re-open.
