### ISSUE TITLE
Star operator for keyword-only arguments

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#880]
Previous discussion on this was in #878 . The main point is that `ccl.Cosmology(0.25, 0.05, 0.65, 0.96, 0.81)` does not fail which opens two issues: readability, and the code being foolproof and futureproof.

On a closer look, these are two sides of the same coin. Obviously, `ccl.Cosmology` *should* require *all* arguments to be keyword-only. But what about functions like `rho_x(cosmo, a, species, is_comoving=False)`? This is not obvious at all.

### The `*` operator in increasing levels of strictness

1. *Essential*: changes that have to do with preventing CCL from silently failing (foolproof), and with making user code compatible with possible changes to the CCL function argument structure (futureproof). _Example_: `ccl.Cosmology(0.25, 0.05, 0.67, 0.81, 0.96)` will silently fail if we decide to swap the order of `sigma8` and `n_s` in the future, giving the wrong cosmology. _Solution_: Go through the entirety of Python code and, for all functions and public methods, add the `*` operator where two (or more) consecutive arguments can be swapped (e.g. accidentally) without the user realizing or CCL complaining. This applies to `Cosmology`, `update_parameters` methods, etc.
2. *Strict*: For example, `rho_x(cosmo, a, species, is_comoving=False)` can be called with `rho_x(cosmo, 1., "matter", True)`. It is not clear what `True` at the end refers to, so we might want to change the definition to `rho_x(cosmo, a, species, *, is_comoving=False)` in order to force users to call it like `rho_x(cosmo, 1. "matter", is_comoving=True)`.
3. *Stricter*: Although "matter" is somewhat self-explanatory, one can argue that `"matter"` is not clear either, and that users should know what the first and second arguments must be because they are used widely in CCL (`cosmo`, `a`). So we could change the definition to `rho_x(cosmo, a, *, species, is_comoving=False)` in order to force users to call it like `rho_x(cosmo, 1., species="matter", is_comoving=False)`.
4. *Strictest*: Apart from the obvious first argument, everything else *must* be keyword-only. Change the definition to `rho_x(cosmo, *, a, species, is_comoving=False)` in order to force users to call it like `rho_x(cosmo, a=1., species="matter", is_comoving=False)`. We should note, however, that although "species" and "is_comoving" are informative words, "a" is not, so is the code really more readable if we use this solution?

### My opinion (in bold)
Adding the `*` operator will unavoidably break some codes [1]. There is a balance between how many codes are we willing to break vs. how many codes deserve to break because they are badly written. What is a badly written code? Again, like @rmjarvis mentioned, codes written like `ccl.halos.halomod_power_spectrum(cosmo, hmc, k_arr, a_arr, p1, p2pt, p2, pka, True, False, False, True)` are very cryptic, so we might want to require explicit declaring of some arguments there.
On the other hand, argument names `cosmo`, `k`, `M`, `a`, `hmc`, `r` are not very informative (when read) because users will already have declared variables with very similar/self-explanatory names, and they also make the code look ugly (e.g. `cosmo=cosmo, k=k, M=M, a=a`). They also appear everywhere in CCL so it would require too much change for too little benefit.
To me, the sweet spot is adding the `*` before any arguments which are full words in English and one can't obviously infer the keyword from the argument value. For example, in `rho_x(cosmo, 1., "matter", True)`, arguments `cosmo` and `a` are OK to be positional because they are used widely in CCL. Argument `"matter"` obviously refers to `species` and it can't be read any other way. Argument `True` is not obvious at all and so we should require that it is explicitly stated. So the overall change would be: `rho_x(cosmo, a, species, *, is_comoving=False)`.
A similar thing happens with other popular libraries like `numpy` and `matplotlib`.

[1] We can avoid breaking *any* codes if we use the [https://github.com/flying-sheep/legacy-api-wrap](url) Mike mentioned in #878 . But this means:

- it would trigger so many warnings that the output of the run would be a complete mess, so the users would be forced, in a way, to make the changes (like in the cases where an error is thrown), OR
- the users would mute warnings, in which case we fall back to the main issue.
- Like I said, some badly written codes deserve to be broken. No one should expect a code containing the line `ccl.Cosmology(0.25, 0.05, 0.65, 0.96, 0.81)` to not have any other critical bugs. If anything, like Mike said, we're doing users a favour by adding the star.

**Comment by rmjarvis** [comment]
> it would trigger so many warnings that the output of the run would be a complete mess, so the users would be forced, in a way, to make the changes (like in the cases where an error is thrown)

It's only a mess if people care about looking at the output.  For scripts that people may have that already run correctly in a automated way, people probably already are redirecting the output to a log file they never look at.  So using legacy-api-wrap would let them continue to work until someone bothers to get around to changing the code (if they ever care about bothering to do so).

For users who are actively looking at the output, they will want to immediately change the code, which is what you are going for with this issue.

**Comment by rmjarvis** [comment]
FYI, here is the corresponding effort for TreeCorr: https://github.com/rmjarvis/TreeCorr/pull/129

I actually ended up reimplementing the legacy-api-wrap idea on my own, since I noticed it was licensed under GPL, so I can't use it.  [Here](https://github.com/rmjarvis/TreeCorr/blob/remove_2.7/treecorr/util.py#L927) is the version I wrote, which I call depr_pos_kwargs, since it deprecates positional arguments that are now kwarg-only.  It's a little simpler than the flying-sheep one, but it does everything I needed.

If you think it would be useful for your effort here, go ahead and copy it into CCL -- just give me credit by linking to the TreeCorr repo where the original lives, and I'll be happy.  :)

**Comment by nikfilippas** [comment]
That's great, thanks! Personally I'm still not fully convinced we need the deprecation decorator, but I'd like to hear what other people think on this.

Either way I think the main issue is deciding where to draw the line (on what level of strictness). For this we probably need input from people who use CCL a lot.

**Comment by nikfilippas** [comment]
@rmjarvis I also found [this](https://github.com/matplotlib/matplotlib/blob/89ce4fbdd10694520bd0727f5818e04b75ca96e7/lib/matplotlib/_api/deprecation.py#L454) implementation from `matplotlib` (which has a BSD license). Comparing it with your version, I think they are almost identical in their implementation.

**Comment by damonge** [comment]
I think I agree with most of this and it'd be good to implement it. I would **not** like to make everything keyword-only though, for some of the reasons @nikfilippas mentions.

At the same time, I like the deprecation warning, so could we mix @nikfilippas and @rmjarvis 's proposals? I.e., we implement the "essential changes" (or "essential" with some leeway to be stricter than that in certain functions) but we add the decorator to avoid breaking code.

**Comment by damonge** [comment]
I think I would do this again for V3, to avoid people getting too many warnings before then.

**Comment by nikfilippas** [comment]
@rmjarvis coming back to you on this: in your implementation of the API change decorator, only the star is accounted for, and possible changes in the sequence and/or names of the arguments is not handled. With the linked PR I'm doing all three: (star, renamings, order swaps), so I'd need a more generic wrapper. I could try re-writing the flying-sheep's implementation, but I'm worried this is already so many changes that the wrapper can't guarantee success in every deprecated function call usage.

For example, say that we have:
```
def func(a, b, c, d, e)
```
and we want to re-write it as:
```
def func(a, see, *, bee, d, e)
```

Then, the way I see it, even the flying-sheep's implementation won't work because there have been order swaps before the star.
In this case no decorator can save us from breaking API. Do you have any suggestions?

**Comment by rmjarvis** [comment]
If you're changing the order of positional parameters, then you're definitely breaking API, and I'd probably recommend bumping the major version.

But I don't think I quite grok the point of moving a later parameter forward and making it positional.  Can you give me the real-world use case of the above straw man?  I don't see why that kind of refactoring would be desirable.

**Comment by nikfilippas** [comment]
You're absolutely right. Going through the changes I've proposed, the order of all positional parameters hasn't changed. So no problem there in preserving API simply by adding a deprecation warning. At first, I thought we could possibly make the decorator more general by allowing the order of positional arguments to change, but we don't need this after all.

Correct me if I'm wrong, but the TreeCorr implementation indeed doesn't account for swaps and name changes, right? So I'm going to need to adapt my own version inspired from flying-sheep.

**Comment by rmjarvis** [comment]
I guess I don't really see a need for swaps in the order of kwargs after the * either other than cosmetic.  It wouldn't make any programmatic difference I don't think.  Only in the order of parameters listed in the docs I guess. 
Anyway, yes, my deprecation warner doesn't have that feature.  If you want to do any of that, you'll need to adapt it.

**Comment by nikfilippas** [comment]
Yes, there's no need, but I've proposed some changes anyway, mainly for consistency throughout CCL (for the docs).
