### ISSUE TITLE
Inconsistencies in function arguments

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#881]
I quickly went over the Python code and noticed inconsistencies in some of the function arguments:

1. Some of the CCL functions/methods have different names for arguments/quantities which are essentially the same. For example, `mdef`, `mass_def`, `m_def` are all used in the code. We should adopt uniform naming.
2. The ordering of some function arguments is not the same everywhere. For example, sometimes, `cosmo` is the first argument. Sometimes it is the last. Sometimes, `prof_2pt` goes before `prof2`. Sometimes it goes after. Like grammar rules, we should make a list of all arguments and decide on a universal ordering, and only allow for very specific deviations from this rule.

**Comment by damonge** [comment]
I agree with this. This will break the API (and a lot of existing code) though, so we should make it a milestone for v3.
@nikfilippas do you have a complete list of the specific inconsistencies you have seen (e.g. in which functions does cosmo not feature first)?

**Comment by nikfilippas** [comment]
I started making a list but it is difficult to do because I couldn't remember all the arguments I had already gone through. I think making a complete list of *all* arguments first would make things easier.
