### ISSUE TITLE
Rename cls.py to cells.py; Rename bcm.py to baryons.py.

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#886]
`cls` is a Python-reserved keyword for class methods ([PEP8](https://www.python.org/dev/peps/pep-0008/)).
I don't think it's good to have a module named `cls.py` just like we wouldn't have a module `self.py`.

**Comment by nikfilippas** [comment]
It even gets recognized by my editing programme and gets a different color.
![Screenshot from 2021-06-09 17-26-28](https://user-images.githubusercontent.com/22447385/121373673-f24e2280-c947-11eb-9cb3-f8f58a1c6b66.png)

**Comment by nikfilippas** [comment]
Renaming `bcm.py` to `baryons.py` will enable future addition of baryonic corrections to the power spectrum, other than the one currently implemented (Schneider & Teysser). Some interest in this has been indicated in #236 .
Also, "baryons" is a better name for a module that deals with baryons, just like there is a module named "neutrinos".

**Comment by c-d-leonard** [comment]
I agree that in general baryons is a better name and not opposed to changing to cells. Obviously need to trade this off against API breaking inconvenience for users, so this would be v3 earliest.

**Comment by nikfilippas** [comment]
No need to break API for any of those. I've implemented that in [this](https://github.com/LSSTDESC/CCL/pull/889/commits/49ce08964f4d28c02d54eb09e729df7e52351fe6) commit of PR #889 .

**Comment by c-d-leonard** [comment]
I was thinking in terms of modules paths but you're right I guess that doesn't technically affect the API.
