### ISSUE TITLE
Exception raised when requesting non-linear P(k) from CAMB with given sigma8

### ISSUE THREAD

**Issue by ahallcosmo** [LSSTDESC/CCL#896]
An error is raised when requesting the non-linear P(k) from CAMB and specifying sigma8, the code complaining about an inconsistent rescaling of the non-linear power spectrum (see https://github.com/LSSTDESC/CCL/pull/854/commits/0f20e189fadaacc76a58fbbeb4f5a9a2dd693d65). I don't see why this should be though given that sigma8 is always computed from the linear power spectrum? @tilmantroester

**Comment by damonge** [comment]
I missed this one. @tilmantroester what's the logic for that?

**Comment by damonge** [comment]
oh, I think I understand: if we were computing the PK_nonlinear in CCL, everything would be fine. We just call camb to get the linear power spectrum, scale that to get the right sigma8, and then apply halofit to it.
However, if we compute it from camb, we can't specify sigma8 for the linear power spectrum. We'd need to call camb with a trial A_s, get the linear power spectrum, figure out the rescaling factor to get the right sigma8, then call CAMB again to get the linear and non-linear power spectra. This would involve two calls to camb, which is not ideal. @tilmantroester can confirm that this is the logic. @ahallcosmo does it make sense?

**Comment by tilmantroester** [comment]
Yes, that's the case. CAMB only takes A_s as an input; any other amplitude parameterisation is done outside of CAMB. Once you get any non-linear quantity from CAMB, you're stuck with using A_s, because rescaling doesn't work anymore.

**Comment by ahallcosmo** [comment]
But as David says I could call CAMB twice, first to determine how to scale a fiducial A_s to the target sigma8 and second to get the non-linear power (at least that's what I usually do). If this isn't implemented though then perhaps the error message could be reworded to reflect that (or raise a NotImplementedError).

**Comment by damonge** [comment]
Right, we want to avoid users calling CAMB twice inadvertently (this was a problem before), so I don't see us implementing this in the future.  We could be a bit clearer in the error message.

Note that if this is an issue, you can call CAMB separately from CCL to get the linear and non-linear Pks, and then pass those to CCL through the `CosmologyCalculator` class to then do your favourite CCL operations (e.g. compute C_ells or whatever)

**Comment by elisachisari** [comment]
Can we close this one? @ahallcosmo

**Comment by ahallcosmo** [comment]
Yes happy for this to be closed.
