### ISSUE TITLE
Compare angular power spectrum with CAMB

### ISSUE THREAD

**Issue by SergeiDBykov** [LSSTDESC/CCL#902]
Hi there.
I am trying to calculate (auto-) angular power spectrum (APS) of some source distribution (given by dn/dz) with CCL and CAMB using pyccl and CAMB python wrapper.

To do that I need to pass a correct cosmology from CCL to CAMB, for example. 
I do so as the in the [following code](https://ccl.readthedocs.io/en/latest/_modules/pyccl/boltzmann.html#get_camb_pk_lin) code from CCL internals, please see [this gist](https://gist.github.com/SergeiDBykov/5b4d0ac049640814010125c1aa948fc5). 

After that I calculate cls with CAMB and CCL and compare. I get the following picture:
![9fae52d2-ad1f-4620-8754-101e33841810](https://user-images.githubusercontent.com/60148493/128373988-be92bd54-e002-43cb-9db8-27d347d6dcd4.png)

The discrepancy at large angular scales (small ell) is understandable as the limber approximation used in all CCL calculations, but one may also see that the spectra are different at larger l up to 2.5%.

I was wondering of why is that. Probably I translated pyccl.cosmology erroneously to CAMB input.
If the cosmology translated correctly, what could go wrong?

Thank you!

**Comment by damonge** [comment]
Hi @SergeiDBykov 
In order to figure out whether this is due to Limber or something else, have you compared against CAMB using the Limber approximation? I see the window function you're using has hard edges, so that could make the Limber approximation less accurate than one would expect.

**Comment by SergeiDBykov** [comment]
Thanks for the answer, @damonge!
Yes I tried, but I cannot force CAMB to use limber approximation, it ignores my `cp.SourceTerms.limber_phi_lmin = 1` argument, it changes almost nothing in the Cl.

I calculated Cl without limber approximation  myself and seems that my result is close to the one of CAMB with 2.5% normalisation difference.

**Comment by SergeiDBykov** [comment]
@damonge Hi! I also figured out that there might be not due to the limber integration, but due to the wrongly assigned cosmological parameters. 
When assigning Omega_b = 0.1 in the gist above, the curves from CCL and CAMB do not match at all, having a difference of ~20-30% at large l values. 
So probably the original question should be reformulated:
Why the Cell in CAMB and CCL responses differently on changing, say, Omega_b (please see plot attached)?
I translate CCL cosmo into CAMB camb.model.CAMBparams just at in [this module](https://ccl.readthedocs.io/en/latest/_modules/pyccl/boltzmann.html#get_camb_pk_lin).
Both cosmologies stay flat when I change parameters.
![ad89c3d0-7fd3-4b10-84bf-136c5d93ba3d](https://user-images.githubusercontent.com/60148493/128702672-563fc20f-b96c-4c1a-9556-c887ac3fdeff.png)

I don't see reason why they predict different Cells.

Thanks.

**Comment by c-d-leonard** [comment]
Thsi is very odd @SergeiDBykov, did you ever figure out what was going on here?

**Comment by SergeiDBykov** [comment]
Hi @c-d-leonard. Thanks for the follow-up.
Sorry for not updating the issue.

Indeed I managed to get less than 1 per cent difference in auto-Cell between the codes when wrapped CAMB code into a function calculations so that it adjusts its A_s value by calculating sigma8 for a given cosmology and scales angular spectra accordingly (https://github.com/LSSTDESC/CCL/issues/902#issuecomment-895164370).
The difference is small, ~1%, but still present.
I think I can close it now.
Thank you.
