### ISSUE TITLE
delta-like redshift distribution error

### ISSUE THREAD

**Issue by ShimingGu** [LSSTDESC/CCL#919]
Hi CCL Team,
I am working on a project that may need a very narrow redshift range of foreground galaxy lenses. If I run the following codes:
```
# Generate a delta-like n(z)
n_bin_z_lens = 101
z_lens = np.linspace(0.0,3.0,n_bin_z_lens)
n_z_lens = np.zeros_like(z_lens)
n_z_lens[50] = 1
# Compute the galaxy-galaxy lensing C_\ell
tracer_lens = ccl.NumberCountsTracer(cosmo, has_rsd=False, dndz=(z_lens,nz_lens), bias=(z_lens,bias_z_lens), mag_bias=None)
tracer_source = ccl.WeakLensingTracer(cosmo, dndz=(z_source,n_z_source), has_shear=True, ia_bias=None)
cl_ggl = ccl.angular_cl(cosmo, tracer_lens, tracer_source, l_arr)
```
it brings the error
`ccl_cls.c: ccl_angular_cls_limber(); integration error`
This error disappears when I also put
`n_z_lens[51] = 1` 
if given a relatively smaller number of redshift bins like 
`n_bin_z_lens = 101`
in the above example. However, that problem still persists when the number of redshift bins goes to a larger number -- when my redshift distribution approach to a Dirac-delta function even if it has more than one non-zero value. It looks like an intrinsic characteristic in pyccl and I don't know how to deal with it if I want better approximations to a very narrow redshift distribution. 

I am very grateful if anyone would be interested to have a look at this problem and tell me how to deal with it.

Have a great day and Thank you so much!

**Comment by tilmantroester** [comment]
Internally, CCL uses spline interpolation for the window functions and then adaptive quadrature for the integral. Neiter is particuarly suited to deal with delta functions. Since the window function for the lenses is just the lens n(z), you could write skip the Limber integral all together and write it as prefector * W(z_lens) * P(k(l, z_lens), z_lens).

**Comment by damonge** [comment]
#928 seems to have solved this (I don't get an error anyore)

**Comment by tilmantroester** [comment]
I don't remember if there's a tests for such a pathological n(z). So I would check if the results make sense first.

**Comment by damonge** [comment]
Looks good to me
![clfine](https://user-images.githubusercontent.com/8809493/183121159-6af8b659-963b-4a51-ba01-10b7e7dffb09.png)

**Comment by ShimingGu** [comment]
Oh Thanks David and Tilman! I almost forgot that I had raised this issue lol.

**Comment by damonge** [comment]
Yeah, sorry we were so slow...
