### ISSUE TITLE
NFW `fourier_analytic` flag default value

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CCL#959]
In `pyccl/halos/profiles.py` line [662](https://github.com/LSSTDESC/CCL/blob/77624d223e4873ddaaf5e701ad2b723646f2a14d/pyccl/halos/profiles.py#L662), the default value for the flag `fourier_analytic` of an NFW profile is `True`. It is inconsistent with the docstring in line 648, which state that the default value is `False`.

**Comment by nikfilippas** [comment]
Note to whoever takes it up: in #934 I have deprecated this keyword because if we have the analytic version, which is faster than FFTLog, there is no reason to choose `fourier_analytic=False`. So I've simply renamed method `_fourier_analytic` to `_fourier`.
