### ISSUE TITLE
Unexpected change in mag bias behaviour

### ISSUE THREAD

**Issue by itrharrison** [LSSTDESC/CCL#962]
It seems between v2.3 and v2.4 the behaviour of mag bias kernels changed. In particular, I would expect a value of `s = 0.4` to return a kernel of 0 and this was the case in v <= 2.3

For v2.4 (and now v2.5) it seems to be `s = 0` which returns a kernel of 0.

Attached is a minimal example, which gives:

```
2.3.0
mag bias kernel at s=0.0 are not zero!
mag bias kernel at s=0.4 all zero
```

```
2.4.0
mag bias kernel at s=0.0 all zero
mag bias kernel at s=0.4 are not zero!
```

```
2.5.0
mag bias kernel at s=0.0 all zero
mag bias kernel at s=0.4 are not zero!
```
[ccl_mag_bug.py.txt](https://github.com/LSSTDESC/CCL/files/9234464/ccl_mag_bug.py.txt)

**Comment by damonge** [comment]
@itrharrison thanks a lot for flagging this. #963 should fix it. This is a bad enough bug that I'll tag a new release after it's been merged (incidentally, I'm pretty sure the origin is #928).

Would you be happy to give #963 a quick review?

**Comment by itrharrison** [comment]
Sure! Happy for you to tag me for a review when it's ready.

**Comment by damonge** [comment]
Ready! just tagged you
