### ISSUE TITLE
Update `Neff = 3.044` (and revert #1024)

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#964]
https://arxiv.org/abs/2008.01074
https://arxiv.org/abs/2012.02726

**Comment by hsinfan1996** [comment]
Related to #1024

**Comment by nikfilippas** [comment]
Does that mean we can relax the req `camb=1.3.6` after we update `Neff`? Is that way the test was failing?

**Comment by hsinfan1996** [comment]
Yes, by setting Neff to 3.044, the failed test passes.

**Comment by damonge** [comment]
I'm pretty sure this is done (https://github.com/LSSTDESC/CCL/blob/cad503b71d7c7bba70bbd0b62e3d187d50268669/pyccl/cosmology.py#L235). Reopen otherwise.

**Comment by hsinfan1996** [comment]
We are still using `camb==1.3.6` in the CI checks. Do we want to use the latest version? We will need to change line 44 of `test_nonlin_camb_power.py`.
https://github.com/LSSTDESC/CCL/blob/master/pyccl/tests/test_nonlin_camb_power.py#L44

**Comment by damonge** [comment]
Ah, right, I forgot about that. Yes, I think we do.
