### ISSUE TITLE
`pk_nl` not computed with `mps == "camb"` and `tf != "boltzmann_camb"`

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#978]
Slightly odd usage, but if we want to get the camb non-linear power spectrum with a non-camb transfer function, the non-linear matter power spectrum never computes.
``` python
cosmo = ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, h=0.67, n_s=0.96, A_s=2.34e-9,
                      transfer_function="boltzmann_class",
                      matter_power_spectrum="camb")
cosmo.compute_nonlin_power()  # doesn't complain
assert cosmo.get_nonlin_power() is None
```

**Comment by damonge** [comment]
The reason: it is a very, very inefficient thing to do, and not generally useful. I'd rather not adapt the code to allow this. For testing purposes one can always use the calculator mode.
