### ISSUE TITLE
covariance integration error

### ISSUE THREAD

**Issue by YaoQianli** [LSSTDESC/CCL#990]
Hello,
I was trying to use the connected non-Gaussian covariance and super-sample covariance in CCL. I assumed Planck cosmology, some redshift distribution, galaxy number density, shape noise to test the code, and set up the halo model part for the calculation. But it gives me the following error, for both connected non-Gaussian cov and super-sample cov. 
The CCL version I used is 2.5.1. I also used a 2.3 or 2.4 version before, but the errors are the same.
Can you help me fix this? Thanks!

```
---------------------------------------------------------------------------
CCLError                                  Traceback (most recent call last)
Input In [19], in <cell line: 5>()
      3 tracer_Gm = ccl.WeakLensingTracer(cosmo,dndz=(z+Dz,nz_tomo[1,:]),ia_bias=(z,AIA))
      4 tracer_Gn = ccl.WeakLensingTracer(cosmo,dndz=(z+Dz,nz_tomo[1,:]),ia_bias=(z,AIA))
----> 5 cov_cNG = ccl.angular_cl_cov_cNG(cosmo=cosmo,
      6                        cltracer1=tracer_Gi, cltracer2=tracer_Gj,
      7                        cltracer3=tracer_Gm, cltracer4=tracer_Gn,
      8                        ell=ell,
      9                        tkka=tk3d_1h,
     10                        fsky=f_sky )
     11 cov_SSC = ccl.angular_cl_cov_SSC(cosmo=cosmo,
     12                        cltracer1=tracer_Gi, cltracer2=tracer_Gj,
     13                        cltracer3=tracer_Gm, cltracer4=tracer_Gn,
     14                        ell=ell,
     15                        tkka=tk3d_SSC,
     16                        fsky=f_sky )

File ~/Research/anaconda3/envs/env1/lib/python3.9/site-packages/pyccl/covariances.py:130, in angular_cl_cov_cNG(cosmo, cltracer1, cltracer2, ell, tkka, fsky, cltracer3, cltracer4, ell2, integration_method)
    127 if cltracer4 is not None:
    128     lib.cl_tracer_collection_t_free(clt4)
--> 130 check(status, cosmo=cosmo_in)
    131 return cov

File ~/Research/anaconda3/envs/env1/lib/python3.9/site-packages/pyccl/pyutils.py:49, in check(status, cosmo)
     47 # Check for known error status
     48 if status in error_types.keys():
---> 49     raise CCLError("Error %s: %s" % (error_types[status], msg))
     51 # Check for unknown error
     52 if status != 0:

CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cov_limber(); integration error
```

**Comment by tilmantroester** [comment]
Is there something being printed to stderr?

**Comment by elisachisari** [comment]
Looks like you could lower the precision required from the Limber integration: https://ccl.readthedocs.io/en/latest/source/notation_and_other_cosmological_conventions.html?highlight=limber#controlling-splines-and-numerical-accuracy

**Comment by YaoQianli** [comment]
Sorry, I was working on something else and forgot to get back on this.
I haven't tried what Elisa suggested, but I use `integration_method = 'spline' `in `angular_cl_cov_cNG ` and it's not reporting the error anymore. Please let me know if this solution sounds reasonable or not.

**Comment by damonge** [comment]
OK, great! Yes, that should do the trick (although trying Elisa's suggestion would be good to make sure the result you're getting makes sense).
